-- Accounts are the tenant. A user is one person (one phone number) who can belong to several
-- accounts through memberships, for example a caretaker who works for two owners.
--
-- Primary keys are UUIDv7 generated by the API, so tables have no id default.

-- +goose Up
-- +goose StatementBegin
CREATE FUNCTION set_updated_at() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
    NEW.updated_at := now();
    RETURN NEW;
END;
$$;
-- +goose StatementEnd

CREATE TABLE accounts (
    id                      uuid        PRIMARY KEY,
    name                    text        NOT NULL CHECK (char_length(name) BETWEEN 1 AND 120),
    status                  text        NOT NULL DEFAULT 'trial'
                            CHECK (status IN ('trial', 'active', 'grace', 'lapsed', 'closed')),
    trial_started_at        timestamptz NOT NULL DEFAULT now(),
    first_direct_booking_at timestamptz,
    created_at              timestamptz NOT NULL DEFAULT now(),
    updated_at              timestamptz NOT NULL DEFAULT now()
);

CREATE TRIGGER accounts_updated_at BEFORE UPDATE ON accounts
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TABLE users (
    id         uuid        PRIMARY KEY,
    phone      text        NOT NULL UNIQUE CHECK (phone ~ '^\+[1-9][0-9]{6,14}$'),
    name       text        NOT NULL DEFAULT '' CHECK (char_length(name) <= 80),
    email      text        CHECK (email IS NULL OR char_length(email) <= 254),
    language   text        NOT NULL DEFAULT 'en' CHECK (language IN ('en', 'si')),
    photo_key  text,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TRIGGER users_updated_at BEFORE UPDATE ON users
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TABLE memberships (
    id         uuid        PRIMARY KEY,
    account_id uuid        NOT NULL REFERENCES accounts (id) ON DELETE CASCADE,
    user_id    uuid        NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    role       text        NOT NULL CHECK (role IN ('owner', 'manager', 'caretaker')),
    status     text        NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'suspended')),
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (account_id, user_id),
    -- Lets child rows reference a membership together with its account.
    UNIQUE (id, account_id)
);

CREATE INDEX memberships_user_id_idx ON memberships (user_id);

CREATE TRIGGER memberships_updated_at BEFORE UPDATE ON memberships
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- +goose Down
DROP TABLE memberships;
DROP TABLE users;
DROP TABLE accounts;
DROP FUNCTION set_updated_at();
