#!/usr/bin/env bash
# Antigravity-native duplicate of hooks/claude/warn-large-files.sh.
# Blocks writes to build artifacts, binary files, and dependency directories.
# PreToolUse hook. Reads Antigravity's {"toolCall":{"name","args"}} stdin;
# always exits 0 -- the decision lives in stdout, not the exit code.
#
# ponytail: intentionally duplicated logic, not shared with the Claude-side
# script (dir-per-host, no translation shim). Keep both in sync by hand when
# detection rules change.

set -uo pipefail

allow() {
  printf '{"decision":"allow"}\n'
  exit 0
}
gate() {
  jq -cn --arg d "$1" --arg r "$2" '{decision:$d, reason:$r}'
  exit 0
}

command -v jq >/dev/null 2>&1 || {
  printf '{"decision":"deny","reason":"jq is required for file protection hooks but is not installed."}\n'
  exit 0
}

INPUT=$(cat)
FILE_PATH=$(printf '%s' "$INPUT" | jq -r '.toolCall.args.TargetFile // empty' 2>/dev/null || true)
[ -z "$FILE_PATH" ] && allow

# Block dependency and build directories
case "$FILE_PATH" in
  node_modules/* | */node_modules/*)
    gate deny "Cannot write into node_modules/. Install dependencies via package manager instead."
    ;;
  vendor/* | */vendor/*)
    gate deny "Cannot write into vendor/. Use dependency manager instead."
    ;;
  dist/* | */dist/* | build/* | */build/* | .next/* | */.next/*)
    gate deny "Cannot write into build output directories. These are generated by the build process."
    ;;
  __pycache__/* | */__pycache__/*)
    gate deny "Cannot write into __pycache__/. These are generated by Python."
    ;;
  .venv/* | */.venv/* | venv/* | */venv/*)
    gate deny "Cannot write into virtual environment directories."
    ;;
esac

# Block binary and archive file extensions
BASENAME=$(basename -- "$FILE_PATH")
case "$BASENAME" in
  *.wasm | *.so | *.dylib | *.dll | *.exe | *.o | *.a)
    gate deny "Cannot write binary files. These should be compiled, not hand-written."
    ;;
  *.zip | *.tar | *.tar.gz | *.tar.bz2 | *.tgz | *.rar | *.7z)
    gate deny "Cannot write archive files."
    ;;
  *.mp4 | *.mov | *.avi | *.mkv | *.mp3 | *.wav | *.flac)
    gate deny "Cannot write media files. Add these manually outside Claude Code."
    ;;
  *.pyc | *.pyo | *.class)
    gate deny "Cannot write compiled bytecode files."
    ;;
esac

allow
