import type { SymbolViewProps } from "expo-symbols";

type Name = SymbolViewProps["name"];

const sym = (ios: string, material: string) => ({ ios, android: material, web: material }) as Name;

/** SF Symbols on iOS, Material Symbols on Android and web. */
export const I = {
  back: sym("chevron.left", "arrow_back"),
  close: sym("xmark", "close"),
  plus: sym("plus", "add"),
  bell: sym("bell", "notifications"),
  bellOn: sym("bell.badge", "notifications_active"),
  calendar: sym("calendar", "calendar_month"),
  chat: sym("message", "chat"),
  phone: sym("phone", "call"),
  mail: sym("envelope", "mail"),
  more: sym("ellipsis", "more_horiz"),
  search: sym("magnifyingglass", "search"),
  filter: sym("line.3.horizontal.decrease", "tune"),
  share: sym("square.and.arrow.up", "share"),
  copy: sym("doc.on.doc", "content_copy"),
  link: sym("link", "link"),
  globe: sym("globe", "public"),
  photo: sym("photo.on.rectangle", "image"),
  bed: sym("bed.double", "bed"),
  tag: sym("tag", "sell"),
  rules: sym("list.bullet.rectangle", "rule"),
  doc: sym("doc.text", "description"),
  percent: sym("percent", "percent"),
  card: sym("creditcard", "credit_card"),
  bank: sym("building.columns", "account_balance"),
  cash: sym("banknote", "payments"),
  settings: sym("gearshape", "settings"),
  brush: sym("paintbrush", "palette"),
  qr: sym("qrcode", "qr_code_2"),
  sync: sym("arrow.triangle.2.circlepath", "sync"),
  team: sym("person.2", "group"),
  template: sym("text.bubble", "forum"),
  crown: sym("star.circle", "workspace_premium"),
  person: sym("person.crop.circle", "person"),
  help: sym("questionmark.circle", "help"),
  insights: sym("chart.bar", "insights"),
  activity: sym("clock.arrow.circlepath", "history"),
  lock: sym("lock", "lock"),
  check: sym("checkmark", "check"),
  house: sym("house", "home"),
  gift: sym("gift", "redeem"),
  ticket: sym("ticket", "confirmation_number"),
  trash: sym("trash", "delete"),
  edit: sym("pencil", "edit"),
  moon: sym("moon", "nights_stay"),
  key: sym("key", "key"),
  logout: sym("rectangle.portrait.and.arrow.right", "logout"),
  chevronLeft: sym("chevron.left", "chevron_left"),
  chevronRight: sym("chevron.right", "chevron_right"),
  chevronDown: sym("chevron.down", "expand_more"),
  wrench: sym("wrench.and.screwdriver", "build"),
  sparkles: sym("sparkles", "auto_awesome"),
  restart: sym("arrow.counterclockwise", "restart_alt"),
  pin: sym("mappin.and.ellipse", "location_on"),
  clock: sym("clock", "schedule"),
  upload: sym("square.and.arrow.down", "download"),
  eye: sym("eye", "visibility"),
  block: sym("nosign", "block"),
  warning: sym("exclamationmark.triangle", "warning"),
  people: sym("person.3", "groups"),
  code: sym("chevron.left.forwardslash.chevron.right", "code"),
  arrowIn: sym("arrow.down.right.circle", "login"),
  arrowOut: sym("arrow.up.right.circle", "logout"),
  wifi: sym("wifi.exclamationmark", "wifi_off"),
} satisfies Record<string, Name>;
