// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: accounts.sql

package queries

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const addMembershipProperty = `-- name: AddMembershipProperty :exec
INSERT INTO membership_properties (account_id, membership_id, property_id)
VALUES ($1, $2, $3)
`

type AddMembershipPropertyParams struct {
	AccountID    uuid.UUID
	MembershipID uuid.UUID
	PropertyID   uuid.UUID
}

func (q *Queries) AddMembershipProperty(ctx context.Context, arg AddMembershipPropertyParams) error {
	_, err := q.db.Exec(ctx, addMembershipProperty, arg.AccountID, arg.MembershipID, arg.PropertyID)
	return err
}

const createAccount = `-- name: CreateAccount :one
INSERT INTO accounts (id, name) VALUES ($1, $2)
RETURNING id, name, status, trial_started_at, first_direct_booking_at, created_at, updated_at, booking_seq
`

type CreateAccountParams struct {
	ID   uuid.UUID
	Name string
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error) {
	row := q.db.QueryRow(ctx, createAccount, arg.ID, arg.Name)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Status,
		&i.TrialStartedAt,
		&i.FirstDirectBookingAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.BookingSeq,
	)
	return i, err
}

const createInvite = `-- name: CreateInvite :exec
INSERT INTO invites (id, account_id, phone, name, role, property_ids, token_hash, invited_by, expires_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
`

type CreateInviteParams struct {
	ID          uuid.UUID
	AccountID   uuid.UUID
	Phone       string
	Name        string
	Role        string
	PropertyIds []uuid.UUID
	TokenHash   []byte
	InvitedBy   *uuid.UUID
	ExpiresAt   time.Time
}

func (q *Queries) CreateInvite(ctx context.Context, arg CreateInviteParams) error {
	_, err := q.db.Exec(ctx, createInvite,
		arg.ID,
		arg.AccountID,
		arg.Phone,
		arg.Name,
		arg.Role,
		arg.PropertyIds,
		arg.TokenHash,
		arg.InvitedBy,
		arg.ExpiresAt,
	)
	return err
}

const createMembership = `-- name: CreateMembership :one
INSERT INTO memberships (id, account_id, user_id, role) VALUES ($1, $2, $3, $4)
RETURNING id, account_id, user_id, role, status, created_at, updated_at
`

type CreateMembershipParams struct {
	ID        uuid.UUID
	AccountID uuid.UUID
	UserID    uuid.UUID
	Role      string
}

func (q *Queries) CreateMembership(ctx context.Context, arg CreateMembershipParams) (Membership, error) {
	row := q.db.QueryRow(ctx, createMembership,
		arg.ID,
		arg.AccountID,
		arg.UserID,
		arg.Role,
	)
	var i Membership
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.UserID,
		&i.Role,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteAccount = `-- name: DeleteAccount :exec
DELETE FROM accounts WHERE id = $1
`

func (q *Queries) DeleteAccount(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteAccount, id)
	return err
}

const getMembership = `-- name: GetMembership :one
SELECT m.id, m.account_id, m.user_id, m.role,
       coalesce(array_agg(mp.property_id ORDER BY mp.property_id)
                FILTER (WHERE mp.property_id IS NOT NULL), '{}')::uuid[] AS property_ids
FROM memberships m
JOIN accounts a ON a.id = m.account_id
LEFT JOIN membership_properties mp ON mp.membership_id = m.id
WHERE m.user_id = $1 AND m.account_id = $2
  AND m.status = 'active' AND a.status <> 'closed'
GROUP BY m.id
`

type GetMembershipParams struct {
	UserID    uuid.UUID
	AccountID uuid.UUID
}

type GetMembershipRow struct {
	ID          uuid.UUID
	AccountID   uuid.UUID
	UserID      uuid.UUID
	Role        string
	PropertyIds []uuid.UUID
}

// The tenant lookup behind every owner route.
func (q *Queries) GetMembership(ctx context.Context, arg GetMembershipParams) (GetMembershipRow, error) {
	row := q.db.QueryRow(ctx, getMembership, arg.UserID, arg.AccountID)
	var i GetMembershipRow
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.UserID,
		&i.Role,
		&i.PropertyIds,
	)
	return i, err
}

const listAccountsForUser = `-- name: ListAccountsForUser :many
SELECT a.id, a.name, a.status, a.trial_started_at, a.created_at,
       m.id AS membership_id, m.role,
       coalesce(array_agg(mp.property_id ORDER BY mp.property_id)
                FILTER (WHERE mp.property_id IS NOT NULL), '{}')::uuid[] AS property_ids
FROM memberships m
JOIN accounts a ON a.id = m.account_id
LEFT JOIN membership_properties mp ON mp.membership_id = m.id
WHERE m.user_id = $1 AND m.status = 'active' AND a.status <> 'closed'
GROUP BY a.id, m.id
ORDER BY m.created_at, m.id
`

type ListAccountsForUserRow struct {
	ID             uuid.UUID
	Name           string
	Status         string
	TrialStartedAt time.Time
	CreatedAt      time.Time
	MembershipID   uuid.UUID
	Role           string
	PropertyIds    []uuid.UUID
}

func (q *Queries) ListAccountsForUser(ctx context.Context, userID uuid.UUID) ([]ListAccountsForUserRow, error) {
	rows, err := q.db.Query(ctx, listAccountsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAccountsForUserRow{}
	for rows.Next() {
		var i ListAccountsForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Status,
			&i.TrialStartedAt,
			&i.CreatedAt,
			&i.MembershipID,
			&i.Role,
			&i.PropertyIds,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
