// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth.sql

package queries

import (
	"context"
	"net/netip"
	"time"

	"github.com/google/uuid"
)

const consumeOTP = `-- name: ConsumeOTP :exec
UPDATE otp_challenges SET consumed_at = $1::timestamptz WHERE id = $2
`

type ConsumeOTPParams struct {
	Now time.Time
	ID  uuid.UUID
}

func (q *Queries) ConsumeOTP(ctx context.Context, arg ConsumeOTPParams) error {
	_, err := q.db.Exec(ctx, consumeOTP, arg.Now, arg.ID)
	return err
}

const createOTPChallenge = `-- name: CreateOTPChallenge :exec
INSERT INTO otp_challenges (id, phone, code_hash, ip, expires_at, created_at)
VALUES ($1, $2, $3, $4, $5, $6)
`

type CreateOTPChallengeParams struct {
	ID        uuid.UUID
	Phone     string
	CodeHash  []byte
	Ip        *netip.Addr
	ExpiresAt time.Time
	CreatedAt time.Time
}

func (q *Queries) CreateOTPChallenge(ctx context.Context, arg CreateOTPChallengeParams) error {
	_, err := q.db.Exec(ctx, createOTPChallenge,
		arg.ID,
		arg.Phone,
		arg.CodeHash,
		arg.Ip,
		arg.ExpiresAt,
		arg.CreatedAt,
	)
	return err
}

const createSession = `-- name: CreateSession :exec
INSERT INTO sessions (id, user_id, refresh_hash, device_name, rotated_at, last_used_at, expires_at, created_at)
VALUES ($1, $2, $3, $4, $5, $5, $6, $5)
`

type CreateSessionParams struct {
	ID          uuid.UUID
	UserID      uuid.UUID
	RefreshHash []byte
	DeviceName  string
	Now         time.Time
	ExpiresAt   time.Time
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.Exec(ctx, createSession,
		arg.ID,
		arg.UserID,
		arg.RefreshHash,
		arg.DeviceName,
		arg.Now,
		arg.ExpiresAt,
	)
	return err
}

const getActiveSessionUser = `-- name: GetActiveSessionUser :one
SELECT user_id FROM sessions WHERE id = $1 AND revoked_at IS NULL AND expires_at > $2
`

type GetActiveSessionUserParams struct {
	ID  uuid.UUID
	Now time.Time
}

func (q *Queries) GetActiveSessionUser(ctx context.Context, arg GetActiveSessionUserParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getActiveSessionUser, arg.ID, arg.Now)
	var user_id uuid.UUID
	err := row.Scan(&user_id)
	return user_id, err
}

const getOpenOTPForUpdate = `-- name: GetOpenOTPForUpdate :one
SELECT id, phone, code_hash, attempts, ip, expires_at, consumed_at, created_at, updated_at FROM otp_challenges
WHERE phone = $1 AND consumed_at IS NULL AND expires_at > $2
ORDER BY created_at DESC
LIMIT 1
FOR UPDATE
`

type GetOpenOTPForUpdateParams struct {
	Phone string
	Now   time.Time
}

// The latest unused, unexpired code for a number. Older codes stop counting once a new one is sent.
func (q *Queries) GetOpenOTPForUpdate(ctx context.Context, arg GetOpenOTPForUpdateParams) (OtpChallenge, error) {
	row := q.db.QueryRow(ctx, getOpenOTPForUpdate, arg.Phone, arg.Now)
	var i OtpChallenge
	err := row.Scan(
		&i.ID,
		&i.Phone,
		&i.CodeHash,
		&i.Attempts,
		&i.Ip,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSessionForUpdate = `-- name: GetSessionForUpdate :one
SELECT id, user_id, refresh_hash, previous_refresh_hash, rotated_at, device_name, last_used_at, expires_at, revoked_at, revoked_reason, created_at, updated_at FROM sessions WHERE id = $1 FOR UPDATE
`

func (q *Queries) GetSessionForUpdate(ctx context.Context, id uuid.UUID) (Session, error) {
	row := q.db.QueryRow(ctx, getSessionForUpdate, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RefreshHash,
		&i.PreviousRefreshHash,
		&i.RotatedAt,
		&i.DeviceName,
		&i.LastUsedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.RevokedReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const lastOTPSentAt = `-- name: LastOTPSentAt :one
SELECT created_at FROM otp_challenges WHERE phone = $1 ORDER BY created_at DESC LIMIT 1
`

func (q *Queries) LastOTPSentAt(ctx context.Context, phone string) (time.Time, error) {
	row := q.db.QueryRow(ctx, lastOTPSentAt, phone)
	var created_at time.Time
	err := row.Scan(&created_at)
	return created_at, err
}

const lockPhone = `-- name: LockPhone :exec

SELECT pg_advisory_xact_lock(hashtextextended($1::text, 0))
`

// Codes and refresh tokens are stored as hashes. Times come from the API's clock so the rules
// can be tested without waiting.
// Serializes code requests for one number inside a transaction, so rate limits hold under load.
func (q *Queries) LockPhone(ctx context.Context, phone string) error {
	_, err := q.db.Exec(ctx, lockPhone, phone)
	return err
}

const oTPsForIPSince = `-- name: OTPsForIPSince :one
SELECT count(*)::int AS sent, coalesce(min(created_at), $1::timestamptz)::timestamptz AS oldest
FROM otp_challenges
WHERE ip = $2 AND created_at > $1::timestamptz
`

type OTPsForIPSinceParams struct {
	Since time.Time
	Ip    *netip.Addr
}

type OTPsForIPSinceRow struct {
	Sent   int32
	Oldest time.Time
}

func (q *Queries) OTPsForIPSince(ctx context.Context, arg OTPsForIPSinceParams) (OTPsForIPSinceRow, error) {
	row := q.db.QueryRow(ctx, oTPsForIPSince, arg.Since, arg.Ip)
	var i OTPsForIPSinceRow
	err := row.Scan(&i.Sent, &i.Oldest)
	return i, err
}

const oTPsForPhoneSince = `-- name: OTPsForPhoneSince :one
SELECT count(*)::int AS sent, coalesce(min(created_at), $1::timestamptz)::timestamptz AS oldest
FROM otp_challenges
WHERE phone = $2 AND created_at > $1::timestamptz
`

type OTPsForPhoneSinceParams struct {
	Since time.Time
	Phone string
}

type OTPsForPhoneSinceRow struct {
	Sent   int32
	Oldest time.Time
}

// How many codes went to a number in the window, and when the oldest of them was sent.
func (q *Queries) OTPsForPhoneSince(ctx context.Context, arg OTPsForPhoneSinceParams) (OTPsForPhoneSinceRow, error) {
	row := q.db.QueryRow(ctx, oTPsForPhoneSince, arg.Since, arg.Phone)
	var i OTPsForPhoneSinceRow
	err := row.Scan(&i.Sent, &i.Oldest)
	return i, err
}

const recordOTPAttempt = `-- name: RecordOTPAttempt :exec
UPDATE otp_challenges SET attempts = attempts + 1 WHERE id = $1
`

func (q *Queries) RecordOTPAttempt(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, recordOTPAttempt, id)
	return err
}

const reissueSession = `-- name: ReissueSession :exec
UPDATE sessions
SET refresh_hash = $1,
    last_used_at = $2,
    expires_at   = $3
WHERE id = $4
`

type ReissueSessionParams struct {
	RefreshHash []byte
	Now         time.Time
	ExpiresAt   time.Time
	ID          uuid.UUID
}

// A retry inside the grace period: replace the token the client never received, and keep the
// previous hash and rotation time so the grace period cannot be stretched.
func (q *Queries) ReissueSession(ctx context.Context, arg ReissueSessionParams) error {
	_, err := q.db.Exec(ctx, reissueSession,
		arg.RefreshHash,
		arg.Now,
		arg.ExpiresAt,
		arg.ID,
	)
	return err
}

const revokeSession = `-- name: RevokeSession :exec
UPDATE sessions SET revoked_at = $1::timestamptz, revoked_reason = $2::text
WHERE id = $3 AND revoked_at IS NULL
`

type RevokeSessionParams struct {
	Now    time.Time
	Reason string
	ID     uuid.UUID
}

func (q *Queries) RevokeSession(ctx context.Context, arg RevokeSessionParams) error {
	_, err := q.db.Exec(ctx, revokeSession, arg.Now, arg.Reason, arg.ID)
	return err
}

const rotateSession = `-- name: RotateSession :exec
UPDATE sessions
SET previous_refresh_hash = refresh_hash,
    refresh_hash          = $1,
    rotated_at            = $2,
    last_used_at          = $2,
    expires_at            = $3
WHERE id = $4
`

type RotateSessionParams struct {
	RefreshHash []byte
	Now         time.Time
	ExpiresAt   time.Time
	ID          uuid.UUID
}

func (q *Queries) RotateSession(ctx context.Context, arg RotateSessionParams) error {
	_, err := q.db.Exec(ctx, rotateSession,
		arg.RefreshHash,
		arg.Now,
		arg.ExpiresAt,
		arg.ID,
	)
	return err
}
