// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: bookings.sql

package queries

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const deleteBookingExtras = `-- name: DeleteBookingExtras :exec
DELETE FROM booking_extras WHERE booking_id = $1 AND account_id = $2
`

type DeleteBookingExtrasParams struct {
	BookingID uuid.UUID
	AccountID uuid.UUID
}

func (q *Queries) DeleteBookingExtras(ctx context.Context, arg DeleteBookingExtrasParams) error {
	_, err := q.db.Exec(ctx, deleteBookingExtras, arg.BookingID, arg.AccountID)
	return err
}

const deleteBookingLines = `-- name: DeleteBookingLines :exec
DELETE FROM booking_lines WHERE booking_id = $1 AND account_id = $2
`

type DeleteBookingLinesParams struct {
	BookingID uuid.UUID
	AccountID uuid.UUID
}

func (q *Queries) DeleteBookingLines(ctx context.Context, arg DeleteBookingLinesParams) error {
	_, err := q.db.Exec(ctx, deleteBookingLines, arg.BookingID, arg.AccountID)
	return err
}

const findGuest = `-- name: FindGuest :one


SELECT id FROM guests
WHERE account_id = $1
  AND (($2::text IS NOT NULL AND phone = $2::text)
    OR ($3::text IS NOT NULL AND lower(email) = lower($3::text)))
ORDER BY created_at
LIMIT 1
`

type FindGuestParams struct {
	AccountID uuid.UUID
	Phone     *string
	Email     *string
}

// Guests, bookings and what hangs off them. Child rows load for a page of bookings at once.
// Guests -----------------------------------------------------------------------------------
func (q *Queries) FindGuest(ctx context.Context, arg FindGuestParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, findGuest, arg.AccountID, arg.Phone, arg.Email)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const getBooking = `-- name: GetBooking :one
SELECT b.id, b.account_id, b.property_id, b.unit_id, b.ref, b.source, b.status, b.guest_id, b.adults, b.children, b.check_in, b.check_out, b.currency, b.total, b.guest_note, b.owner_note, b.request_expires_at, b.hold_expires_at, b.payment_due_at, b.cancel_reason, b.cancelled_at, b.external_uid, b.feed_id, b.promo_id, b.created_by, b.version, b.created_at, b.updated_at, g.name AS guest_name, g.phone AS guest_phone, g.email AS guest_email,
       g.country AS guest_country
FROM bookings b
JOIN guests g ON g.id = b.guest_id
WHERE b.id = $1 AND b.account_id = $2
`

type GetBookingParams struct {
	ID        uuid.UUID
	AccountID uuid.UUID
}

type GetBookingRow struct {
	Booking      Booking
	GuestName    string
	GuestPhone   *string
	GuestEmail   *string
	GuestCountry *string
}

func (q *Queries) GetBooking(ctx context.Context, arg GetBookingParams) (GetBookingRow, error) {
	row := q.db.QueryRow(ctx, getBooking, arg.ID, arg.AccountID)
	var i GetBookingRow
	err := row.Scan(
		&i.Booking.ID,
		&i.Booking.AccountID,
		&i.Booking.PropertyID,
		&i.Booking.UnitID,
		&i.Booking.Ref,
		&i.Booking.Source,
		&i.Booking.Status,
		&i.Booking.GuestID,
		&i.Booking.Adults,
		&i.Booking.Children,
		&i.Booking.CheckIn,
		&i.Booking.CheckOut,
		&i.Booking.Currency,
		&i.Booking.Total,
		&i.Booking.GuestNote,
		&i.Booking.OwnerNote,
		&i.Booking.RequestExpiresAt,
		&i.Booking.HoldExpiresAt,
		&i.Booking.PaymentDueAt,
		&i.Booking.CancelReason,
		&i.Booking.CancelledAt,
		&i.Booking.ExternalUid,
		&i.Booking.FeedID,
		&i.Booking.PromoID,
		&i.Booking.CreatedBy,
		&i.Booking.Version,
		&i.Booking.CreatedAt,
		&i.Booking.UpdatedAt,
		&i.GuestName,
		&i.GuestPhone,
		&i.GuestEmail,
		&i.GuestCountry,
	)
	return i, err
}

const getBookingForUpdate = `-- name: GetBookingForUpdate :one
SELECT b.id, b.account_id, b.property_id, b.unit_id, b.ref, b.source, b.status, b.guest_id, b.adults, b.children, b.check_in, b.check_out, b.currency, b.total, b.guest_note, b.owner_note, b.request_expires_at, b.hold_expires_at, b.payment_due_at, b.cancel_reason, b.cancelled_at, b.external_uid, b.feed_id, b.promo_id, b.created_by, b.version, b.created_at, b.updated_at, g.name AS guest_name, g.phone AS guest_phone, g.email AS guest_email,
       g.country AS guest_country
FROM bookings b
JOIN guests g ON g.id = b.guest_id
WHERE b.id = $1 AND b.account_id = $2
FOR UPDATE OF b
`

type GetBookingForUpdateParams struct {
	ID        uuid.UUID
	AccountID uuid.UUID
}

type GetBookingForUpdateRow struct {
	Booking      Booking
	GuestName    string
	GuestPhone   *string
	GuestEmail   *string
	GuestCountry *string
}

func (q *Queries) GetBookingForUpdate(ctx context.Context, arg GetBookingForUpdateParams) (GetBookingForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getBookingForUpdate, arg.ID, arg.AccountID)
	var i GetBookingForUpdateRow
	err := row.Scan(
		&i.Booking.ID,
		&i.Booking.AccountID,
		&i.Booking.PropertyID,
		&i.Booking.UnitID,
		&i.Booking.Ref,
		&i.Booking.Source,
		&i.Booking.Status,
		&i.Booking.GuestID,
		&i.Booking.Adults,
		&i.Booking.Children,
		&i.Booking.CheckIn,
		&i.Booking.CheckOut,
		&i.Booking.Currency,
		&i.Booking.Total,
		&i.Booking.GuestNote,
		&i.Booking.OwnerNote,
		&i.Booking.RequestExpiresAt,
		&i.Booking.HoldExpiresAt,
		&i.Booking.PaymentDueAt,
		&i.Booking.CancelReason,
		&i.Booking.CancelledAt,
		&i.Booking.ExternalUid,
		&i.Booking.FeedID,
		&i.Booking.PromoID,
		&i.Booking.CreatedBy,
		&i.Booking.Version,
		&i.Booking.CreatedAt,
		&i.Booking.UpdatedAt,
		&i.GuestName,
		&i.GuestPhone,
		&i.GuestEmail,
		&i.GuestCountry,
	)
	return i, err
}

const getSlipForUpdate = `-- name: GetSlipForUpdate :one
SELECT id, booking_id, amount, status
FROM payment_slips
WHERE id = $1 AND account_id = $2
FOR UPDATE
`

type GetSlipForUpdateParams struct {
	ID        uuid.UUID
	AccountID uuid.UUID
}

type GetSlipForUpdateRow struct {
	ID        uuid.UUID
	BookingID uuid.UUID
	Amount    int64
	Status    string
}

func (q *Queries) GetSlipForUpdate(ctx context.Context, arg GetSlipForUpdateParams) (GetSlipForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getSlipForUpdate, arg.ID, arg.AccountID)
	var i GetSlipForUpdateRow
	err := row.Scan(
		&i.ID,
		&i.BookingID,
		&i.Amount,
		&i.Status,
	)
	return i, err
}

const insertBooking = `-- name: InsertBooking :exec
INSERT INTO bookings (id, account_id, property_id, unit_id, ref, source, status, guest_id, adults,
                      children, check_in, check_out, currency, total, guest_note, owner_note,
                      request_expires_at, payment_due_at, promo_id, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9,
        $10, $11, $12, $13, $14, $15, $16,
        $17, $18, $19,
        $20)
`

type InsertBookingParams struct {
	ID               uuid.UUID
	AccountID        uuid.UUID
	PropertyID       uuid.UUID
	UnitID           uuid.UUID
	Ref              string
	Source           string
	Status           string
	GuestID          uuid.UUID
	Adults           int16
	Children         int16
	CheckIn          time.Time
	CheckOut         time.Time
	Currency         string
	Total            int64
	GuestNote        string
	OwnerNote        string
	RequestExpiresAt *time.Time
	PaymentDueAt     *time.Time
	PromoID          *uuid.UUID
	CreatedBy        *uuid.UUID
}

func (q *Queries) InsertBooking(ctx context.Context, arg InsertBookingParams) error {
	_, err := q.db.Exec(ctx, insertBooking,
		arg.ID,
		arg.AccountID,
		arg.PropertyID,
		arg.UnitID,
		arg.Ref,
		arg.Source,
		arg.Status,
		arg.GuestID,
		arg.Adults,
		arg.Children,
		arg.CheckIn,
		arg.CheckOut,
		arg.Currency,
		arg.Total,
		arg.GuestNote,
		arg.OwnerNote,
		arg.RequestExpiresAt,
		arg.PaymentDueAt,
		arg.PromoID,
		arg.CreatedBy,
	)
	return err
}

const insertBookingEvent = `-- name: InsertBookingEvent :exec
INSERT INTO booking_events (id, account_id, booking_id, from_status, to_status, actor_user_id, reason)
VALUES ($1, $2, $3, $4, $5,
        $6, $7)
`

type InsertBookingEventParams struct {
	ID          uuid.UUID
	AccountID   uuid.UUID
	BookingID   uuid.UUID
	FromStatus  *string
	ToStatus    string
	ActorUserID *uuid.UUID
	Reason      string
}

func (q *Queries) InsertBookingEvent(ctx context.Context, arg InsertBookingEventParams) error {
	_, err := q.db.Exec(ctx, insertBookingEvent,
		arg.ID,
		arg.AccountID,
		arg.BookingID,
		arg.FromStatus,
		arg.ToStatus,
		arg.ActorUserID,
		arg.Reason,
	)
	return err
}

const insertBookingExtra = `-- name: InsertBookingExtra :exec
INSERT INTO booking_extras (account_id, booking_id, extra_id, name, amount)
VALUES ($1, $2, $3, $4, $5)
`

type InsertBookingExtraParams struct {
	AccountID uuid.UUID
	BookingID uuid.UUID
	ExtraID   uuid.UUID
	Name      string
	Amount    int64
}

func (q *Queries) InsertBookingExtra(ctx context.Context, arg InsertBookingExtraParams) error {
	_, err := q.db.Exec(ctx, insertBookingExtra,
		arg.AccountID,
		arg.BookingID,
		arg.ExtraID,
		arg.Name,
		arg.Amount,
	)
	return err
}

const insertBookingLine = `-- name: InsertBookingLine :exec
INSERT INTO booking_lines (account_id, booking_id, position, label, amount, kind)
VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertBookingLineParams struct {
	AccountID uuid.UUID
	BookingID uuid.UUID
	Position  int16
	Label     string
	Amount    int64
	Kind      *string
}

func (q *Queries) InsertBookingLine(ctx context.Context, arg InsertBookingLineParams) error {
	_, err := q.db.Exec(ctx, insertBookingLine,
		arg.AccountID,
		arg.BookingID,
		arg.Position,
		arg.Label,
		arg.Amount,
		arg.Kind,
	)
	return err
}

const insertGuest = `-- name: InsertGuest :exec
INSERT INTO guests (id, account_id, name, phone, email, country)
VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertGuestParams struct {
	ID        uuid.UUID
	AccountID uuid.UUID
	Name      string
	Phone     *string
	Email     *string
	Country   *string
}

func (q *Queries) InsertGuest(ctx context.Context, arg InsertGuestParams) error {
	_, err := q.db.Exec(ctx, insertGuest,
		arg.ID,
		arg.AccountID,
		arg.Name,
		arg.Phone,
		arg.Email,
		arg.Country,
	)
	return err
}

const insertPayment = `-- name: InsertPayment :exec
INSERT INTO payments (id, account_id, booking_id, kind, method, amount, currency, note,
                      received_at, recorded_by, slip_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9,
        $10, $11)
`

type InsertPaymentParams struct {
	ID         uuid.UUID
	AccountID  uuid.UUID
	BookingID  uuid.UUID
	Kind       string
	Method     string
	Amount     int64
	Currency   string
	Note       string
	ReceivedAt time.Time
	RecordedBy *uuid.UUID
	SlipID     *uuid.UUID
}

func (q *Queries) InsertPayment(ctx context.Context, arg InsertPaymentParams) error {
	_, err := q.db.Exec(ctx, insertPayment,
		arg.ID,
		arg.AccountID,
		arg.BookingID,
		arg.Kind,
		arg.Method,
		arg.Amount,
		arg.Currency,
		arg.Note,
		arg.ReceivedAt,
		arg.RecordedBy,
		arg.SlipID,
	)
	return err
}

const insertSlip = `-- name: InsertSlip :exec
INSERT INTO payment_slips (id, account_id, booking_id, file_key, amount, uploaded_at)
VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertSlipParams struct {
	ID         uuid.UUID
	AccountID  uuid.UUID
	BookingID  uuid.UUID
	FileKey    string
	Amount     int64
	UploadedAt time.Time
}

func (q *Queries) InsertSlip(ctx context.Context, arg InsertSlipParams) error {
	_, err := q.db.Exec(ctx, insertSlip,
		arg.ID,
		arg.AccountID,
		arg.BookingID,
		arg.FileKey,
		arg.Amount,
		arg.UploadedAt,
	)
	return err
}

const listBookingEvents = `-- name: ListBookingEvents :many
SELECT from_status, to_status, actor_user_id, reason, created_at
FROM booking_events
WHERE booking_id = $1 AND account_id = $2
ORDER BY created_at, id
`

type ListBookingEventsParams struct {
	BookingID uuid.UUID
	AccountID uuid.UUID
}

type ListBookingEventsRow struct {
	FromStatus  *string
	ToStatus    string
	ActorUserID *uuid.UUID
	Reason      string
	CreatedAt   time.Time
}

func (q *Queries) ListBookingEvents(ctx context.Context, arg ListBookingEventsParams) ([]ListBookingEventsRow, error) {
	rows, err := q.db.Query(ctx, listBookingEvents, arg.BookingID, arg.AccountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBookingEventsRow{}
	for rows.Next() {
		var i ListBookingEventsRow
		if err := rows.Scan(
			&i.FromStatus,
			&i.ToStatus,
			&i.ActorUserID,
			&i.Reason,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBookingExtras = `-- name: ListBookingExtras :many
SELECT booking_id, extra_id, name, amount
FROM booking_extras
WHERE account_id = $1 AND booking_id = ANY ($2::uuid[])
ORDER BY booking_id, name
`

type ListBookingExtrasParams struct {
	AccountID  uuid.UUID
	BookingIds []uuid.UUID
}

type ListBookingExtrasRow struct {
	BookingID uuid.UUID
	ExtraID   uuid.UUID
	Name      string
	Amount    int64
}

func (q *Queries) ListBookingExtras(ctx context.Context, arg ListBookingExtrasParams) ([]ListBookingExtrasRow, error) {
	rows, err := q.db.Query(ctx, listBookingExtras, arg.AccountID, arg.BookingIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBookingExtrasRow{}
	for rows.Next() {
		var i ListBookingExtrasRow
		if err := rows.Scan(
			&i.BookingID,
			&i.ExtraID,
			&i.Name,
			&i.Amount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBookingLines = `-- name: ListBookingLines :many
SELECT booking_id, label, amount, kind
FROM booking_lines
WHERE account_id = $1 AND booking_id = ANY ($2::uuid[])
ORDER BY booking_id, position
`

type ListBookingLinesParams struct {
	AccountID  uuid.UUID
	BookingIds []uuid.UUID
}

type ListBookingLinesRow struct {
	BookingID uuid.UUID
	Label     string
	Amount    int64
	Kind      *string
}

func (q *Queries) ListBookingLines(ctx context.Context, arg ListBookingLinesParams) ([]ListBookingLinesRow, error) {
	rows, err := q.db.Query(ctx, listBookingLines, arg.AccountID, arg.BookingIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBookingLinesRow{}
	for rows.Next() {
		var i ListBookingLinesRow
		if err := rows.Scan(
			&i.BookingID,
			&i.Label,
			&i.Amount,
			&i.Kind,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBookings = `-- name: ListBookings :many
SELECT b.id, b.account_id, b.property_id, b.unit_id, b.ref, b.source, b.status, b.guest_id, b.adults, b.children, b.check_in, b.check_out, b.currency, b.total, b.guest_note, b.owner_note, b.request_expires_at, b.hold_expires_at, b.payment_due_at, b.cancel_reason, b.cancelled_at, b.external_uid, b.feed_id, b.promo_id, b.created_by, b.version, b.created_at, b.updated_at, g.name AS guest_name, g.phone AS guest_phone, g.email AS guest_email,
       g.country AS guest_country
FROM bookings b
JOIN guests g ON g.id = b.guest_id
WHERE b.account_id = $1
  AND ($2::uuid[] IS NULL OR b.property_id = ANY ($2::uuid[]))
  AND ($3::date IS NULL OR b.check_out > $3::date)
  AND ($4::date IS NULL OR b.check_in < $4::date)
  AND ($5::date IS NULL
    OR (b.check_in, b.id) > ($5::date, $6::uuid))
ORDER BY b.check_in, b.id
LIMIT $7
`

type ListBookingsParams struct {
	AccountID    uuid.UUID
	PropertyIds  []uuid.UUID
	RangeFrom    *time.Time
	RangeTo      *time.Time
	AfterCheckIn *time.Time
	AfterID      *uuid.UUID
	RowLimit     int32
}

type ListBookingsRow struct {
	Booking      Booking
	GuestName    string
	GuestPhone   *string
	GuestEmail   *string
	GuestCountry *string
}

// Stays that overlap [from, to), ordered by arrival. The cursor is the last row's arrival and id.
func (q *Queries) ListBookings(ctx context.Context, arg ListBookingsParams) ([]ListBookingsRow, error) {
	rows, err := q.db.Query(ctx, listBookings,
		arg.AccountID,
		arg.PropertyIds,
		arg.RangeFrom,
		arg.RangeTo,
		arg.AfterCheckIn,
		arg.AfterID,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBookingsRow{}
	for rows.Next() {
		var i ListBookingsRow
		if err := rows.Scan(
			&i.Booking.ID,
			&i.Booking.AccountID,
			&i.Booking.PropertyID,
			&i.Booking.UnitID,
			&i.Booking.Ref,
			&i.Booking.Source,
			&i.Booking.Status,
			&i.Booking.GuestID,
			&i.Booking.Adults,
			&i.Booking.Children,
			&i.Booking.CheckIn,
			&i.Booking.CheckOut,
			&i.Booking.Currency,
			&i.Booking.Total,
			&i.Booking.GuestNote,
			&i.Booking.OwnerNote,
			&i.Booking.RequestExpiresAt,
			&i.Booking.HoldExpiresAt,
			&i.Booking.PaymentDueAt,
			&i.Booking.CancelReason,
			&i.Booking.CancelledAt,
			&i.Booking.ExternalUid,
			&i.Booking.FeedID,
			&i.Booking.PromoID,
			&i.Booking.CreatedBy,
			&i.Booking.Version,
			&i.Booking.CreatedAt,
			&i.Booking.UpdatedAt,
			&i.GuestName,
			&i.GuestPhone,
			&i.GuestEmail,
			&i.GuestCountry,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPayments = `-- name: ListPayments :many

SELECT id, booking_id, kind, method, amount, note, received_at, slip_id
FROM payments
WHERE account_id = $1 AND booking_id = ANY ($2::uuid[])
ORDER BY booking_id, received_at, id
`

type ListPaymentsParams struct {
	AccountID  uuid.UUID
	BookingIds []uuid.UUID
}

type ListPaymentsRow struct {
	ID         uuid.UUID
	BookingID  uuid.UUID
	Kind       string
	Method     string
	Amount     int64
	Note       string
	ReceivedAt time.Time
	SlipID     *uuid.UUID
}

// Payments and slips -----------------------------------------------------------------------
func (q *Queries) ListPayments(ctx context.Context, arg ListPaymentsParams) ([]ListPaymentsRow, error) {
	rows, err := q.db.Query(ctx, listPayments, arg.AccountID, arg.BookingIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPaymentsRow{}
	for rows.Next() {
		var i ListPaymentsRow
		if err := rows.Scan(
			&i.ID,
			&i.BookingID,
			&i.Kind,
			&i.Method,
			&i.Amount,
			&i.Note,
			&i.ReceivedAt,
			&i.SlipID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSlips = `-- name: ListSlips :many
SELECT id, booking_id, file_key, amount, status, uploaded_at
FROM payment_slips
WHERE account_id = $1 AND booking_id = ANY ($2::uuid[])
ORDER BY booking_id, uploaded_at, id
`

type ListSlipsParams struct {
	AccountID  uuid.UUID
	BookingIds []uuid.UUID
}

type ListSlipsRow struct {
	ID         uuid.UUID
	BookingID  uuid.UUID
	FileKey    string
	Amount     int64
	Status     string
	UploadedAt time.Time
}

func (q *Queries) ListSlips(ctx context.Context, arg ListSlipsParams) ([]ListSlipsRow, error) {
	rows, err := q.db.Query(ctx, listSlips, arg.AccountID, arg.BookingIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSlipsRow{}
	for rows.Next() {
		var i ListSlipsRow
		if err := rows.Scan(
			&i.ID,
			&i.BookingID,
			&i.FileKey,
			&i.Amount,
			&i.Status,
			&i.UploadedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nextBookingNumber = `-- name: NextBookingNumber :one

UPDATE accounts SET booking_seq = booking_seq + 1 WHERE id = $1 RETURNING booking_seq
`

// Bookings ---------------------------------------------------------------------------------
func (q *Queries) NextBookingNumber(ctx context.Context, accountID uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, nextBookingNumber, accountID)
	var booking_seq int32
	err := row.Scan(&booking_seq)
	return booking_seq, err
}

const reviewSlip = `-- name: ReviewSlip :exec
UPDATE payment_slips SET status = $1, reviewed_by = $2,
                         reviewed_at = $3
WHERE id = $4 AND account_id = $5
`

type ReviewSlipParams struct {
	Status     string
	ReviewedBy *uuid.UUID
	ReviewedAt *time.Time
	ID         uuid.UUID
	AccountID  uuid.UUID
}

func (q *Queries) ReviewSlip(ctx context.Context, arg ReviewSlipParams) error {
	_, err := q.db.Exec(ctx, reviewSlip,
		arg.Status,
		arg.ReviewedBy,
		arg.ReviewedAt,
		arg.ID,
		arg.AccountID,
	)
	return err
}

const updateBooking = `-- name: UpdateBooking :exec
UPDATE bookings SET unit_id = $1, source = $2, status = $3, adults = $4,
                    children = $5, check_in = $6, check_out = $7,
                    total = $8, guest_note = $9, owner_note = $10,
                    request_expires_at = $11,
                    payment_due_at = $12,
                    cancel_reason = $13,
                    cancelled_at = $14,
                    version = version + 1
WHERE id = $15 AND account_id = $16
`

type UpdateBookingParams struct {
	UnitID           uuid.UUID
	Source           string
	Status           string
	Adults           int16
	Children         int16
	CheckIn          time.Time
	CheckOut         time.Time
	Total            int64
	GuestNote        string
	OwnerNote        string
	RequestExpiresAt *time.Time
	PaymentDueAt     *time.Time
	CancelReason     *string
	CancelledAt      *time.Time
	ID               uuid.UUID
	AccountID        uuid.UUID
}

func (q *Queries) UpdateBooking(ctx context.Context, arg UpdateBookingParams) error {
	_, err := q.db.Exec(ctx, updateBooking,
		arg.UnitID,
		arg.Source,
		arg.Status,
		arg.Adults,
		arg.Children,
		arg.CheckIn,
		arg.CheckOut,
		arg.Total,
		arg.GuestNote,
		arg.OwnerNote,
		arg.RequestExpiresAt,
		arg.PaymentDueAt,
		arg.CancelReason,
		arg.CancelledAt,
		arg.ID,
		arg.AccountID,
	)
	return err
}

const updateGuest = `-- name: UpdateGuest :exec
UPDATE guests SET name = $1, phone = $2, email = $3,
                  country = $4
WHERE id = $5 AND account_id = $6
`

type UpdateGuestParams struct {
	Name      string
	Phone     *string
	Email     *string
	Country   *string
	ID        uuid.UUID
	AccountID uuid.UUID
}

func (q *Queries) UpdateGuest(ctx context.Context, arg UpdateGuestParams) error {
	_, err := q.db.Exec(ctx, updateGuest,
		arg.Name,
		arg.Phone,
		arg.Email,
		arg.Country,
		arg.ID,
		arg.AccountID,
	)
	return err
}
