// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: calendar.sql

package queries

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const deleteBlock = `-- name: DeleteBlock :exec
DELETE FROM blocks WHERE id = $1 AND account_id = $2
`

type DeleteBlockParams struct {
	ID        uuid.UUID
	AccountID uuid.UUID
}

func (q *Queries) DeleteBlock(ctx context.Context, arg DeleteBlockParams) error {
	_, err := q.db.Exec(ctx, deleteBlock, arg.ID, arg.AccountID)
	return err
}

const deleteBookingNights = `-- name: DeleteBookingNights :exec
DELETE FROM unit_nights WHERE booking_id = $1 AND account_id = $2
`

type DeleteBookingNightsParams struct {
	BookingID *uuid.UUID
	AccountID uuid.UUID
}

func (q *Queries) DeleteBookingNights(ctx context.Context, arg DeleteBookingNightsParams) error {
	_, err := q.db.Exec(ctx, deleteBookingNights, arg.BookingID, arg.AccountID)
	return err
}

const deleteExpiredHolds = `-- name: DeleteExpiredHolds :execrows
DELETE FROM unit_nights WHERE hold_expires_at < $1::timestamptz
`

func (q *Queries) DeleteExpiredHolds(ctx context.Context, now time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredHolds, now)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteRateOverrides = `-- name: DeleteRateOverrides :exec

DELETE FROM rate_overrides
WHERE account_id = $1 AND property_id = $2
  AND unit_id = ANY ($3::uuid[]) AND night >= $4::date AND night < $5::date
`

type DeleteRateOverridesParams struct {
	AccountID  uuid.UUID
	PropertyID uuid.UUID
	UnitIds    []uuid.UUID
	RangeFrom  time.Time
	RangeTo    time.Time
}

// Rate overrides ---------------------------------------------------------------------------
func (q *Queries) DeleteRateOverrides(ctx context.Context, arg DeleteRateOverridesParams) error {
	_, err := q.db.Exec(ctx, deleteRateOverrides,
		arg.AccountID,
		arg.PropertyID,
		arg.UnitIds,
		arg.RangeFrom,
		arg.RangeTo,
	)
	return err
}

const firstHeldNight = `-- name: FirstHeldNight :one
SELECT un.night, un.unit_id, un.booking_id, un.block_id,
       b.ref AS booking_ref, b.check_in AS booking_check_in, b.check_out AS booking_check_out,
       g.name AS guest_name, bl.starts_on AS block_starts_on, bl.ends_on AS block_ends_on
FROM unit_nights un
LEFT JOIN bookings b ON b.id = un.booking_id
LEFT JOIN guests g ON g.id = b.guest_id
LEFT JOIN blocks bl ON bl.id = un.block_id
WHERE un.account_id = $1
  AND un.unit_id = ANY ($2::uuid[])
  AND un.night >= $3::date AND un.night < $4::date
ORDER BY un.night
LIMIT 1
`

type FirstHeldNightParams struct {
	AccountID uuid.UUID
	UnitIds   []uuid.UUID
	CheckIn   time.Time
	CheckOut  time.Time
}

type FirstHeldNightRow struct {
	Night           time.Time
	UnitID          uuid.UUID
	BookingID       *uuid.UUID
	BlockID         *uuid.UUID
	BookingRef      *string
	BookingCheckIn  *time.Time
	BookingCheckOut *time.Time
	GuestName       *string
	BlockStartsOn   *time.Time
	BlockEndsOn     *time.Time
}

// The first night already held on these units in [check_in, check_out), with what holds it.
func (q *Queries) FirstHeldNight(ctx context.Context, arg FirstHeldNightParams) (FirstHeldNightRow, error) {
	row := q.db.QueryRow(ctx, firstHeldNight,
		arg.AccountID,
		arg.UnitIds,
		arg.CheckIn,
		arg.CheckOut,
	)
	var i FirstHeldNightRow
	err := row.Scan(
		&i.Night,
		&i.UnitID,
		&i.BookingID,
		&i.BlockID,
		&i.BookingRef,
		&i.BookingCheckIn,
		&i.BookingCheckOut,
		&i.GuestName,
		&i.BlockStartsOn,
		&i.BlockEndsOn,
	)
	return i, err
}

const getBlock = `-- name: GetBlock :one
SELECT id, property_id, starts_on, ends_on, reason, note
FROM blocks
WHERE id = $1 AND account_id = $2
`

type GetBlockParams struct {
	ID        uuid.UUID
	AccountID uuid.UUID
}

type GetBlockRow struct {
	ID         uuid.UUID
	PropertyID uuid.UUID
	StartsOn   time.Time
	EndsOn     time.Time
	Reason     string
	Note       string
}

func (q *Queries) GetBlock(ctx context.Context, arg GetBlockParams) (GetBlockRow, error) {
	row := q.db.QueryRow(ctx, getBlock, arg.ID, arg.AccountID)
	var i GetBlockRow
	err := row.Scan(
		&i.ID,
		&i.PropertyID,
		&i.StartsOn,
		&i.EndsOn,
		&i.Reason,
		&i.Note,
	)
	return i, err
}

const insertBlock = `-- name: InsertBlock :exec

INSERT INTO blocks (id, account_id, property_id, starts_on, ends_on, reason, note, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type InsertBlockParams struct {
	ID         uuid.UUID
	AccountID  uuid.UUID
	PropertyID uuid.UUID
	StartsOn   time.Time
	EndsOn     time.Time
	Reason     string
	Note       string
	CreatedBy  *uuid.UUID
}

// Blocks -----------------------------------------------------------------------------------
func (q *Queries) InsertBlock(ctx context.Context, arg InsertBlockParams) error {
	_, err := q.db.Exec(ctx, insertBlock,
		arg.ID,
		arg.AccountID,
		arg.PropertyID,
		arg.StartsOn,
		arg.EndsOn,
		arg.Reason,
		arg.Note,
		arg.CreatedBy,
	)
	return err
}

const insertBlockUnit = `-- name: InsertBlockUnit :exec
INSERT INTO block_units (account_id, property_id, block_id, unit_id)
VALUES ($1, $2, $3, $4)
`

type InsertBlockUnitParams struct {
	AccountID  uuid.UUID
	PropertyID uuid.UUID
	BlockID    uuid.UUID
	UnitID     uuid.UUID
}

func (q *Queries) InsertBlockUnit(ctx context.Context, arg InsertBlockUnitParams) error {
	_, err := q.db.Exec(ctx, insertBlockUnit,
		arg.AccountID,
		arg.PropertyID,
		arg.BlockID,
		arg.UnitID,
	)
	return err
}

const insertRateOverrides = `-- name: InsertRateOverrides :exec
INSERT INTO rate_overrides (unit_id, night, account_id, property_id, price, min_nights, closed_to_arrival)
SELECT u.unit_id, n.night::date, $1::uuid, $2::uuid, $3::bigint,
       $4::smallint, $5::boolean
FROM unnest($6::uuid[]) AS u (unit_id)
CROSS JOIN generate_series($7::date, $8::date - 1, interval '1 day') AS n (night)
`

type InsertRateOverridesParams struct {
	AccountID       uuid.UUID
	PropertyID      uuid.UUID
	Price           *int64
	MinNights       *int16
	ClosedToArrival bool
	UnitIds         []uuid.UUID
	RangeFrom       time.Time
	RangeTo         time.Time
}

func (q *Queries) InsertRateOverrides(ctx context.Context, arg InsertRateOverridesParams) error {
	_, err := q.db.Exec(ctx, insertRateOverrides,
		arg.AccountID,
		arg.PropertyID,
		arg.Price,
		arg.MinNights,
		arg.ClosedToArrival,
		arg.UnitIds,
		arg.RangeFrom,
		arg.RangeTo,
	)
	return err
}

const insertUnitNights = `-- name: InsertUnitNights :exec


INSERT INTO unit_nights (unit_id, night, account_id, property_id, booking_id, block_id)
SELECT u.unit_id, n.night::date, $1::uuid, $2::uuid,
       $3::uuid, $4::uuid
FROM unnest($5::uuid[]) AS u (unit_id)
CROSS JOIN generate_series($6::date, $7::date - 1, interval '1 day') AS n (night)
`

type InsertUnitNightsParams struct {
	AccountID  uuid.UUID
	PropertyID uuid.UUID
	BookingID  *uuid.UUID
	BlockID    *uuid.UUID
	UnitIds    []uuid.UUID
	CheckIn    time.Time
	CheckOut   time.Time
}

// The night ledger, blocks and rate overrides.
// Night ledger -----------------------------------------------------------------------------
// Holds every night in [check_in, check_out) on each unit for a booking or a block. A night
// someone else holds fails the primary key.
func (q *Queries) InsertUnitNights(ctx context.Context, arg InsertUnitNightsParams) error {
	_, err := q.db.Exec(ctx, insertUnitNights,
		arg.AccountID,
		arg.PropertyID,
		arg.BookingID,
		arg.BlockID,
		arg.UnitIds,
		arg.CheckIn,
		arg.CheckOut,
	)
	return err
}

const listBlockUnits = `-- name: ListBlockUnits :many
SELECT block_id, unit_id
FROM block_units
WHERE account_id = $1 AND block_id = ANY ($2::uuid[])
`

type ListBlockUnitsParams struct {
	AccountID uuid.UUID
	BlockIds  []uuid.UUID
}

type ListBlockUnitsRow struct {
	BlockID uuid.UUID
	UnitID  uuid.UUID
}

func (q *Queries) ListBlockUnits(ctx context.Context, arg ListBlockUnitsParams) ([]ListBlockUnitsRow, error) {
	rows, err := q.db.Query(ctx, listBlockUnits, arg.AccountID, arg.BlockIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBlockUnitsRow{}
	for rows.Next() {
		var i ListBlockUnitsRow
		if err := rows.Scan(&i.BlockID, &i.UnitID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBlocks = `-- name: ListBlocks :many
SELECT id, property_id, starts_on, ends_on, reason, note
FROM blocks
WHERE account_id = $1 AND property_id = $2
  AND ends_on > $3::date AND starts_on < $4::date
ORDER BY starts_on, id
`

type ListBlocksParams struct {
	AccountID  uuid.UUID
	PropertyID uuid.UUID
	RangeFrom  time.Time
	RangeTo    time.Time
}

type ListBlocksRow struct {
	ID         uuid.UUID
	PropertyID uuid.UUID
	StartsOn   time.Time
	EndsOn     time.Time
	Reason     string
	Note       string
}

func (q *Queries) ListBlocks(ctx context.Context, arg ListBlocksParams) ([]ListBlocksRow, error) {
	rows, err := q.db.Query(ctx, listBlocks,
		arg.AccountID,
		arg.PropertyID,
		arg.RangeFrom,
		arg.RangeTo,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBlocksRow{}
	for rows.Next() {
		var i ListBlocksRow
		if err := rows.Scan(
			&i.ID,
			&i.PropertyID,
			&i.StartsOn,
			&i.EndsOn,
			&i.Reason,
			&i.Note,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRateOverrides = `-- name: ListRateOverrides :many
SELECT unit_id, night, price, min_nights, closed_to_arrival
FROM rate_overrides
WHERE account_id = $1 AND property_id = $2
  AND night >= $3::date AND night < $4::date
ORDER BY unit_id, night
`

type ListRateOverridesParams struct {
	AccountID  uuid.UUID
	PropertyID uuid.UUID
	RangeFrom  time.Time
	RangeTo    time.Time
}

type ListRateOverridesRow struct {
	UnitID          uuid.UUID
	Night           time.Time
	Price           *int64
	MinNights       *int16
	ClosedToArrival bool
}

func (q *Queries) ListRateOverrides(ctx context.Context, arg ListRateOverridesParams) ([]ListRateOverridesRow, error) {
	rows, err := q.db.Query(ctx, listRateOverrides,
		arg.AccountID,
		arg.PropertyID,
		arg.RangeFrom,
		arg.RangeTo,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRateOverridesRow{}
	for rows.Next() {
		var i ListRateOverridesRow
		if err := rows.Scan(
			&i.UnitID,
			&i.Night,
			&i.Price,
			&i.MinNights,
			&i.ClosedToArrival,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
