// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: idempotency.sql

package queries

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const claimIdempotencyKey = `-- name: ClaimIdempotencyKey :execrows

INSERT INTO idempotency_keys (account_id, key, request_hash, expires_at)
VALUES ($1, $2, $3, $4)
ON CONFLICT (account_id, key) DO NOTHING
`

type ClaimIdempotencyKeyParams struct {
	AccountID   uuid.UUID
	Key         string
	RequestHash []byte
	ExpiresAt   time.Time
}

// Idempotency keys. Claiming a key inserts its row inside the request's transaction, so a
// retry that arrives while the first attempt runs waits for it and then sees its reply.
func (q *Queries) ClaimIdempotencyKey(ctx context.Context, arg ClaimIdempotencyKeyParams) (int64, error) {
	result, err := q.db.Exec(ctx, claimIdempotencyKey,
		arg.AccountID,
		arg.Key,
		arg.RequestHash,
		arg.ExpiresAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteExpiredIdempotencyKeys = `-- name: DeleteExpiredIdempotencyKeys :execrows
DELETE FROM idempotency_keys WHERE expires_at < $1::timestamptz
`

func (q *Queries) DeleteExpiredIdempotencyKeys(ctx context.Context, now time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredIdempotencyKeys, now)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteIdempotencyKey = `-- name: DeleteIdempotencyKey :exec
DELETE FROM idempotency_keys WHERE account_id = $1 AND key = $2
`

type DeleteIdempotencyKeyParams struct {
	AccountID uuid.UUID
	Key       string
}

func (q *Queries) DeleteIdempotencyKey(ctx context.Context, arg DeleteIdempotencyKeyParams) error {
	_, err := q.db.Exec(ctx, deleteIdempotencyKey, arg.AccountID, arg.Key)
	return err
}

const getIdempotencyKey = `-- name: GetIdempotencyKey :one
SELECT request_hash, status, response, expires_at
FROM idempotency_keys
WHERE account_id = $1 AND key = $2
FOR UPDATE
`

type GetIdempotencyKeyParams struct {
	AccountID uuid.UUID
	Key       string
}

type GetIdempotencyKeyRow struct {
	RequestHash []byte
	Status      *int16
	Response    []byte
	ExpiresAt   time.Time
}

func (q *Queries) GetIdempotencyKey(ctx context.Context, arg GetIdempotencyKeyParams) (GetIdempotencyKeyRow, error) {
	row := q.db.QueryRow(ctx, getIdempotencyKey, arg.AccountID, arg.Key)
	var i GetIdempotencyKeyRow
	err := row.Scan(
		&i.RequestHash,
		&i.Status,
		&i.Response,
		&i.ExpiresAt,
	)
	return i, err
}

const saveIdempotentResponse = `-- name: SaveIdempotentResponse :exec
UPDATE idempotency_keys SET status = $1, response = $2
WHERE account_id = $3 AND key = $4
`

type SaveIdempotentResponseParams struct {
	Status    *int16
	Response  []byte
	AccountID uuid.UUID
	Key       string
}

func (q *Queries) SaveIdempotentResponse(ctx context.Context, arg SaveIdempotentResponseParams) error {
	_, err := q.db.Exec(ctx, saveIdempotentResponse,
		arg.Status,
		arg.Response,
		arg.AccountID,
		arg.Key,
	)
	return err
}
