// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: jobs.sql

package queries

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const cancelUnpaidBookings = `-- name: CancelUnpaidBookings :many
UPDATE bookings b SET status = 'cancelled', payment_due_at = NULL, cancelled_at = $1::timestamptz,
                      cancel_reason = 'Not paid in time', version = version + 1
WHERE b.status = 'awaiting_payment' AND b.payment_due_at < $1::timestamptz
  AND NOT EXISTS (SELECT 1 FROM payments p WHERE p.booking_id = b.id AND p.kind = 'payment')
RETURNING b.id, b.account_id
`

type CancelUnpaidBookingsRow struct {
	ID        uuid.UUID
	AccountID uuid.UUID
}

// A stay waiting for payment is cancelled once its deadline passes with nothing paid. The
// deadline is only set when the property cancels unpaid stays.
func (q *Queries) CancelUnpaidBookings(ctx context.Context, now time.Time) ([]CancelUnpaidBookingsRow, error) {
	rows, err := q.db.Query(ctx, cancelUnpaidBookings, now)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CancelUnpaidBookingsRow{}
	for rows.Next() {
		var i CancelUnpaidBookingsRow
		if err := rows.Scan(&i.ID, &i.AccountID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const declineExpiredRequests = `-- name: DeclineExpiredRequests :many

UPDATE bookings SET status = 'declined', request_expires_at = NULL, version = version + 1
WHERE status = 'requested' AND request_expires_at < $1::timestamptz
RETURNING id, account_id
`

type DeclineExpiredRequestsRow struct {
	ID        uuid.UUID
	AccountID uuid.UUID
}

// Sweeps the job workers run across every account.
func (q *Queries) DeclineExpiredRequests(ctx context.Context, now time.Time) ([]DeclineExpiredRequestsRow, error) {
	rows, err := q.db.Query(ctx, declineExpiredRequests, now)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DeclineExpiredRequestsRow{}
	for rows.Next() {
		var i DeclineExpiredRequestsRow
		if err := rows.Scan(&i.ID, &i.AccountID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const fileInUse = `-- name: FileInUse :one
SELECT EXISTS (SELECT 1 FROM property_photos WHERE key = $1::text)
    OR EXISTS (SELECT 1 FROM properties WHERE logo_key = $1::text)
    OR EXISTS (SELECT 1 FROM payment_slips WHERE file_key = $1::text) AS in_use
`

func (q *Queries) FileInUse(ctx context.Context, key string) (*bool, error) {
	row := q.db.QueryRow(ctx, fileInUse, key)
	var in_use *bool
	err := row.Scan(&in_use)
	return in_use, err
}
