// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package queries

import (
	"net/netip"
	"time"

	"github.com/google/uuid"
)

type Account struct {
	ID                   uuid.UUID
	Name                 string
	Status               string
	TrialStartedAt       time.Time
	FirstDirectBookingAt *time.Time
	CreatedAt            time.Time
	UpdatedAt            time.Time
}

type Membership struct {
	ID        uuid.UUID
	AccountID uuid.UUID
	UserID    uuid.UUID
	Role      string
	Status    string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type OtpChallenge struct {
	ID         uuid.UUID
	Phone      string
	CodeHash   []byte
	Attempts   int16
	Ip         *netip.Addr
	ExpiresAt  time.Time
	ConsumedAt *time.Time
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

type Session struct {
	ID                  uuid.UUID
	UserID              uuid.UUID
	RefreshHash         []byte
	PreviousRefreshHash []byte
	RotatedAt           time.Time
	DeviceName          string
	LastUsedAt          time.Time
	ExpiresAt           time.Time
	RevokedAt           *time.Time
	RevokedReason       *string
	CreatedAt           time.Time
	UpdatedAt           time.Time
}

type User struct {
	ID        uuid.UUID
	Phone     string
	Name      string
	Email     *string
	Language  string
	PhotoKey  *string
	CreatedAt time.Time
	UpdatedAt time.Time
}
