// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: properties.sql

package queries

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createProperty = `-- name: CreateProperty :one
INSERT INTO properties (id, account_id, slug, name, booking_type, location, currency, base_rate_minor)
VALUES ($1, $2, $3, $4, $5, nullif($6::text, ''), $7, $8)
RETURNING id, account_id, slug, name, booking_type, location, currency, base_rate_minor, created_at
`

type CreatePropertyParams struct {
	ID            uuid.UUID
	AccountID     uuid.UUID
	Slug          string
	Name          string
	BookingType   string
	Location      string
	Currency      string
	BaseRateMinor int64
}

type CreatePropertyRow struct {
	ID            uuid.UUID
	AccountID     uuid.UUID
	Slug          string
	Name          string
	BookingType   string
	Location      *string
	Currency      string
	BaseRateMinor int64
	CreatedAt     time.Time
}

func (q *Queries) CreateProperty(ctx context.Context, arg CreatePropertyParams) (CreatePropertyRow, error) {
	row := q.db.QueryRow(ctx, createProperty,
		arg.ID,
		arg.AccountID,
		arg.Slug,
		arg.Name,
		arg.BookingType,
		arg.Location,
		arg.Currency,
		arg.BaseRateMinor,
	)
	var i CreatePropertyRow
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Slug,
		&i.Name,
		&i.BookingType,
		&i.Location,
		&i.Currency,
		&i.BaseRateMinor,
		&i.CreatedAt,
	)
	return i, err
}

const getPropertyBySlug = `-- name: GetPropertyBySlug :one

SELECT id, account_id, slug, name, booking_type, location, currency, base_rate_minor, created_at
FROM properties
WHERE slug = $1
`

type GetPropertyBySlugRow struct {
	ID            uuid.UUID
	AccountID     uuid.UUID
	Slug          string
	Name          string
	BookingType   string
	Location      *string
	Currency      string
	BaseRateMinor int64
	CreatedAt     time.Time
}

// Public: booking pages look a property up by its address, across accounts.
func (q *Queries) GetPropertyBySlug(ctx context.Context, slug string) (GetPropertyBySlugRow, error) {
	row := q.db.QueryRow(ctx, getPropertyBySlug, slug)
	var i GetPropertyBySlugRow
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Slug,
		&i.Name,
		&i.BookingType,
		&i.Location,
		&i.Currency,
		&i.BaseRateMinor,
		&i.CreatedAt,
	)
	return i, err
}

const listProperties = `-- name: ListProperties :many

SELECT id, account_id, slug, name, booking_type, location, currency, base_rate_minor, created_at
FROM properties
WHERE account_id = $1
  AND ($2::uuid[] IS NULL OR id = ANY ($2::uuid[]))
ORDER BY created_at DESC
LIMIT 200
`

type ListPropertiesParams struct {
	AccountID   uuid.UUID
	PropertyIds []uuid.UUID
}

type ListPropertiesRow struct {
	ID            uuid.UUID
	AccountID     uuid.UUID
	Slug          string
	Name          string
	BookingType   string
	Location      *string
	Currency      string
	BaseRateMinor int64
	CreatedAt     time.Time
}

// Owner queries take the account, and the membership's property scope when it has one, so a
// missed filter cannot leak another account's rows.
func (q *Queries) ListProperties(ctx context.Context, arg ListPropertiesParams) ([]ListPropertiesRow, error) {
	rows, err := q.db.Query(ctx, listProperties, arg.AccountID, arg.PropertyIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPropertiesRow{}
	for rows.Next() {
		var i ListPropertiesRow
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.Slug,
			&i.Name,
			&i.BookingType,
			&i.Location,
			&i.Currency,
			&i.BaseRateMinor,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
