// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: setup.sql

package queries

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const archiveUnitsNotIn = `-- name: ArchiveUnitsNotIn :many
UPDATE units SET archived_at = $1::timestamptz
WHERE property_id = $2 AND account_id = $3 AND archived_at IS NULL
  AND NOT (id = ANY ($4::uuid[]))
RETURNING id
`

type ArchiveUnitsNotInParams struct {
	Now        time.Time
	PropertyID uuid.UUID
	AccountID  uuid.UUID
	Keep       []uuid.UUID
}

func (q *Queries) ArchiveUnitsNotIn(ctx context.Context, arg ArchiveUnitsNotInParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, archiveUnitsNotIn,
		arg.Now,
		arg.PropertyID,
		arg.AccountID,
		arg.Keep,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const chargeIDs = `-- name: ChargeIDs :many
SELECT id FROM charges WHERE property_id = $1 AND account_id = $2
`

type ChargeIDsParams struct {
	PropertyID uuid.UUID
	AccountID  uuid.UUID
}

func (q *Queries) ChargeIDs(ctx context.Context, arg ChargeIDsParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, chargeIDs, arg.PropertyID, arg.AccountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteChargesNotIn = `-- name: DeleteChargesNotIn :exec
DELETE FROM charges
WHERE property_id = $1 AND account_id = $2 AND NOT (id = ANY ($3::uuid[]))
`

type DeleteChargesNotInParams struct {
	PropertyID uuid.UUID
	AccountID  uuid.UUID
	Keep       []uuid.UUID
}

func (q *Queries) DeleteChargesNotIn(ctx context.Context, arg DeleteChargesNotInParams) error {
	_, err := q.db.Exec(ctx, deleteChargesNotIn, arg.PropertyID, arg.AccountID, arg.Keep)
	return err
}

const deleteExtrasNotIn = `-- name: DeleteExtrasNotIn :exec
DELETE FROM extras
WHERE property_id = $1 AND account_id = $2 AND NOT (id = ANY ($3::uuid[]))
`

type DeleteExtrasNotInParams struct {
	PropertyID uuid.UUID
	AccountID  uuid.UUID
	Keep       []uuid.UUID
}

func (q *Queries) DeleteExtrasNotIn(ctx context.Context, arg DeleteExtrasNotInParams) error {
	_, err := q.db.Exec(ctx, deleteExtrasNotIn, arg.PropertyID, arg.AccountID, arg.Keep)
	return err
}

const deleteIcalFeedsNotIn = `-- name: DeleteIcalFeedsNotIn :exec
DELETE FROM ical_feeds
WHERE property_id = $1 AND account_id = $2 AND NOT (id = ANY ($3::uuid[]))
`

type DeleteIcalFeedsNotInParams struct {
	PropertyID uuid.UUID
	AccountID  uuid.UUID
	Keep       []uuid.UUID
}

func (q *Queries) DeleteIcalFeedsNotIn(ctx context.Context, arg DeleteIcalFeedsNotInParams) error {
	_, err := q.db.Exec(ctx, deleteIcalFeedsNotIn, arg.PropertyID, arg.AccountID, arg.Keep)
	return err
}

const deleteLengthDiscounts = `-- name: DeleteLengthDiscounts :exec
DELETE FROM length_discounts WHERE property_id = $1 AND account_id = $2
`

type DeleteLengthDiscountsParams struct {
	PropertyID uuid.UUID
	AccountID  uuid.UUID
}

func (q *Queries) DeleteLengthDiscounts(ctx context.Context, arg DeleteLengthDiscountsParams) error {
	_, err := q.db.Exec(ctx, deleteLengthDiscounts, arg.PropertyID, arg.AccountID)
	return err
}

const deletePhotos = `-- name: DeletePhotos :exec
DELETE FROM property_photos WHERE property_id = $1 AND account_id = $2
`

type DeletePhotosParams struct {
	PropertyID uuid.UUID
	AccountID  uuid.UUID
}

func (q *Queries) DeletePhotos(ctx context.Context, arg DeletePhotosParams) error {
	_, err := q.db.Exec(ctx, deletePhotos, arg.PropertyID, arg.AccountID)
	return err
}

const deletePromosNotIn = `-- name: DeletePromosNotIn :exec
DELETE FROM promos
WHERE property_id = $1 AND account_id = $2 AND NOT (id = ANY ($3::uuid[]))
`

type DeletePromosNotInParams struct {
	PropertyID uuid.UUID
	AccountID  uuid.UUID
	Keep       []uuid.UUID
}

func (q *Queries) DeletePromosNotIn(ctx context.Context, arg DeletePromosNotInParams) error {
	_, err := q.db.Exec(ctx, deletePromosNotIn, arg.PropertyID, arg.AccountID, arg.Keep)
	return err
}

const deleteSeasonPrices = `-- name: DeleteSeasonPrices :exec
DELETE FROM season_prices WHERE property_id = $1 AND account_id = $2
`

type DeleteSeasonPricesParams struct {
	PropertyID uuid.UUID
	AccountID  uuid.UUID
}

func (q *Queries) DeleteSeasonPrices(ctx context.Context, arg DeleteSeasonPricesParams) error {
	_, err := q.db.Exec(ctx, deleteSeasonPrices, arg.PropertyID, arg.AccountID)
	return err
}

const deleteSeasonPricesForUnits = `-- name: DeleteSeasonPricesForUnits :exec
DELETE FROM season_prices
WHERE property_id = $1 AND account_id = $2 AND unit_id = ANY ($3::uuid[])
`

type DeleteSeasonPricesForUnitsParams struct {
	PropertyID uuid.UUID
	AccountID  uuid.UUID
	UnitIds    []uuid.UUID
}

func (q *Queries) DeleteSeasonPricesForUnits(ctx context.Context, arg DeleteSeasonPricesForUnitsParams) error {
	_, err := q.db.Exec(ctx, deleteSeasonPricesForUnits, arg.PropertyID, arg.AccountID, arg.UnitIds)
	return err
}

const deleteSeasonsNotIn = `-- name: DeleteSeasonsNotIn :exec
DELETE FROM seasons
WHERE property_id = $1 AND account_id = $2 AND NOT (id = ANY ($3::uuid[]))
`

type DeleteSeasonsNotInParams struct {
	PropertyID uuid.UUID
	AccountID  uuid.UUID
	Keep       []uuid.UUID
}

func (q *Queries) DeleteSeasonsNotIn(ctx context.Context, arg DeleteSeasonsNotInParams) error {
	_, err := q.db.Exec(ctx, deleteSeasonsNotIn, arg.PropertyID, arg.AccountID, arg.Keep)
	return err
}

const deleteUnitLinks = `-- name: DeleteUnitLinks :exec
DELETE FROM unit_links WHERE property_id = $1 AND account_id = $2
`

type DeleteUnitLinksParams struct {
	PropertyID uuid.UUID
	AccountID  uuid.UUID
}

func (q *Queries) DeleteUnitLinks(ctx context.Context, arg DeleteUnitLinksParams) error {
	_, err := q.db.Exec(ctx, deleteUnitLinks, arg.PropertyID, arg.AccountID)
	return err
}

const extraIDs = `-- name: ExtraIDs :many
SELECT id FROM extras WHERE property_id = $1 AND account_id = $2
`

type ExtraIDsParams struct {
	PropertyID uuid.UUID
	AccountID  uuid.UUID
}

func (q *Queries) ExtraIDs(ctx context.Context, arg ExtraIDsParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, extraIDs, arg.PropertyID, arg.AccountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const icalFeedIDs = `-- name: IcalFeedIDs :many
SELECT id FROM ical_feeds WHERE property_id = $1 AND account_id = $2
`

type IcalFeedIDsParams struct {
	PropertyID uuid.UUID
	AccountID  uuid.UUID
}

func (q *Queries) IcalFeedIDs(ctx context.Context, arg IcalFeedIDsParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, icalFeedIDs, arg.PropertyID, arg.AccountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertCharge = `-- name: InsertCharge :exec
INSERT INTO charges (id, account_id, property_id, name, kind, amount, per, enabled, note, position)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
`

type InsertChargeParams struct {
	ID         uuid.UUID
	AccountID  uuid.UUID
	PropertyID uuid.UUID
	Name       string
	Kind       string
	Amount     int64
	Per        string
	Enabled    bool
	Note       string
	Position   int16
}

func (q *Queries) InsertCharge(ctx context.Context, arg InsertChargeParams) error {
	_, err := q.db.Exec(ctx, insertCharge,
		arg.ID,
		arg.AccountID,
		arg.PropertyID,
		arg.Name,
		arg.Kind,
		arg.Amount,
		arg.Per,
		arg.Enabled,
		arg.Note,
		arg.Position,
	)
	return err
}

const insertExtra = `-- name: InsertExtra :exec
INSERT INTO extras (id, account_id, property_id, name, price, per, on_request, enabled, position)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
`

type InsertExtraParams struct {
	ID         uuid.UUID
	AccountID  uuid.UUID
	PropertyID uuid.UUID
	Name       string
	Price      int64
	Per        string
	OnRequest  bool
	Enabled    bool
	Position   int16
}

func (q *Queries) InsertExtra(ctx context.Context, arg InsertExtraParams) error {
	_, err := q.db.Exec(ctx, insertExtra,
		arg.ID,
		arg.AccountID,
		arg.PropertyID,
		arg.Name,
		arg.Price,
		arg.Per,
		arg.OnRequest,
		arg.Enabled,
		arg.Position,
	)
	return err
}

const insertIcalFeed = `-- name: InsertIcalFeed :exec
INSERT INTO ical_feeds (id, account_id, property_id, channel, url, position)
VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertIcalFeedParams struct {
	ID         uuid.UUID
	AccountID  uuid.UUID
	PropertyID uuid.UUID
	Channel    string
	Url        string
	Position   int16
}

func (q *Queries) InsertIcalFeed(ctx context.Context, arg InsertIcalFeedParams) error {
	_, err := q.db.Exec(ctx, insertIcalFeed,
		arg.ID,
		arg.AccountID,
		arg.PropertyID,
		arg.Channel,
		arg.Url,
		arg.Position,
	)
	return err
}

const insertLengthDiscount = `-- name: InsertLengthDiscount :exec
INSERT INTO length_discounts (account_id, property_id, nights, percent)
VALUES ($1, $2, $3, $4)
`

type InsertLengthDiscountParams struct {
	AccountID  uuid.UUID
	PropertyID uuid.UUID
	Nights     int16
	Percent    int16
}

func (q *Queries) InsertLengthDiscount(ctx context.Context, arg InsertLengthDiscountParams) error {
	_, err := q.db.Exec(ctx, insertLengthDiscount,
		arg.AccountID,
		arg.PropertyID,
		arg.Nights,
		arg.Percent,
	)
	return err
}

const insertPhoto = `-- name: InsertPhoto :exec
INSERT INTO property_photos (id, account_id, property_id, key, caption, position)
VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertPhotoParams struct {
	ID         uuid.UUID
	AccountID  uuid.UUID
	PropertyID uuid.UUID
	Key        string
	Caption    string
	Position   int16
}

func (q *Queries) InsertPhoto(ctx context.Context, arg InsertPhotoParams) error {
	_, err := q.db.Exec(ctx, insertPhoto,
		arg.ID,
		arg.AccountID,
		arg.PropertyID,
		arg.Key,
		arg.Caption,
		arg.Position,
	)
	return err
}

const insertPromo = `-- name: InsertPromo :exec
INSERT INTO promos (id, account_id, property_id, code, kind, amount, starts_on, ends_on,
                    usage_limit, min_nights, note, position)
VALUES ($1, $2, $3, $4, $5, $6, $7,
        $8, $9, $10, $11, $12)
`

type InsertPromoParams struct {
	ID         uuid.UUID
	AccountID  uuid.UUID
	PropertyID uuid.UUID
	Code       string
	Kind       string
	Amount     int64
	StartsOn   *time.Time
	EndsOn     *time.Time
	UsageLimit *int32
	MinNights  *int16
	Note       string
	Position   int16
}

func (q *Queries) InsertPromo(ctx context.Context, arg InsertPromoParams) error {
	_, err := q.db.Exec(ctx, insertPromo,
		arg.ID,
		arg.AccountID,
		arg.PropertyID,
		arg.Code,
		arg.Kind,
		arg.Amount,
		arg.StartsOn,
		arg.EndsOn,
		arg.UsageLimit,
		arg.MinNights,
		arg.Note,
		arg.Position,
	)
	return err
}

const insertSeason = `-- name: InsertSeason :exec
INSERT INTO seasons (id, account_id, property_id, name, start_md, end_md, min_nights, position)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type InsertSeasonParams struct {
	ID         uuid.UUID
	AccountID  uuid.UUID
	PropertyID uuid.UUID
	Name       string
	StartMd    string
	EndMd      string
	MinNights  *int16
	Position   int16
}

func (q *Queries) InsertSeason(ctx context.Context, arg InsertSeasonParams) error {
	_, err := q.db.Exec(ctx, insertSeason,
		arg.ID,
		arg.AccountID,
		arg.PropertyID,
		arg.Name,
		arg.StartMd,
		arg.EndMd,
		arg.MinNights,
		arg.Position,
	)
	return err
}

const insertSeasonPrice = `-- name: InsertSeasonPrice :exec
INSERT INTO season_prices (account_id, property_id, season_id, unit_id, price)
VALUES ($1, $2, $3, $4, $5)
`

type InsertSeasonPriceParams struct {
	AccountID  uuid.UUID
	PropertyID uuid.UUID
	SeasonID   uuid.UUID
	UnitID     uuid.UUID
	Price      int64
}

func (q *Queries) InsertSeasonPrice(ctx context.Context, arg InsertSeasonPriceParams) error {
	_, err := q.db.Exec(ctx, insertSeasonPrice,
		arg.AccountID,
		arg.PropertyID,
		arg.SeasonID,
		arg.UnitID,
		arg.Price,
	)
	return err
}

const insertUnit = `-- name: InsertUnit :exec
INSERT INTO units (id, account_id, property_id, name, sleeps, beds, rate, weekend_rate, position)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
`

type InsertUnitParams struct {
	ID          uuid.UUID
	AccountID   uuid.UUID
	PropertyID  uuid.UUID
	Name        string
	Sleeps      int16
	Beds        string
	Rate        int64
	WeekendRate *int64
	Position    int16
}

func (q *Queries) InsertUnit(ctx context.Context, arg InsertUnitParams) error {
	_, err := q.db.Exec(ctx, insertUnit,
		arg.ID,
		arg.AccountID,
		arg.PropertyID,
		arg.Name,
		arg.Sleeps,
		arg.Beds,
		arg.Rate,
		arg.WeekendRate,
		arg.Position,
	)
	return err
}

const insertUnitLink = `-- name: InsertUnitLink :exec
INSERT INTO unit_links (account_id, property_id, parent_unit_id, child_unit_id)
VALUES ($1, $2, $3, $4)
`

type InsertUnitLinkParams struct {
	AccountID    uuid.UUID
	PropertyID   uuid.UUID
	ParentUnitID uuid.UUID
	ChildUnitID  uuid.UUID
}

func (q *Queries) InsertUnitLink(ctx context.Context, arg InsertUnitLinkParams) error {
	_, err := q.db.Exec(ctx, insertUnitLink,
		arg.AccountID,
		arg.PropertyID,
		arg.ParentUnitID,
		arg.ChildUnitID,
	)
	return err
}

const listCharges = `-- name: ListCharges :many

SELECT id, property_id, name, kind, amount, per, enabled, note
FROM charges
WHERE account_id = $1 AND property_id = ANY ($2::uuid[])
ORDER BY property_id, position
`

type ListChargesParams struct {
	AccountID   uuid.UUID
	PropertyIds []uuid.UUID
}

type ListChargesRow struct {
	ID         uuid.UUID
	PropertyID uuid.UUID
	Name       string
	Kind       string
	Amount     int64
	Per        string
	Enabled    bool
	Note       string
}

// Charges and extras -----------------------------------------------------------------------
func (q *Queries) ListCharges(ctx context.Context, arg ListChargesParams) ([]ListChargesRow, error) {
	rows, err := q.db.Query(ctx, listCharges, arg.AccountID, arg.PropertyIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListChargesRow{}
	for rows.Next() {
		var i ListChargesRow
		if err := rows.Scan(
			&i.ID,
			&i.PropertyID,
			&i.Name,
			&i.Kind,
			&i.Amount,
			&i.Per,
			&i.Enabled,
			&i.Note,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExtras = `-- name: ListExtras :many
SELECT id, property_id, name, price, per, on_request, enabled
FROM extras
WHERE account_id = $1 AND property_id = ANY ($2::uuid[])
ORDER BY property_id, position
`

type ListExtrasParams struct {
	AccountID   uuid.UUID
	PropertyIds []uuid.UUID
}

type ListExtrasRow struct {
	ID         uuid.UUID
	PropertyID uuid.UUID
	Name       string
	Price      int64
	Per        string
	OnRequest  bool
	Enabled    bool
}

func (q *Queries) ListExtras(ctx context.Context, arg ListExtrasParams) ([]ListExtrasRow, error) {
	rows, err := q.db.Query(ctx, listExtras, arg.AccountID, arg.PropertyIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListExtrasRow{}
	for rows.Next() {
		var i ListExtrasRow
		if err := rows.Scan(
			&i.ID,
			&i.PropertyID,
			&i.Name,
			&i.Price,
			&i.Per,
			&i.OnRequest,
			&i.Enabled,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIcalFeeds = `-- name: ListIcalFeeds :many

SELECT id, property_id, channel, url, status, last_synced_at, last_error, upcoming
FROM ical_feeds
WHERE account_id = $1 AND property_id = ANY ($2::uuid[])
ORDER BY property_id, position
`

type ListIcalFeedsParams struct {
	AccountID   uuid.UUID
	PropertyIds []uuid.UUID
}

type ListIcalFeedsRow struct {
	ID           uuid.UUID
	PropertyID   uuid.UUID
	Channel      string
	Url          string
	Status       string
	LastSyncedAt *time.Time
	LastError    *string
	Upcoming     int32
}

// Imported calendars -----------------------------------------------------------------------
func (q *Queries) ListIcalFeeds(ctx context.Context, arg ListIcalFeedsParams) ([]ListIcalFeedsRow, error) {
	rows, err := q.db.Query(ctx, listIcalFeeds, arg.AccountID, arg.PropertyIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListIcalFeedsRow{}
	for rows.Next() {
		var i ListIcalFeedsRow
		if err := rows.Scan(
			&i.ID,
			&i.PropertyID,
			&i.Channel,
			&i.Url,
			&i.Status,
			&i.LastSyncedAt,
			&i.LastError,
			&i.Upcoming,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLengthDiscounts = `-- name: ListLengthDiscounts :many
SELECT property_id, nights, percent
FROM length_discounts
WHERE account_id = $1 AND property_id = ANY ($2::uuid[])
ORDER BY property_id, nights
`

type ListLengthDiscountsParams struct {
	AccountID   uuid.UUID
	PropertyIds []uuid.UUID
}

type ListLengthDiscountsRow struct {
	PropertyID uuid.UUID
	Nights     int16
	Percent    int16
}

func (q *Queries) ListLengthDiscounts(ctx context.Context, arg ListLengthDiscountsParams) ([]ListLengthDiscountsRow, error) {
	rows, err := q.db.Query(ctx, listLengthDiscounts, arg.AccountID, arg.PropertyIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLengthDiscountsRow{}
	for rows.Next() {
		var i ListLengthDiscountsRow
		if err := rows.Scan(&i.PropertyID, &i.Nights, &i.Percent); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPaymentSettings = `-- name: ListPaymentSettings :many

SELECT property_id, bank_enabled, bank_name, account_name, account_number_enc, pay_within_hours,
       cancel_if_unpaid, at_property, cards_status
FROM payment_settings
WHERE account_id = $1 AND property_id = ANY ($2::uuid[])
`

type ListPaymentSettingsParams struct {
	AccountID   uuid.UUID
	PropertyIds []uuid.UUID
}

type ListPaymentSettingsRow struct {
	PropertyID       uuid.UUID
	BankEnabled      bool
	BankName         string
	AccountName      string
	AccountNumberEnc []byte
	PayWithinHours   int16
	CancelIfUnpaid   bool
	AtProperty       bool
	CardsStatus      string
}

// Payment settings -------------------------------------------------------------------------
func (q *Queries) ListPaymentSettings(ctx context.Context, arg ListPaymentSettingsParams) ([]ListPaymentSettingsRow, error) {
	rows, err := q.db.Query(ctx, listPaymentSettings, arg.AccountID, arg.PropertyIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPaymentSettingsRow{}
	for rows.Next() {
		var i ListPaymentSettingsRow
		if err := rows.Scan(
			&i.PropertyID,
			&i.BankEnabled,
			&i.BankName,
			&i.AccountName,
			&i.AccountNumberEnc,
			&i.PayWithinHours,
			&i.CancelIfUnpaid,
			&i.AtProperty,
			&i.CardsStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPhotos = `-- name: ListPhotos :many

SELECT id, property_id, key, caption
FROM property_photos
WHERE account_id = $1 AND property_id = ANY ($2::uuid[])
ORDER BY property_id, position
`

type ListPhotosParams struct {
	AccountID   uuid.UUID
	PropertyIds []uuid.UUID
}

type ListPhotosRow struct {
	ID         uuid.UUID
	PropertyID uuid.UUID
	Key        string
	Caption    string
}

// Photos -----------------------------------------------------------------------------------
func (q *Queries) ListPhotos(ctx context.Context, arg ListPhotosParams) ([]ListPhotosRow, error) {
	rows, err := q.db.Query(ctx, listPhotos, arg.AccountID, arg.PropertyIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPhotosRow{}
	for rows.Next() {
		var i ListPhotosRow
		if err := rows.Scan(
			&i.ID,
			&i.PropertyID,
			&i.Key,
			&i.Caption,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPromos = `-- name: ListPromos :many

SELECT id, property_id, code, kind, amount, starts_on, ends_on, usage_limit, used_count,
       min_nights, note
FROM promos
WHERE account_id = $1 AND property_id = ANY ($2::uuid[])
ORDER BY property_id, position
`

type ListPromosParams struct {
	AccountID   uuid.UUID
	PropertyIds []uuid.UUID
}

type ListPromosRow struct {
	ID         uuid.UUID
	PropertyID uuid.UUID
	Code       string
	Kind       string
	Amount     int64
	StartsOn   *time.Time
	EndsOn     *time.Time
	UsageLimit *int32
	UsedCount  int32
	MinNights  *int16
	Note       string
}

// Promo codes ------------------------------------------------------------------------------
func (q *Queries) ListPromos(ctx context.Context, arg ListPromosParams) ([]ListPromosRow, error) {
	rows, err := q.db.Query(ctx, listPromos, arg.AccountID, arg.PropertyIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPromosRow{}
	for rows.Next() {
		var i ListPromosRow
		if err := rows.Scan(
			&i.ID,
			&i.PropertyID,
			&i.Code,
			&i.Kind,
			&i.Amount,
			&i.StartsOn,
			&i.EndsOn,
			&i.UsageLimit,
			&i.UsedCount,
			&i.MinNights,
			&i.Note,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSeasonPrices = `-- name: ListSeasonPrices :many
SELECT season_id, unit_id, price
FROM season_prices
WHERE account_id = $1 AND property_id = ANY ($2::uuid[])
`

type ListSeasonPricesParams struct {
	AccountID   uuid.UUID
	PropertyIds []uuid.UUID
}

type ListSeasonPricesRow struct {
	SeasonID uuid.UUID
	UnitID   uuid.UUID
	Price    int64
}

func (q *Queries) ListSeasonPrices(ctx context.Context, arg ListSeasonPricesParams) ([]ListSeasonPricesRow, error) {
	rows, err := q.db.Query(ctx, listSeasonPrices, arg.AccountID, arg.PropertyIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSeasonPricesRow{}
	for rows.Next() {
		var i ListSeasonPricesRow
		if err := rows.Scan(&i.SeasonID, &i.UnitID, &i.Price); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSeasons = `-- name: ListSeasons :many

SELECT id, property_id, name, start_md, end_md, min_nights
FROM seasons
WHERE account_id = $1 AND property_id = ANY ($2::uuid[])
ORDER BY property_id, position
`

type ListSeasonsParams struct {
	AccountID   uuid.UUID
	PropertyIds []uuid.UUID
}

type ListSeasonsRow struct {
	ID         uuid.UUID
	PropertyID uuid.UUID
	Name       string
	StartMd    string
	EndMd      string
	MinNights  *int16
}

// Seasons and length discounts -------------------------------------------------------------
func (q *Queries) ListSeasons(ctx context.Context, arg ListSeasonsParams) ([]ListSeasonsRow, error) {
	rows, err := q.db.Query(ctx, listSeasons, arg.AccountID, arg.PropertyIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSeasonsRow{}
	for rows.Next() {
		var i ListSeasonsRow
		if err := rows.Scan(
			&i.ID,
			&i.PropertyID,
			&i.Name,
			&i.StartMd,
			&i.EndMd,
			&i.MinNights,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnitLinks = `-- name: ListUnitLinks :many
SELECT parent_unit_id, child_unit_id
FROM unit_links
WHERE account_id = $1 AND property_id = ANY ($2::uuid[])
`

type ListUnitLinksParams struct {
	AccountID   uuid.UUID
	PropertyIds []uuid.UUID
}

type ListUnitLinksRow struct {
	ParentUnitID uuid.UUID
	ChildUnitID  uuid.UUID
}

func (q *Queries) ListUnitLinks(ctx context.Context, arg ListUnitLinksParams) ([]ListUnitLinksRow, error) {
	rows, err := q.db.Query(ctx, listUnitLinks, arg.AccountID, arg.PropertyIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUnitLinksRow{}
	for rows.Next() {
		var i ListUnitLinksRow
		if err := rows.Scan(&i.ParentUnitID, &i.ChildUnitID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnits = `-- name: ListUnits :many


SELECT id, property_id, name, sleeps, beds, rate, weekend_rate, position
FROM units
WHERE account_id = $1 AND property_id = ANY ($2::uuid[]) AND archived_at IS NULL
ORDER BY property_id, position, created_at
`

type ListUnitsParams struct {
	AccountID   uuid.UUID
	PropertyIds []uuid.UUID
}

type ListUnitsRow struct {
	ID          uuid.UUID
	PropertyID  uuid.UUID
	Name        string
	Sleeps      int16
	Beds        string
	Rate        int64
	WeekendRate *int64
	Position    int16
}

// A property's setup collections. Lists load every property in a page at once; writes are
// scoped by property and account. Collections are replaced as a whole: items whose id is kept
// are updated, new ones inserted, and the rest removed (units are archived instead).
// Units ------------------------------------------------------------------------------------
func (q *Queries) ListUnits(ctx context.Context, arg ListUnitsParams) ([]ListUnitsRow, error) {
	rows, err := q.db.Query(ctx, listUnits, arg.AccountID, arg.PropertyIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUnitsRow{}
	for rows.Next() {
		var i ListUnitsRow
		if err := rows.Scan(
			&i.ID,
			&i.PropertyID,
			&i.Name,
			&i.Sleeps,
			&i.Beds,
			&i.Rate,
			&i.WeekendRate,
			&i.Position,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const promoIDs = `-- name: PromoIDs :many
SELECT id FROM promos WHERE property_id = $1 AND account_id = $2
`

type PromoIDsParams struct {
	PropertyID uuid.UUID
	AccountID  uuid.UUID
}

func (q *Queries) PromoIDs(ctx context.Context, arg PromoIDsParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, promoIDs, arg.PropertyID, arg.AccountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const seasonIDs = `-- name: SeasonIDs :many
SELECT id FROM seasons WHERE property_id = $1 AND account_id = $2
`

type SeasonIDsParams struct {
	PropertyID uuid.UUID
	AccountID  uuid.UUID
}

func (q *Queries) SeasonIDs(ctx context.Context, arg SeasonIDsParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, seasonIDs, arg.PropertyID, arg.AccountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const unitIDs = `-- name: UnitIDs :many
SELECT id FROM units
WHERE property_id = $1 AND account_id = $2 AND archived_at IS NULL
`

type UnitIDsParams struct {
	PropertyID uuid.UUID
	AccountID  uuid.UUID
}

func (q *Queries) UnitIDs(ctx context.Context, arg UnitIDsParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, unitIDs, arg.PropertyID, arg.AccountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCharge = `-- name: UpdateCharge :exec
UPDATE charges SET name = $1, kind = $2, amount = $3, per = $4, enabled = $5,
                   note = $6, position = $7
WHERE id = $8 AND property_id = $9 AND account_id = $10
`

type UpdateChargeParams struct {
	Name       string
	Kind       string
	Amount     int64
	Per        string
	Enabled    bool
	Note       string
	Position   int16
	ID         uuid.UUID
	PropertyID uuid.UUID
	AccountID  uuid.UUID
}

func (q *Queries) UpdateCharge(ctx context.Context, arg UpdateChargeParams) error {
	_, err := q.db.Exec(ctx, updateCharge,
		arg.Name,
		arg.Kind,
		arg.Amount,
		arg.Per,
		arg.Enabled,
		arg.Note,
		arg.Position,
		arg.ID,
		arg.PropertyID,
		arg.AccountID,
	)
	return err
}

const updateExtra = `-- name: UpdateExtra :exec
UPDATE extras SET name = $1, price = $2, per = $3, on_request = $4,
                  enabled = $5, position = $6
WHERE id = $7 AND property_id = $8 AND account_id = $9
`

type UpdateExtraParams struct {
	Name       string
	Price      int64
	Per        string
	OnRequest  bool
	Enabled    bool
	Position   int16
	ID         uuid.UUID
	PropertyID uuid.UUID
	AccountID  uuid.UUID
}

func (q *Queries) UpdateExtra(ctx context.Context, arg UpdateExtraParams) error {
	_, err := q.db.Exec(ctx, updateExtra,
		arg.Name,
		arg.Price,
		arg.Per,
		arg.OnRequest,
		arg.Enabled,
		arg.Position,
		arg.ID,
		arg.PropertyID,
		arg.AccountID,
	)
	return err
}

const updateIcalFeed = `-- name: UpdateIcalFeed :exec
UPDATE ical_feeds SET
    channel              = $1,
    position             = $2,
    status               = CASE WHEN url = $3 THEN status ELSE 'pending' END,
    last_error           = CASE WHEN url = $3 THEN last_error END,
    consecutive_failures = CASE WHEN url = $3 THEN consecutive_failures ELSE 0 END,
    etag                 = CASE WHEN url = $3 THEN etag END,
    url                  = $3
WHERE id = $4 AND property_id = $5 AND account_id = $6
`

type UpdateIcalFeedParams struct {
	Channel    string
	Position   int16
	Url        string
	ID         uuid.UUID
	PropertyID uuid.UUID
	AccountID  uuid.UUID
}

// A new link starts over: pending until the import worker reads it.
func (q *Queries) UpdateIcalFeed(ctx context.Context, arg UpdateIcalFeedParams) error {
	_, err := q.db.Exec(ctx, updateIcalFeed,
		arg.Channel,
		arg.Position,
		arg.Url,
		arg.ID,
		arg.PropertyID,
		arg.AccountID,
	)
	return err
}

const updatePromo = `-- name: UpdatePromo :exec
UPDATE promos SET code = $1, kind = $2, amount = $3, starts_on = $4,
                  ends_on = $5, usage_limit = $6,
                  min_nights = $7, note = $8, position = $9
WHERE id = $10 AND property_id = $11 AND account_id = $12
`

type UpdatePromoParams struct {
	Code       string
	Kind       string
	Amount     int64
	StartsOn   *time.Time
	EndsOn     *time.Time
	UsageLimit *int32
	MinNights  *int16
	Note       string
	Position   int16
	ID         uuid.UUID
	PropertyID uuid.UUID
	AccountID  uuid.UUID
}

// The used count belongs to bookings and is never written here.
func (q *Queries) UpdatePromo(ctx context.Context, arg UpdatePromoParams) error {
	_, err := q.db.Exec(ctx, updatePromo,
		arg.Code,
		arg.Kind,
		arg.Amount,
		arg.StartsOn,
		arg.EndsOn,
		arg.UsageLimit,
		arg.MinNights,
		arg.Note,
		arg.Position,
		arg.ID,
		arg.PropertyID,
		arg.AccountID,
	)
	return err
}

const updateSeason = `-- name: UpdateSeason :exec
UPDATE seasons SET name = $1, start_md = $2, end_md = $3,
                   min_nights = $4, position = $5
WHERE id = $6 AND property_id = $7 AND account_id = $8
`

type UpdateSeasonParams struct {
	Name       string
	StartMd    string
	EndMd      string
	MinNights  *int16
	Position   int16
	ID         uuid.UUID
	PropertyID uuid.UUID
	AccountID  uuid.UUID
}

func (q *Queries) UpdateSeason(ctx context.Context, arg UpdateSeasonParams) error {
	_, err := q.db.Exec(ctx, updateSeason,
		arg.Name,
		arg.StartMd,
		arg.EndMd,
		arg.MinNights,
		arg.Position,
		arg.ID,
		arg.PropertyID,
		arg.AccountID,
	)
	return err
}

const updateUnit = `-- name: UpdateUnit :exec
UPDATE units SET name = $1, sleeps = $2, beds = $3, rate = $4,
                 weekend_rate = $5, position = $6
WHERE id = $7 AND property_id = $8 AND account_id = $9
`

type UpdateUnitParams struct {
	Name        string
	Sleeps      int16
	Beds        string
	Rate        int64
	WeekendRate *int64
	Position    int16
	ID          uuid.UUID
	PropertyID  uuid.UUID
	AccountID   uuid.UUID
}

func (q *Queries) UpdateUnit(ctx context.Context, arg UpdateUnitParams) error {
	_, err := q.db.Exec(ctx, updateUnit,
		arg.Name,
		arg.Sleeps,
		arg.Beds,
		arg.Rate,
		arg.WeekendRate,
		arg.Position,
		arg.ID,
		arg.PropertyID,
		arg.AccountID,
	)
	return err
}

const upsertPaymentSettings = `-- name: UpsertPaymentSettings :exec
INSERT INTO payment_settings (property_id, account_id, bank_enabled, bank_name, account_name,
                              account_number_enc, pay_within_hours, cancel_if_unpaid, at_property,
                              cards_status)
VALUES ($1, $2, $3, $4, $5,
        $6, $7, $8, $9,
        $10)
ON CONFLICT (property_id) DO UPDATE SET
    bank_enabled       = excluded.bank_enabled,
    bank_name          = excluded.bank_name,
    account_name       = excluded.account_name,
    account_number_enc = excluded.account_number_enc,
    pay_within_hours   = excluded.pay_within_hours,
    cancel_if_unpaid   = excluded.cancel_if_unpaid,
    at_property        = excluded.at_property,
    cards_status       = excluded.cards_status
WHERE payment_settings.account_id = excluded.account_id
`

type UpsertPaymentSettingsParams struct {
	PropertyID       uuid.UUID
	AccountID        uuid.UUID
	BankEnabled      bool
	BankName         string
	AccountName      string
	AccountNumberEnc []byte
	PayWithinHours   int16
	CancelIfUnpaid   bool
	AtProperty       bool
	CardsStatus      string
}

func (q *Queries) UpsertPaymentSettings(ctx context.Context, arg UpsertPaymentSettingsParams) error {
	_, err := q.db.Exec(ctx, upsertPaymentSettings,
		arg.PropertyID,
		arg.AccountID,
		arg.BankEnabled,
		arg.BankName,
		arg.AccountName,
		arg.AccountNumberEnc,
		arg.PayWithinHours,
		arg.CancelIfUnpaid,
		arg.AtProperty,
		arg.CardsStatus,
	)
	return err
}
