// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package queries

import (
	"context"

	"github.com/google/uuid"
)

const getUser = `-- name: GetUser :one
SELECT id, phone, name, email, language, photo_key, created_at, updated_at FROM users WHERE id = $1
`

func (q *Queries) GetUser(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Phone,
		&i.Name,
		&i.Email,
		&i.Language,
		&i.PhotoKey,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByPhone = `-- name: GetUserByPhone :one
SELECT id, phone, name, email, language, photo_key, created_at, updated_at FROM users WHERE phone = $1
`

func (q *Queries) GetUserByPhone(ctx context.Context, phone string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByPhone, phone)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Phone,
		&i.Name,
		&i.Email,
		&i.Language,
		&i.PhotoKey,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertUserIfMissing = `-- name: InsertUserIfMissing :exec
INSERT INTO users (id, phone) VALUES ($1, $2)
ON CONFLICT (phone) DO NOTHING
`

type InsertUserIfMissingParams struct {
	ID    uuid.UUID
	Phone string
}

func (q *Queries) InsertUserIfMissing(ctx context.Context, arg InsertUserIfMissingParams) error {
	_, err := q.db.Exec(ctx, insertUserIfMissing, arg.ID, arg.Phone)
	return err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users SET
    name     = coalesce($1::text, name),
    email    = CASE WHEN $2::text IS NULL THEN email
                    ELSE nullif($2::text, '') END,
    language = coalesce($3::text, language)
WHERE id = $4
RETURNING id, phone, name, email, language, photo_key, created_at, updated_at
`

type UpdateUserParams struct {
	Name     *string
	Email    *string
	Language *string
	ID       uuid.UUID
}

// Null leaves a field as it is; an empty email clears it.
func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.Name,
		arg.Email,
		arg.Language,
		arg.ID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Phone,
		&i.Name,
		&i.Email,
		&i.Language,
		&i.PhotoKey,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
