//go:build go1.22

// Package oapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package oapi

import (
	"bytes"
	"compress/flate"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for AccountStatus.
const (
	Active AccountStatus = "active"
	Closed AccountStatus = "closed"
	Grace  AccountStatus = "grace"
	Lapsed AccountStatus = "lapsed"
	Trial  AccountStatus = "trial"
)

// Valid indicates whether the value is a known member of the AccountStatus enum.
func (e AccountStatus) Valid() bool {
	switch e {
	case Active:
		return true
	case Closed:
		return true
	case Grace:
		return true
	case Lapsed:
		return true
	case Trial:
		return true
	default:
		return false
	}
}

// Defines values for BookingSettingsDisplayCurrencies.
const (
	BookingSettingsDisplayCurrenciesAUD BookingSettingsDisplayCurrencies = "AUD"
	BookingSettingsDisplayCurrenciesEUR BookingSettingsDisplayCurrencies = "EUR"
	BookingSettingsDisplayCurrenciesGBP BookingSettingsDisplayCurrencies = "GBP"
	BookingSettingsDisplayCurrenciesINR BookingSettingsDisplayCurrencies = "INR"
	BookingSettingsDisplayCurrenciesLKR BookingSettingsDisplayCurrencies = "LKR"
	BookingSettingsDisplayCurrenciesUSD BookingSettingsDisplayCurrencies = "USD"
)

// Valid indicates whether the value is a known member of the BookingSettingsDisplayCurrencies enum.
func (e BookingSettingsDisplayCurrencies) Valid() bool {
	switch e {
	case BookingSettingsDisplayCurrenciesAUD:
		return true
	case BookingSettingsDisplayCurrenciesEUR:
		return true
	case BookingSettingsDisplayCurrenciesGBP:
		return true
	case BookingSettingsDisplayCurrenciesINR:
		return true
	case BookingSettingsDisplayCurrenciesLKR:
		return true
	case BookingSettingsDisplayCurrenciesUSD:
		return true
	default:
		return false
	}
}

// Defines values for BookingSettingsMode.
const (
	Instant BookingSettingsMode = "instant"
	Request BookingSettingsMode = "request"
)

// Valid indicates whether the value is a known member of the BookingSettingsMode enum.
func (e BookingSettingsMode) Valid() bool {
	switch e {
	case Instant:
		return true
	case Request:
		return true
	default:
		return false
	}
}

// Defines values for BookingType.
const (
	Entire BookingType = "entire"
	Rooms  BookingType = "rooms"
)

// Valid indicates whether the value is a known member of the BookingType enum.
func (e BookingType) Valid() bool {
	switch e {
	case Entire:
		return true
	case Rooms:
		return true
	default:
		return false
	}
}

// Defines values for ChargePer.
const (
	ChargePerGuest ChargePer = "guest"
	ChargePerNight ChargePer = "night"
	ChargePerStay  ChargePer = "stay"
)

// Valid indicates whether the value is a known member of the ChargePer enum.
func (e ChargePer) Valid() bool {
	switch e {
	case ChargePerGuest:
		return true
	case ChargePerNight:
		return true
	case ChargePerStay:
		return true
	default:
		return false
	}
}

// Defines values for ChargeInputPer.
const (
	ChargeInputPerGuest ChargeInputPer = "guest"
	ChargeInputPerNight ChargeInputPer = "night"
	ChargeInputPerStay  ChargeInputPer = "stay"
)

// Valid indicates whether the value is a known member of the ChargeInputPer enum.
func (e ChargeInputPer) Valid() bool {
	switch e {
	case ChargeInputPerGuest:
		return true
	case ChargeInputPerNight:
		return true
	case ChargeInputPerStay:
		return true
	default:
		return false
	}
}

// Defines values for ChargeKind.
const (
	Fixed   ChargeKind = "fixed"
	Percent ChargeKind = "percent"
)

// Valid indicates whether the value is a known member of the ChargeKind enum.
func (e ChargeKind) Valid() bool {
	switch e {
	case Fixed:
		return true
	case Percent:
		return true
	default:
		return false
	}
}

// Defines values for Currency.
const (
	CurrencyEUR Currency = "EUR"
	CurrencyGBP Currency = "GBP"
	CurrencyLKR Currency = "LKR"
	CurrencyUSD Currency = "USD"
)

// Valid indicates whether the value is a known member of the Currency enum.
func (e Currency) Valid() bool {
	switch e {
	case CurrencyEUR:
		return true
	case CurrencyGBP:
		return true
	case CurrencyLKR:
		return true
	case CurrencyUSD:
		return true
	default:
		return false
	}
}

// Defines values for ExtraPer.
const (
	ExtraPerGuest      ExtraPer = "guest"
	ExtraPerGuestNight ExtraPer = "guestNight"
	ExtraPerNight      ExtraPer = "night"
	ExtraPerStay       ExtraPer = "stay"
	ExtraPerTrip       ExtraPer = "trip"
)

// Valid indicates whether the value is a known member of the ExtraPer enum.
func (e ExtraPer) Valid() bool {
	switch e {
	case ExtraPerGuest:
		return true
	case ExtraPerGuestNight:
		return true
	case ExtraPerNight:
		return true
	case ExtraPerStay:
		return true
	case ExtraPerTrip:
		return true
	default:
		return false
	}
}

// Defines values for HealthDatabase.
const (
	Down HealthDatabase = "down"
	Up   HealthDatabase = "up"
)

// Valid indicates whether the value is a known member of the HealthDatabase enum.
func (e HealthDatabase) Valid() bool {
	switch e {
	case Down:
		return true
	case Up:
		return true
	default:
		return false
	}
}

// Defines values for HealthStatus.
const (
	HealthStatusDegraded HealthStatus = "degraded"
	HealthStatusOk       HealthStatus = "ok"
)

// Valid indicates whether the value is a known member of the HealthStatus enum.
func (e HealthStatus) Valid() bool {
	switch e {
	case HealthStatusDegraded:
		return true
	case HealthStatusOk:
		return true
	default:
		return false
	}
}

// Defines values for IcalChannel.
const (
	Agoda   IcalChannel = "agoda"
	Airbnb  IcalChannel = "airbnb"
	Booking IcalChannel = "booking"
	Expedia IcalChannel = "expedia"
	Other   IcalChannel = "other"
)

// Valid indicates whether the value is a known member of the IcalChannel enum.
func (e IcalChannel) Valid() bool {
	switch e {
	case Agoda:
		return true
	case Airbnb:
		return true
	case Booking:
		return true
	case Expedia:
		return true
	case Other:
		return true
	default:
		return false
	}
}

// Defines values for IcalFeedStatus.
const (
	IcalFeedStatusError   IcalFeedStatus = "error"
	IcalFeedStatusOk      IcalFeedStatus = "ok"
	IcalFeedStatusPending IcalFeedStatus = "pending"
)

// Valid indicates whether the value is a known member of the IcalFeedStatus enum.
func (e IcalFeedStatus) Valid() bool {
	switch e {
	case IcalFeedStatusError:
		return true
	case IcalFeedStatusOk:
		return true
	case IcalFeedStatusPending:
		return true
	default:
		return false
	}
}

// Defines values for Language.
const (
	En Language = "en"
	Si Language = "si"
)

// Valid indicates whether the value is a known member of the Language enum.
func (e Language) Valid() bool {
	switch e {
	case En:
		return true
	case Si:
		return true
	default:
		return false
	}
}

// Defines values for PaymentSettingsCards.
const (
	PaymentSettingsCardsOff     PaymentSettingsCards = "off"
	PaymentSettingsCardsOn      PaymentSettingsCards = "on"
	PaymentSettingsCardsPending PaymentSettingsCards = "pending"
)

// Valid indicates whether the value is a known member of the PaymentSettingsCards enum.
func (e PaymentSettingsCards) Valid() bool {
	switch e {
	case PaymentSettingsCardsOff:
		return true
	case PaymentSettingsCardsOn:
		return true
	case PaymentSettingsCardsPending:
		return true
	default:
		return false
	}
}

// Defines values for Policy.
const (
	Flexible Policy = "flexible"
	Moderate Policy = "moderate"
	Strict   Policy = "strict"
)

// Valid indicates whether the value is a known member of the Policy enum.
func (e Policy) Valid() bool {
	switch e {
	case Flexible:
		return true
	case Moderate:
		return true
	case Strict:
		return true
	default:
		return false
	}
}

// Defines values for Role.
const (
	Caretaker Role = "caretaker"
	Manager   Role = "manager"
	Owner     Role = "owner"
)

// Valid indicates whether the value is a known member of the Role enum.
func (e Role) Valid() bool {
	switch e {
	case Caretaker:
		return true
	case Manager:
		return true
	case Owner:
		return true
	default:
		return false
	}
}

// Defines values for UploadRequestContentType.
const (
	Imageheic UploadRequestContentType = "image/heic"
	Imagejpeg UploadRequestContentType = "image/jpeg"
	Imagepng  UploadRequestContentType = "image/png"
	Imagewebp UploadRequestContentType = "image/webp"
)

// Valid indicates whether the value is a known member of the UploadRequestContentType enum.
func (e UploadRequestContentType) Valid() bool {
	switch e {
	case Imageheic:
		return true
	case Imagejpeg:
		return true
	case Imagepng:
		return true
	case Imagewebp:
		return true
	default:
		return false
	}
}

// Defines values for UploadRequestKind.
const (
	UploadRequestKindLogo  UploadRequestKind = "logo"
	UploadRequestKindPhoto UploadRequestKind = "photo"
)

// Valid indicates whether the value is a known member of the UploadRequestKind enum.
func (e UploadRequestKind) Valid() bool {
	switch e {
	case UploadRequestKindLogo:
		return true
	case UploadRequestKindPhoto:
		return true
	default:
		return false
	}
}

// Defines values for UploadTicketMethod.
const (
	PUT UploadTicketMethod = "PUT"
)

// Valid indicates whether the value is a known member of the UploadTicketMethod enum.
func (e UploadTicketMethod) Valid() bool {
	switch e {
	case PUT:
		return true
	default:
		return false
	}
}

// Account An account as the signed-in user sees it, with their role in it.
type Account struct {
	CreatedAt time.Time          `json:"createdAt"`
	Id        openapi_types.UUID `json:"id"`
	Name      string             `json:"name"`

	// PropertyIds The properties this member is limited to. Empty means every property.
	PropertyIds    []openapi_types.UUID `json:"propertyIds"`
	Role           Role                 `json:"role"`
	Status         AccountStatus        `json:"status"`
	TrialStartedAt time.Time            `json:"trialStartedAt"`
}

// AccountList defines model for AccountList.
type AccountList struct {
	Items []Account `json:"items"`
}

// AccountStatus defines model for AccountStatus.
type AccountStatus string

// AuthTokens defines model for AuthTokens.
type AuthTokens struct {
	AccessToken           string    `json:"accessToken"`
	AccessTokenExpiresAt  time.Time `json:"accessTokenExpiresAt"`
	RefreshToken          string    `json:"refreshToken"`
	RefreshTokenExpiresAt time.Time `json:"refreshTokenExpiresAt"`
}

// BankDetails defines model for BankDetails.
type BankDetails struct {
	AccountName string `json:"accountName"`

	// AccountNumber Encrypted at rest. Hidden from caretakers.
	AccountNumber  string `json:"accountNumber"`
	BankName       string `json:"bankName"`
	CancelIfUnpaid bool   `json:"cancelIfUnpaid"`
	Enabled        bool   `json:"enabled"`
	PayWithinHours int    `json:"payWithinHours"`
}

// BookingSettings defines model for BookingSettings.
type BookingSettings struct {
	DisplayCurrencies []BookingSettingsDisplayCurrencies `json:"displayCurrencies"`
	HoldMinutes       int                                `json:"holdMinutes"`
	Mode              BookingSettingsMode                `json:"mode"`
	ReplyHours        int                                `json:"replyHours"`
}

// BookingSettingsDisplayCurrencies defines model for BookingSettings.DisplayCurrencies.
type BookingSettingsDisplayCurrencies string

// BookingSettingsMode defines model for BookingSettings.Mode.
type BookingSettingsMode string

// BookingType Whether guests book the whole place or individual rooms.
type BookingType string

// Branding defines model for Branding.
type Branding struct {
	// Color Example: #09090b
	Color   string  `json:"color"`
	LogoKey *string `json:"logoKey,omitempty"`
	LogoUrl *string `json:"logoUrl,omitempty"`
}

// BrandingInput defines model for BrandingInput.
type BrandingInput struct {
	Color string `json:"color"`

	// LogoKey A key from /v1/uploads, or the current logo's. Leave out to remove the logo.
	LogoKey *string `json:"logoKey,omitempty"`
}

// Charge defines model for Charge.
type Charge struct {
	// Amount A whole percent, or minor units for fixed charges.
	Amount  int64              `json:"amount"`
	Enabled bool               `json:"enabled"`
	Id      openapi_types.UUID `json:"id"`
	Kind    ChargeKind         `json:"kind"`
	Name    string             `json:"name"`
	Note    *string            `json:"note,omitempty"`
	Per     ChargePer          `json:"per"`
}

// ChargePer defines model for Charge.Per.
type ChargePer string

// ChargeInput defines model for ChargeInput.
type ChargeInput struct {
	Amount  int64          `json:"amount"`
	Enabled bool           `json:"enabled"`
	Id      *string        `json:"id,omitempty"`
	Kind    ChargeKind     `json:"kind"`
	Name    string         `json:"name"`
	Note    *string        `json:"note,omitempty"`
	Per     ChargeInputPer `json:"per"`
}

// ChargeInputPer defines model for ChargeInput.Per.
type ChargeInputPer string

// ChargeKind defines model for ChargeKind.
type ChargeKind string

// Clock Example: 14:00
type Clock = string

// Currency defines model for Currency.
type Currency string

// Day Example: 2026-12-01
type Day = openapi_types.Date

// Error defines model for Error.
type Error struct {
	// Code Example: slug_taken
	Code string `json:"code"`

	// Field The request field the error is about, when there is one.
	//
	// Example: slug
	Field *string `json:"field,omitempty"`

	// Message Example: That booking page address is already taken.
	Message string `json:"message"`

	// RetryAfter Seconds to wait before retrying, on 429 responses.
	RetryAfter *int `json:"retryAfter,omitempty"`
}

// Extra defines model for Extra.
type Extra struct {
	Enabled   bool               `json:"enabled"`
	Id        openapi_types.UUID `json:"id"`
	Name      string             `json:"name"`
	OnRequest bool               `json:"onRequest"`
	Per       ExtraPer           `json:"per"`

	// Price An amount in minor units of the property's currency.
	Price Money `json:"price"`
}

// ExtraGuest A charge per guest per night above the included guests. Amount 0 is off.
type ExtraGuest struct {
	Above int `json:"above"`

	// Amount An amount in minor units of the property's currency.
	Amount Money `json:"amount"`
}

// ExtraInput defines model for ExtraInput.
type ExtraInput struct {
	Enabled   bool     `json:"enabled"`
	Id        *string  `json:"id,omitempty"`
	Name      string   `json:"name"`
	OnRequest bool     `json:"onRequest"`
	Per       ExtraPer `json:"per"`

	// Price An amount in minor units of the property's currency.
	Price Money `json:"price"`
}

// ExtraPer defines model for ExtraPer.
type ExtraPer string

// Health defines model for Health.
type Health struct {
	Database HealthDatabase `json:"database"`
	Status   HealthStatus   `json:"status"`
}

// HealthDatabase defines model for Health.Database.
type HealthDatabase string

// HealthStatus defines model for Health.Status.
type HealthStatus string

// IcalChannel defines model for IcalChannel.
type IcalChannel string

// IcalFeed defines model for IcalFeed.
type IcalFeed struct {
	Channel  IcalChannel        `json:"channel"`
	Error    *string            `json:"error,omitempty"`
	Id       openapi_types.UUID `json:"id"`
	LastSync *time.Time         `json:"lastSync,omitempty"`

	// Status Pending until the import worker has read the link.
	Status IcalFeedStatus `json:"status"`

	// Upcoming Imported stays from today on.
	Upcoming int    `json:"upcoming"`
	Url      string `json:"url"`
}

// IcalFeedStatus Pending until the import worker has read the link.
type IcalFeedStatus string

// IcalFeedInput defines model for IcalFeedInput.
type IcalFeedInput struct {
	Channel IcalChannel `json:"channel"`
	Id      *string     `json:"id,omitempty"`
	Url     string      `json:"url"`
}

// Language defines model for Language.
type Language string

// LengthDiscount defines model for LengthDiscount.
type LengthDiscount struct {
	Nights  int `json:"nights"`
	Percent int `json:"percent"`
}

// Me defines model for Me.
type Me struct {
	Accounts []Account `json:"accounts"`
	User     User      `json:"user"`
}

// Money An amount in minor units of the property's currency.
type Money = int64

// MonthDay Month and day, repeating every year.
//
// Example: 12-15
type MonthDay = string

// NewAccount defines model for NewAccount.
type NewAccount struct {
	// Name Example: Kingfisher Villa
	Name string `json:"name"`
}

// NewProperty defines model for NewProperty.
type NewProperty struct {
	// BaseRate Nightly rate in minor units for the one unit a quick start gets. Required without setup.units.
	//
	// Example: 18000
	BaseRate *int64 `json:"baseRate,omitempty"`

	// BookingType Whether guests book the whole place or individual rooms.
	BookingType BookingType `json:"bookingType"`
	Currency    Currency    `json:"currency"`

	// Location Example: Unawatuna, Galle
	Location *string `json:"location,omitempty"`

	// Name Example: Kingfisher Villa
	Name string `json:"name"`

	// Setup Sections to change. Absent sections stay as they are; lists replace the whole list.
	Setup *PropertyPatch `json:"setup,omitempty"`

	// Slug Lowercase subdomain label used for the booking page, for example "kingfisher" in kingfisher.staykey.direct.
	//
	// Example: kingfisher
	Slug *Slug `json:"slug,omitempty"`
}

// OtpRequest defines model for OtpRequest.
type OtpRequest struct {
	// Phone Phone number with its country code. Returned in E.164, for example +94771234567.
	//
	// Example: +94771234567
	Phone Phone `json:"phone"`
}

// OtpSent defines model for OtpSent.
type OtpSent struct {
	// DevCode The code itself. Development servers only, so test devices can sign in.
	DevCode   *string   `json:"devCode,omitempty"`
	ExpiresAt time.Time `json:"expiresAt"`

	// Phone Phone number with its country code. Returned in E.164, for example +94771234567.
	//
	// Example: +94771234567
	Phone Phone `json:"phone"`

	// ResendAfter Seconds before another code can be requested.
	//
	// Example: 30
	ResendAfter int `json:"resendAfter"`
}

// PaymentSettings defines model for PaymentSettings.
type PaymentSettings struct {
	AtProperty bool        `json:"atProperty"`
	Bank       BankDetails `json:"bank"`

	// Cards The app can apply (pending) or withdraw (off); "on" comes from PayHere's approval.
	Cards PaymentSettingsCards `json:"cards"`
}

// PaymentSettingsCards The app can apply (pending) or withdraw (off); "on" comes from PayHere's approval.
type PaymentSettingsCards string

// Phone Phone number with its country code. Returned in E.164, for example +94771234567.
//
// Example: +94771234567
type Phone = string

// Photo defines model for Photo.
type Photo struct {
	Caption string             `json:"caption"`
	Id      openapi_types.UUID `json:"id"`
	Key     string             `json:"key"`
	Url     string             `json:"url"`
}

// PhotoInput defines model for PhotoInput.
type PhotoInput struct {
	Caption *string `json:"caption,omitempty"`

	// Key The key from /v1/uploads, or of a photo the property already has.
	Key string `json:"key"`
}

// Policy defines model for Policy.
type Policy string

// Promo defines model for Promo.
type Promo struct {
	Amount int64  `json:"amount"`
	Code   string `json:"code"`

	// From Example: 2026-12-01
	From      *Day               `json:"from,omitempty"`
	Id        openapi_types.UUID `json:"id"`
	Kind      ChargeKind         `json:"kind"`
	Limit     *int               `json:"limit,omitempty"`
	MinNights *int               `json:"minNights,omitempty"`
	Note      *string            `json:"note,omitempty"`

	// To Example: 2026-12-01
	To *Day `json:"to,omitempty"`

	// Used Bookings that used the code. Kept by the server.
	Used int `json:"used"`
}

// PromoInput defines model for PromoInput.
type PromoInput struct {
	Amount int64 `json:"amount"`

	// Code Example: MONSOON10
	Code string `json:"code"`

	// From Example: 2026-12-01
	From      *Day       `json:"from,omitempty"`
	Id        *string    `json:"id,omitempty"`
	Kind      ChargeKind `json:"kind"`
	Limit     *int       `json:"limit,omitempty"`
	MinNights *int       `json:"minNights,omitempty"`
	Note      *string    `json:"note,omitempty"`

	// To Example: 2026-12-01
	To *Day `json:"to,omitempty"`
}

// Property A property with its full setup, as owners and managers see it.
type Property struct {
	Amenities      []string `json:"amenities"`
	BalanceDueDays int      `json:"balanceDueDays"`

	// BaseRate The lowest unit rate, in minor units.
	BaseRate int64           `json:"baseRate"`
	Booking  BookingSettings `json:"booking"`

	// BookingPageUrl Example: https://kingfisher.staykey.direct
	BookingPageUrl string `json:"bookingPageUrl"`

	// BookingType Whether guests book the whole place or individual rooms.
	BookingType BookingType `json:"bookingType"`
	Branding    Branding    `json:"branding"`
	Charges     []Charge    `json:"charges"`

	// CheckIn Example: 14:00
	CheckIn Clock `json:"checkIn"`

	// CheckOut Example: 14:00
	CheckOut       Clock     `json:"checkOut"`
	CreatedAt      time.Time `json:"createdAt"`
	Currency       Currency  `json:"currency"`
	DepositPercent int       `json:"depositPercent"`
	Description    string    `json:"description"`

	// ExtraGuest A charge per guest per night above the included guests. Amount 0 is off.
	ExtraGuest ExtraGuest `json:"extraGuest"`
	Extras     []Extra    `json:"extras"`
	HouseRules []string   `json:"houseRules"`

	// IcalExportToken Secret part of the calendar export link for OTAs.
	IcalExportToken string             `json:"icalExportToken"`
	IcalFeeds       []IcalFeed         `json:"icalFeeds"`
	Id              openapi_types.UUID `json:"id"`
	LengthDiscounts []LengthDiscount   `json:"lengthDiscounts"`
	Location        *string            `json:"location,omitempty"`
	Name            string             `json:"name"`
	Payments        PaymentSettings    `json:"payments"`

	// Photos In display order; the first is the cover.
	Photos  []Photo   `json:"photos"`
	Policy  Policy    `json:"policy"`
	Promos  []Promo   `json:"promos"`
	Rules   StayRules `json:"rules"`
	Seasons []Season  `json:"seasons"`

	// Slug Lowercase subdomain label used for the booking page, for example "kingfisher" in kingfisher.staykey.direct.
	//
	// Example: kingfisher
	Slug Slug `json:"slug"`

	// TimeZone Example: Asia/Colombo
	TimeZone string `json:"timeZone"`
	Units    []Unit `json:"units"`
}

// PropertyList defines model for PropertyList.
type PropertyList struct {
	Items []Property `json:"items"`
}

// PropertyPatch Sections to change. Absent sections stay as they are; lists replace the whole list.
type PropertyPatch struct {
	Amenities      *[]string        `json:"amenities,omitempty"`
	BalanceDueDays *int             `json:"balanceDueDays,omitempty"`
	Booking        *BookingSettings `json:"booking,omitempty"`

	// BookingType Whether guests book the whole place or individual rooms.
	BookingType *BookingType   `json:"bookingType,omitempty"`
	Branding    *BrandingInput `json:"branding,omitempty"`
	Charges     *[]ChargeInput `json:"charges,omitempty"`

	// CheckIn Example: 14:00
	CheckIn *Clock `json:"checkIn,omitempty"`

	// CheckOut Example: 14:00
	CheckOut       *Clock  `json:"checkOut,omitempty"`
	DepositPercent *int    `json:"depositPercent,omitempty"`
	Description    *string `json:"description,omitempty"`

	// ExtraGuest A charge per guest per night above the included guests. Amount 0 is off.
	ExtraGuest      *ExtraGuest       `json:"extraGuest,omitempty"`
	Extras          *[]ExtraInput     `json:"extras,omitempty"`
	HouseRules      *[]string         `json:"houseRules,omitempty"`
	IcalFeeds       *[]IcalFeedInput  `json:"icalFeeds,omitempty"`
	LengthDiscounts *[]LengthDiscount `json:"lengthDiscounts,omitempty"`
	Location        *string           `json:"location,omitempty"`
	Name            *string           `json:"name,omitempty"`
	Payments        *PaymentSettings  `json:"payments,omitempty"`
	Photos          *[]PhotoInput     `json:"photos,omitempty"`
	Policy          *Policy           `json:"policy,omitempty"`
	Promos          *[]PromoInput     `json:"promos,omitempty"`
	Rules           *StayRules        `json:"rules,omitempty"`
	Seasons         *[]SeasonInput    `json:"seasons,omitempty"`
	Units           *[]UnitInput      `json:"units,omitempty"`
}

// PublicProperty defines model for PublicProperty.
type PublicProperty struct {
	BaseRate int64 `json:"baseRate"`

	// BookingType Whether guests book the whole place or individual rooms.
	BookingType BookingType `json:"bookingType"`
	Currency    Currency    `json:"currency"`
	Location    *string     `json:"location,omitempty"`
	Name        string      `json:"name"`

	// Slug Lowercase subdomain label used for the booking page, for example "kingfisher" in kingfisher.staykey.direct.
	//
	// Example: kingfisher
	Slug Slug `json:"slug"`
}

// RefreshRequest defines model for RefreshRequest.
type RefreshRequest struct {
	RefreshToken string `json:"refreshToken"`
}

// Role defines model for Role.
type Role string

// Season defines model for Season.
type Season struct {
	// End Month and day, repeating every year.
	//
	// Example: 12-15
	End       MonthDay           `json:"end"`
	Id        openapi_types.UUID `json:"id"`
	MinNights *int               `json:"minNights,omitempty"`
	Name      string             `json:"name"`

	// Prices Nightly price per unit id.
	Prices map[string]int64 `json:"prices"`

	// Start Month and day, repeating every year.
	//
	// Example: 12-15
	Start MonthDay `json:"start"`
}

// SeasonInput defines model for SeasonInput.
type SeasonInput struct {
	// End Month and day, repeating every year.
	//
	// Example: 12-15
	End       MonthDay `json:"end"`
	Id        *string  `json:"id,omitempty"`
	MinNights *int     `json:"minNights,omitempty"`
	Name      string   `json:"name"`

	// Prices Nightly price per unit id, or per new unit's id from the same request.
	Prices map[string]int64 `json:"prices"`

	// Start Month and day, repeating every year.
	//
	// Example: 12-15
	Start MonthDay `json:"start"`
}

// SignIn defines model for SignIn.
type SignIn struct {
	Accounts []Account `json:"accounts"`

	// NewUser True when this sign-in created the user.
	NewUser bool       `json:"newUser"`
	Tokens  AuthTokens `json:"tokens"`
	User    User       `json:"user"`
}

// Slug Lowercase subdomain label used for the booking page, for example "kingfisher" in kingfisher.staykey.direct.
//
// Example: kingfisher
type Slug = string

// StayRules defines model for StayRules.
type StayRules struct {
	// ClosedArrival Weekdays guests can't arrive on, 0 for Sunday.
	ClosedArrival []int `json:"closedArrival"`
	MaxNights     int   `json:"maxNights"`
	MinNights     int   `json:"minNights"`

	// SameDayCutoff Hour until which same-day arrivals can book. Null turns them off.
	SameDayCutoff *int `json:"sameDayCutoff"`
	WindowMonths  int  `json:"windowMonths"`
}

// Unit defines model for Unit.
type Unit struct {
	Beds string             `json:"beds"`
	Id   openapi_types.UUID `json:"id"`

	// LinkedUnitIds Rooms a whole-house unit books together.
	LinkedUnitIds []openapi_types.UUID `json:"linkedUnitIds"`
	Name          string               `json:"name"`

	// Rate An amount in minor units of the property's currency.
	Rate   Money `json:"rate"`
	Sleeps int   `json:"sleeps"`

	// WeekendRate An amount in minor units of the property's currency.
	WeekendRate *Money `json:"weekendRate,omitempty"`
}

// UnitInput defines model for UnitInput.
type UnitInput struct {
	Beds *string `json:"beds,omitempty"`

	// Id An existing unit's id, or any text unique in the request for a new unit.
	Id            string    `json:"id"`
	LinkedUnitIds *[]string `json:"linkedUnitIds,omitempty"`
	Name          string    `json:"name"`

	// Rate An amount in minor units of the property's currency.
	Rate   Money `json:"rate"`
	Sleeps int   `json:"sleeps"`

	// WeekendRate An amount in minor units of the property's currency.
	WeekendRate *Money `json:"weekendRate,omitempty"`
}

// UploadRequest defines model for UploadRequest.
type UploadRequest struct {
	ContentType UploadRequestContentType `json:"contentType"`
	Kind        UploadRequestKind        `json:"kind"`

	// Size Exact size in bytes. Photos up to 15 MB, logos up to 5 MB.
	Size int64 `json:"size"`
}

// UploadRequestContentType defines model for UploadRequest.ContentType.
type UploadRequestContentType string

// UploadRequestKind defines model for UploadRequest.Kind.
type UploadRequestKind string

// UploadTicket defines model for UploadTicket.
type UploadTicket struct {
	ExpiresAt time.Time `json:"expiresAt"`

	// Headers Headers to send with the upload, exactly as given.
	Headers   map[string]string  `json:"headers"`
	Key       string             `json:"key"`
	Method    UploadTicketMethod `json:"method"`
	UploadUrl string             `json:"uploadUrl"`

	// Url Where the file is served once uploaded.
	Url string `json:"url"`
}

// UploadTicketMethod defines model for UploadTicket.Method.
type UploadTicketMethod string

// User defines model for User.
type User struct {
	CreatedAt time.Time          `json:"createdAt"`
	Email     *string            `json:"email,omitempty"`
	Id        openapi_types.UUID `json:"id"`
	Language  Language           `json:"language"`
	Name      string             `json:"name"`

	// Phone Phone number with its country code. Returned in E.164, for example +94771234567.
	//
	// Example: +94771234567
	Phone Phone `json:"phone"`
}

// UserPatch defines model for UserPatch.
type UserPatch struct {
	// Email An empty string clears the email.
	Email    *string   `json:"email,omitempty"`
	Language *Language `json:"language,omitempty"`
	Name     *string   `json:"name,omitempty"`
}

// VerifyRequest defines model for VerifyRequest.
type VerifyRequest struct {
	// Code Example: 482913
	Code string `json:"code"`

	// DeviceName Shown in the list of signed-in devices.
	//
	// Example: Nimal's iPhone
	DeviceName *string `json:"deviceName,omitempty"`

	// Phone Phone number with its country code. Returned in E.164, for example +94771234567.
	//
	// Example: +94771234567
	Phone Phone `json:"phone"`
}

// BadRequest defines model for BadRequest.
type BadRequest = Error

// Forbidden defines model for Forbidden.
type Forbidden = Error

// NotFound defines model for NotFound.
type NotFound = Error

// TooManyRequests defines model for TooManyRequests.
type TooManyRequests = Error

// Unauthorized defines model for Unauthorized.
type Unauthorized = Error

// CreateAccountJSONRequestBody defines body for CreateAccount for application/json ContentType.
type CreateAccountJSONRequestBody = NewAccount

// LogoutJSONRequestBody defines body for Logout for application/json ContentType.
type LogoutJSONRequestBody = RefreshRequest

// RequestOtpJSONRequestBody defines body for RequestOtp for application/json ContentType.
type RequestOtpJSONRequestBody = OtpRequest

// RefreshSessionJSONRequestBody defines body for RefreshSession for application/json ContentType.
type RefreshSessionJSONRequestBody = RefreshRequest

// VerifyOtpJSONRequestBody defines body for VerifyOtp for application/json ContentType.
type VerifyOtpJSONRequestBody = VerifyRequest

// UpdateMeJSONRequestBody defines body for UpdateMe for application/json ContentType.
type UpdateMeJSONRequestBody = UserPatch

// CreatePropertyJSONRequestBody defines body for CreateProperty for application/json ContentType.
type CreatePropertyJSONRequestBody = NewProperty

// UpdatePropertyJSONRequestBody defines body for UpdateProperty for application/json ContentType.
type UpdatePropertyJSONRequestBody = PropertyPatch

// CreateUploadJSONRequestBody defines body for CreateUpload for application/json ContentType.
type CreateUploadJSONRequestBody = UploadRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// GetHealth Service and database health
	// (GET /healthz)
	GetHealth(w http.ResponseWriter, r *http.Request)
	// ListAccounts Accounts the signed-in user belongs to
	// (GET /v1/accounts)
	ListAccounts(w http.ResponseWriter, r *http.Request)
	// CreateAccount Create an account with the signed-in user as its owner
	// (POST /v1/accounts)
	CreateAccount(w http.ResponseWriter, r *http.Request)
	// Logout End the session behind a refresh token
	// (POST /v1/auth/logout)
	Logout(w http.ResponseWriter, r *http.Request)
	// RequestOtp Text a 6-digit sign-in code to a phone number
	// (POST /v1/auth/otp)
	RequestOtp(w http.ResponseWriter, r *http.Request)
	// RefreshSession Exchange a refresh token for new tokens
	// (POST /v1/auth/refresh)
	RefreshSession(w http.ResponseWriter, r *http.Request)
	// VerifyOtp Check a code and sign in, creating the user on first sign-in
	// (POST /v1/auth/verify)
	VerifyOtp(w http.ResponseWriter, r *http.Request)
	// GetMe The signed-in user and the accounts they belong to
	// (GET /v1/me)
	GetMe(w http.ResponseWriter, r *http.Request)
	// UpdateMe Update the signed-in user's profile
	// (PATCH /v1/me)
	UpdateMe(w http.ResponseWriter, r *http.Request)
	// ListProperties List the properties the caller can see
	// (GET /v1/properties)
	ListProperties(w http.ResponseWriter, r *http.Request)
	// CreateProperty Create a property and its booking page address
	// (POST /v1/properties)
	CreateProperty(w http.ResponseWriter, r *http.Request)
	// GetProperty A property with its full setup
	// (GET /v1/properties/{id})
	GetProperty(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// UpdateProperty Change some of a property's setup
	// (PATCH /v1/properties/{id})
	UpdateProperty(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// GetPublicProperty Public details for a property's booking page
	// (GET /v1/public/properties/{slug})
	GetPublicProperty(w http.ResponseWriter, r *http.Request, slug Slug)
	// CreateUpload Get a link to upload a photo or logo
	// (POST /v1/uploads)
	CreateUpload(w http.ResponseWriter, r *http.Request)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetHealth operation middleware
func (siw *ServerInterfaceWrapper) GetHealth(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHealth(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListAccounts operation middleware
func (siw *ServerInterfaceWrapper) ListAccounts(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListAccounts(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateAccount operation middleware
func (siw *ServerInterfaceWrapper) CreateAccount(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateAccount(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Logout operation middleware
func (siw *ServerInterfaceWrapper) Logout(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Logout(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RequestOtp operation middleware
func (siw *ServerInterfaceWrapper) RequestOtp(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RequestOtp(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RefreshSession operation middleware
func (siw *ServerInterfaceWrapper) RefreshSession(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RefreshSession(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// VerifyOtp operation middleware
func (siw *ServerInterfaceWrapper) VerifyOtp(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.VerifyOtp(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetMe operation middleware
func (siw *ServerInterfaceWrapper) GetMe(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetMe(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateMe operation middleware
func (siw *ServerInterfaceWrapper) UpdateMe(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateMe(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListProperties operation middleware
func (siw *ServerInterfaceWrapper) ListProperties(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListProperties(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateProperty operation middleware
func (siw *ServerInterfaceWrapper) CreateProperty(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateProperty(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetProperty operation middleware
func (siw *ServerInterfaceWrapper) GetProperty(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetProperty(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateProperty operation middleware
func (siw *ServerInterfaceWrapper) UpdateProperty(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateProperty(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetPublicProperty operation middleware
func (siw *ServerInterfaceWrapper) GetPublicProperty(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "slug" -------------
	var slug Slug

	err = runtime.BindStyledParameterWithOptions("simple", "slug", r.PathValue("slug"), &slug, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "slug", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetPublicProperty(w, r, slug)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateUpload operation middleware
func (siw *ServerInterfaceWrapper) CreateUpload(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateUpload(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of [http.ServeMux].
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	http.Handler
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/healthz", wrapper.GetHealth)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/v1/auth/otp", wrapper.RequestOtp)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/v1/auth/verify", wrapper.VerifyOtp)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/v1/auth/refresh", wrapper.RefreshSession)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/v1/auth/logout", wrapper.Logout)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/v1/me", wrapper.GetMe)
	m.HandleFunc(http.MethodPatch+" "+options.BaseURL+"/v1/me", wrapper.UpdateMe)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/v1/accounts", wrapper.ListAccounts)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/v1/accounts", wrapper.CreateAccount)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/v1/properties", wrapper.ListProperties)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/v1/properties", wrapper.CreateProperty)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/v1/properties/{id}", wrapper.GetProperty)
	m.HandleFunc(http.MethodPatch+" "+options.BaseURL+"/v1/properties/{id}", wrapper.UpdateProperty)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/v1/uploads", wrapper.CreateUpload)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/v1/public/properties/{slug}", wrapper.GetPublicProperty)

	return m
}

type BadRequestJSONResponse Error

type ForbiddenJSONResponse Error

type NotFoundJSONResponse Error

type TooManyRequestsResponseHeaders struct {
	RetryAfter *int
}
type TooManyRequestsJSONResponse struct {
	Body Error

	Headers TooManyRequestsResponseHeaders
}

type UnauthorizedJSONResponse Error

type GetHealthRequestObject struct {
}

type GetHealthResponseObject interface {
	VisitGetHealthResponse(w http.ResponseWriter) error
}

type GetHealth200JSONResponse Health

func (response GetHealth200JSONResponse) VisitGetHealthResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListAccountsRequestObject struct {
}

type ListAccountsResponseObject interface {
	VisitListAccountsResponse(w http.ResponseWriter) error
}

type ListAccounts200JSONResponse AccountList

func (response ListAccounts200JSONResponse) VisitListAccountsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListAccounts401JSONResponse struct{ UnauthorizedJSONResponse }

func (response ListAccounts401JSONResponse) VisitListAccountsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type CreateAccountRequestObject struct {
	Body *CreateAccountJSONRequestBody
}

type CreateAccountResponseObject interface {
	VisitCreateAccountResponse(w http.ResponseWriter) error
}

type CreateAccount201JSONResponse Account

func (response CreateAccount201JSONResponse) VisitCreateAccountResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type CreateAccount400JSONResponse struct{ BadRequestJSONResponse }

func (response CreateAccount400JSONResponse) VisitCreateAccountResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type CreateAccount401JSONResponse struct{ UnauthorizedJSONResponse }

func (response CreateAccount401JSONResponse) VisitCreateAccountResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type LogoutRequestObject struct {
	Body *LogoutJSONRequestBody
}

type LogoutResponseObject interface {
	VisitLogoutResponse(w http.ResponseWriter) error
}

type Logout204Response struct {
}

func (response Logout204Response) VisitLogoutResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type RequestOtpRequestObject struct {
	Body *RequestOtpJSONRequestBody
}

type RequestOtpResponseObject interface {
	VisitRequestOtpResponse(w http.ResponseWriter) error
}

type RequestOtp200JSONResponse OtpSent

func (response RequestOtp200JSONResponse) VisitRequestOtpResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type RequestOtp400JSONResponse struct{ BadRequestJSONResponse }

func (response RequestOtp400JSONResponse) VisitRequestOtpResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type RequestOtp429JSONResponse struct{ TooManyRequestsJSONResponse }

func (response RequestOtp429JSONResponse) VisitRequestOtpResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.RetryAfter != nil {
		w.Header().Set("Retry-After", fmt.Sprint(*response.Headers.RetryAfter))
	}
	w.WriteHeader(429)
	_, err := buf.WriteTo(w)
	return err
}

type RefreshSessionRequestObject struct {
	Body *RefreshSessionJSONRequestBody
}

type RefreshSessionResponseObject interface {
	VisitRefreshSessionResponse(w http.ResponseWriter) error
}

type RefreshSession200JSONResponse AuthTokens

func (response RefreshSession200JSONResponse) VisitRefreshSessionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type RefreshSession401JSONResponse struct{ UnauthorizedJSONResponse }

func (response RefreshSession401JSONResponse) VisitRefreshSessionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type VerifyOtpRequestObject struct {
	Body *VerifyOtpJSONRequestBody
}

type VerifyOtpResponseObject interface {
	VisitVerifyOtpResponse(w http.ResponseWriter) error
}

type VerifyOtp200JSONResponse SignIn

func (response VerifyOtp200JSONResponse) VisitVerifyOtpResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type VerifyOtp400JSONResponse Error

func (response VerifyOtp400JSONResponse) VisitVerifyOtpResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type GetMeRequestObject struct {
}

type GetMeResponseObject interface {
	VisitGetMeResponse(w http.ResponseWriter) error
}

type GetMe200JSONResponse Me

func (response GetMe200JSONResponse) VisitGetMeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetMe401JSONResponse struct{ UnauthorizedJSONResponse }

func (response GetMe401JSONResponse) VisitGetMeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateMeRequestObject struct {
	Body *UpdateMeJSONRequestBody
}

type UpdateMeResponseObject interface {
	VisitUpdateMeResponse(w http.ResponseWriter) error
}

type UpdateMe200JSONResponse User

func (response UpdateMe200JSONResponse) VisitUpdateMeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateMe400JSONResponse struct{ BadRequestJSONResponse }

func (response UpdateMe400JSONResponse) VisitUpdateMeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateMe401JSONResponse struct{ UnauthorizedJSONResponse }

func (response UpdateMe401JSONResponse) VisitUpdateMeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type ListPropertiesRequestObject struct {
}

type ListPropertiesResponseObject interface {
	VisitListPropertiesResponse(w http.ResponseWriter) error
}

type ListProperties200JSONResponse PropertyList

func (response ListProperties200JSONResponse) VisitListPropertiesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListProperties400JSONResponse struct{ BadRequestJSONResponse }

func (response ListProperties400JSONResponse) VisitListPropertiesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type ListProperties401JSONResponse struct{ UnauthorizedJSONResponse }

func (response ListProperties401JSONResponse) VisitListPropertiesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type ListProperties404JSONResponse struct{ NotFoundJSONResponse }

func (response ListProperties404JSONResponse) VisitListPropertiesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type CreatePropertyRequestObject struct {
	Body *CreatePropertyJSONRequestBody
}

type CreatePropertyResponseObject interface {
	VisitCreatePropertyResponse(w http.ResponseWriter) error
}

type CreateProperty201JSONResponse Property

func (response CreateProperty201JSONResponse) VisitCreatePropertyResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type CreateProperty400JSONResponse struct{ BadRequestJSONResponse }

func (response CreateProperty400JSONResponse) VisitCreatePropertyResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type CreateProperty401JSONResponse struct{ UnauthorizedJSONResponse }

func (response CreateProperty401JSONResponse) VisitCreatePropertyResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type CreateProperty403JSONResponse struct{ ForbiddenJSONResponse }

func (response CreateProperty403JSONResponse) VisitCreatePropertyResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type CreateProperty404JSONResponse struct{ NotFoundJSONResponse }

func (response CreateProperty404JSONResponse) VisitCreatePropertyResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type CreateProperty409JSONResponse Error

func (response CreateProperty409JSONResponse) VisitCreatePropertyResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type GetPropertyRequestObject struct {
	Id openapi_types.UUID `json:"id"`
}

type GetPropertyResponseObject interface {
	VisitGetPropertyResponse(w http.ResponseWriter) error
}

type GetProperty200JSONResponse Property

func (response GetProperty200JSONResponse) VisitGetPropertyResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetProperty401JSONResponse struct{ UnauthorizedJSONResponse }

func (response GetProperty401JSONResponse) VisitGetPropertyResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type GetProperty404JSONResponse struct{ NotFoundJSONResponse }

func (response GetProperty404JSONResponse) VisitGetPropertyResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type UpdatePropertyRequestObject struct {
	Id   openapi_types.UUID `json:"id"`
	Body *UpdatePropertyJSONRequestBody
}

type UpdatePropertyResponseObject interface {
	VisitUpdatePropertyResponse(w http.ResponseWriter) error
}

type UpdateProperty200JSONResponse Property

func (response UpdateProperty200JSONResponse) VisitUpdatePropertyResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateProperty400JSONResponse struct{ BadRequestJSONResponse }

func (response UpdateProperty400JSONResponse) VisitUpdatePropertyResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateProperty401JSONResponse struct{ UnauthorizedJSONResponse }

func (response UpdateProperty401JSONResponse) VisitUpdatePropertyResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateProperty403JSONResponse struct{ ForbiddenJSONResponse }

func (response UpdateProperty403JSONResponse) VisitUpdatePropertyResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateProperty404JSONResponse struct{ NotFoundJSONResponse }

func (response UpdateProperty404JSONResponse) VisitUpdatePropertyResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type GetPublicPropertyRequestObject struct {
	Slug Slug `json:"slug"`
}

type GetPublicPropertyResponseObject interface {
	VisitGetPublicPropertyResponse(w http.ResponseWriter) error
}

type GetPublicProperty200JSONResponse PublicProperty

func (response GetPublicProperty200JSONResponse) VisitGetPublicPropertyResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetPublicProperty404JSONResponse struct{ NotFoundJSONResponse }

func (response GetPublicProperty404JSONResponse) VisitGetPublicPropertyResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type CreateUploadRequestObject struct {
	Body *CreateUploadJSONRequestBody
}

type CreateUploadResponseObject interface {
	VisitCreateUploadResponse(w http.ResponseWriter) error
}

type CreateUpload201JSONResponse UploadTicket

func (response CreateUpload201JSONResponse) VisitCreateUploadResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type CreateUpload400JSONResponse struct{ BadRequestJSONResponse }

func (response CreateUpload400JSONResponse) VisitCreateUploadResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type CreateUpload401JSONResponse struct{ UnauthorizedJSONResponse }

func (response CreateUpload401JSONResponse) VisitCreateUploadResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type CreateUpload403JSONResponse struct{ ForbiddenJSONResponse }

func (response CreateUpload403JSONResponse) VisitCreateUploadResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type CreateUpload404JSONResponse struct{ NotFoundJSONResponse }

func (response CreateUpload404JSONResponse) VisitCreateUploadResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// GetHealth Service and database health
	// (GET /healthz)
	GetHealth(ctx context.Context, request GetHealthRequestObject) (GetHealthResponseObject, error)
	// ListAccounts Accounts the signed-in user belongs to
	// (GET /v1/accounts)
	ListAccounts(ctx context.Context, request ListAccountsRequestObject) (ListAccountsResponseObject, error)
	// CreateAccount Create an account with the signed-in user as its owner
	// (POST /v1/accounts)
	CreateAccount(ctx context.Context, request CreateAccountRequestObject) (CreateAccountResponseObject, error)
	// Logout End the session behind a refresh token
	// (POST /v1/auth/logout)
	Logout(ctx context.Context, request LogoutRequestObject) (LogoutResponseObject, error)
	// RequestOtp Text a 6-digit sign-in code to a phone number
	// (POST /v1/auth/otp)
	RequestOtp(ctx context.Context, request RequestOtpRequestObject) (RequestOtpResponseObject, error)
	// RefreshSession Exchange a refresh token for new tokens
	// (POST /v1/auth/refresh)
	RefreshSession(ctx context.Context, request RefreshSessionRequestObject) (RefreshSessionResponseObject, error)
	// VerifyOtp Check a code and sign in, creating the user on first sign-in
	// (POST /v1/auth/verify)
	VerifyOtp(ctx context.Context, request VerifyOtpRequestObject) (VerifyOtpResponseObject, error)
	// GetMe The signed-in user and the accounts they belong to
	// (GET /v1/me)
	GetMe(ctx context.Context, request GetMeRequestObject) (GetMeResponseObject, error)
	// UpdateMe Update the signed-in user's profile
	// (PATCH /v1/me)
	UpdateMe(ctx context.Context, request UpdateMeRequestObject) (UpdateMeResponseObject, error)
	// ListProperties List the properties the caller can see
	// (GET /v1/properties)
	ListProperties(ctx context.Context, request ListPropertiesRequestObject) (ListPropertiesResponseObject, error)
	// CreateProperty Create a property and its booking page address
	// (POST /v1/properties)
	CreateProperty(ctx context.Context, request CreatePropertyRequestObject) (CreatePropertyResponseObject, error)
	// GetProperty A property with its full setup
	// (GET /v1/properties/{id})
	GetProperty(ctx context.Context, request GetPropertyRequestObject) (GetPropertyResponseObject, error)
	// UpdateProperty Change some of a property's setup
	// (PATCH /v1/properties/{id})
	UpdateProperty(ctx context.Context, request UpdatePropertyRequestObject) (UpdatePropertyResponseObject, error)
	// GetPublicProperty Public details for a property's booking page
	// (GET /v1/public/properties/{slug})
	GetPublicProperty(ctx context.Context, request GetPublicPropertyRequestObject) (GetPublicPropertyResponseObject, error)
	// CreateUpload Get a link to upload a photo or logo
	// (POST /v1/uploads)
	CreateUpload(ctx context.Context, request CreateUploadRequestObject) (CreateUploadResponseObject, error)
}

type StrictHandlerFunc func(ctx context.Context, w http.ResponseWriter, r *http.Request, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	if options.RequestErrorHandlerFunc == nil {
		options.RequestErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	if options.ResponseErrorHandlerFunc == nil {
		options.ResponseErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		}
	}
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// GetHealth operation middleware
func (sh *strictHandler) GetHealth(w http.ResponseWriter, r *http.Request) {
	var request GetHealthRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetHealth(ctx, request.(GetHealthRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetHealth")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetHealthResponseObject); ok {
		if err := validResponse.VisitGetHealthResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListAccounts operation middleware
func (sh *strictHandler) ListAccounts(w http.ResponseWriter, r *http.Request) {
	var request ListAccountsRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListAccounts(ctx, request.(ListAccountsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListAccounts")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListAccountsResponseObject); ok {
		if err := validResponse.VisitListAccountsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateAccount operation middleware
func (sh *strictHandler) CreateAccount(w http.ResponseWriter, r *http.Request) {
	var request CreateAccountRequestObject

	var body CreateAccountJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateAccount(ctx, request.(CreateAccountRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateAccount")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateAccountResponseObject); ok {
		if err := validResponse.VisitCreateAccountResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Logout operation middleware
func (sh *strictHandler) Logout(w http.ResponseWriter, r *http.Request) {
	var request LogoutRequestObject

	var body LogoutJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.Logout(ctx, request.(LogoutRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Logout")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(LogoutResponseObject); ok {
		if err := validResponse.VisitLogoutResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// RequestOtp operation middleware
func (sh *strictHandler) RequestOtp(w http.ResponseWriter, r *http.Request) {
	var request RequestOtpRequestObject

	var body RequestOtpJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.RequestOtp(ctx, request.(RequestOtpRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "RequestOtp")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(RequestOtpResponseObject); ok {
		if err := validResponse.VisitRequestOtpResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// RefreshSession operation middleware
func (sh *strictHandler) RefreshSession(w http.ResponseWriter, r *http.Request) {
	var request RefreshSessionRequestObject

	var body RefreshSessionJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.RefreshSession(ctx, request.(RefreshSessionRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "RefreshSession")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(RefreshSessionResponseObject); ok {
		if err := validResponse.VisitRefreshSessionResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// VerifyOtp operation middleware
func (sh *strictHandler) VerifyOtp(w http.ResponseWriter, r *http.Request) {
	var request VerifyOtpRequestObject

	var body VerifyOtpJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.VerifyOtp(ctx, request.(VerifyOtpRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "VerifyOtp")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(VerifyOtpResponseObject); ok {
		if err := validResponse.VisitVerifyOtpResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetMe operation middleware
func (sh *strictHandler) GetMe(w http.ResponseWriter, r *http.Request) {
	var request GetMeRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetMe(ctx, request.(GetMeRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetMe")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetMeResponseObject); ok {
		if err := validResponse.VisitGetMeResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// UpdateMe operation middleware
func (sh *strictHandler) UpdateMe(w http.ResponseWriter, r *http.Request) {
	var request UpdateMeRequestObject

	var body UpdateMeJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.UpdateMe(ctx, request.(UpdateMeRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdateMe")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(UpdateMeResponseObject); ok {
		if err := validResponse.VisitUpdateMeResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListProperties operation middleware
func (sh *strictHandler) ListProperties(w http.ResponseWriter, r *http.Request) {
	var request ListPropertiesRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListProperties(ctx, request.(ListPropertiesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListProperties")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListPropertiesResponseObject); ok {
		if err := validResponse.VisitListPropertiesResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateProperty operation middleware
func (sh *strictHandler) CreateProperty(w http.ResponseWriter, r *http.Request) {
	var request CreatePropertyRequestObject

	var body CreatePropertyJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateProperty(ctx, request.(CreatePropertyRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateProperty")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreatePropertyResponseObject); ok {
		if err := validResponse.VisitCreatePropertyResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetProperty operation middleware
func (sh *strictHandler) GetProperty(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	var request GetPropertyRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetProperty(ctx, request.(GetPropertyRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetProperty")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetPropertyResponseObject); ok {
		if err := validResponse.VisitGetPropertyResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// UpdateProperty operation middleware
func (sh *strictHandler) UpdateProperty(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	var request UpdatePropertyRequestObject

	request.Id = id

	var body UpdatePropertyJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.UpdateProperty(ctx, request.(UpdatePropertyRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdateProperty")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(UpdatePropertyResponseObject); ok {
		if err := validResponse.VisitUpdatePropertyResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetPublicProperty operation middleware
func (sh *strictHandler) GetPublicProperty(w http.ResponseWriter, r *http.Request, slug Slug) {
	var request GetPublicPropertyRequestObject

	request.Slug = slug

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetPublicProperty(ctx, request.(GetPublicPropertyRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetPublicProperty")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetPublicPropertyResponseObject); ok {
		if err := validResponse.VisitGetPublicPropertyResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateUpload operation middleware
func (sh *strictHandler) CreateUpload(w http.ResponseWriter, r *http.Request) {
	var request CreateUploadRequestObject

	var body CreateUploadJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateUpload(ctx, request.(CreateUploadRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateUpload")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateUploadResponseObject); ok {
		if err := validResponse.VisitCreateUploadResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7H17c9s4kvhXQXG3apL60bLsOJnE+8evPElmxpfEccX27tXZvimIbElYkwAHAC1rcv7uV90AXxIoyc99",
	"1P0ViwSBRnej3418jxKVF0qCtCba/x5pMIWSBujHTzz9Br+XYCz+SpS0IOlPXhSZSLgVSm7/3SiJz0wy",
	"hZzjX3/WMI72oz9tN1Nvu7dm+6PWSke3t7dxlIJJtChwkmg/Op0C024xNuOGCXnNM5FGt3H0s9IjkaYg",
	"nweKhGcZ6B8M0yoDliowTCrLeJapGbNTYRCmI2V/VqVMnx6kI2XZmJa6jaNTpb5wOfdUMc+AEKVYzuW8",
	"oo0ZsG9g9ZzxsQXN7BSYLPMRaKbGzECiZIq0YxoHHeCYQRRHU+ApaAKXvt6iN13w7LyAaD8S0sIECJbb",
	"ODqTvLRTpcUfkD4P9XmSgDHMqiuQTBiWC2OEnMQVQ8YMbgqhIWVKMw3X6grSCKfys+PiB0miSgdld4ED",
	"ybh7x7gh5BkxkZBuCclKA5oZAMOEjdlM2CkOENqxoZBMWERloVUB2gp3QhMN3EJ6QGuNlc65jfajlFvY",
	"siKHKK7QaqwWcoIsJNLO2LIUaWiY5Dm0yNK88ADMD1OzvEHEYAMhnRaWA/GHMCwTubCQMqsG7GNe2DnL",
	"gUvD4Br0vPpujrsUFnKzEZz+Adeaz/E3YmsdA3zDMUgyy21p1o321Dxxg3FJLXh2Yrm+E+YRNvi9RNaJ",
	"9s8j2g0huYbDA99F8dJycYvol/UqavR3SCxC58H9LJzU7vJLjdf6jw12vozmxb3QZCuAOakRDbLM8RPa",
	"VBRHPLHiGvc80TzBfzNeGEDcJJnCPy4DND8o7fQUD6hZ3qE7v/Q2yL6t9x/pIJu7HB4NYw1m2j99e8Cd",
	"519Aa3srPYAvQNS3fog0P3F59QEsF1kYi0i3oz4hUL0n0b8sBj7KRM8LPOrcMg3GDtivpMHZWKucJVyD",
	"5VegzSCE5BGXV70rJ1wmkB2Oz2TBRdoaMlIqAy5xDEg+yqDnZcHnfxN2KuSvqnQqKec3Ike23HnzNo5y",
	"If2veFkndQlUrdMCOe6gbhFRS6sv7SdIKaWuhJycgLVCTgLUSoUpMj5/X2oNMlk86tWROzv5EMXRx7Nv",
	"URz98tNxFEcHZ/jk8AiffP70LXjWFuXrVGXpFyFLCwu42x22cPd6GXdxlKsU2gAJaSyXjomdlXkZPHJF",
	"Nl+m1Y+7dyIVrd2ZrLuVOIDEFbQ4peeLbP+3KdgpaDbBzRg2UuqKlPxsiiq8yHgCaDUImYprkZY8Y1qp",
	"nA5BhROQVmiCFN8EEfKT5jLFv5f4IFGZotMINzwvUA9Gfxq+G74bjkLHLFMT9QnmwVOG78501tXAWqwV",
	"WQ6CIOI81IeyKO0K0AtuLWgZ7Uf//afz4dY7vjU+2Pr58vub2z+v2cSCqcWuYO7Ezfb1znZZZIqnJkb8",
	"I0kSIrNl+P0PZsA+A78GpkrLrGIacnUNNA7fDx6w7fdTricQELB5j4VYMQvoBKQleHMhlWalFNawsdJs",
	"LG4gZQnNTMxTk0hI+2YvCp29lSJxQ5PwSsh0ncng9vtJOHel14iUyoZfFE6dVMfBWD6P4kiKydRGcTTp",
	"kRIrbCsCOq7w7RZo0NFPsh4+bej2OEj/10XyA/H7ye+zAsIzPHKzuOl82cD9PlPJVVe+7eztD4dR3BYb",
	"L86HO5coOi7/Z/d8uPXq8uX++XDrtXsUFCJe5s+XtSVqxbbODEH1gc+7MO0Od99s7exuDXeiuGv3hRZ3",
	"3mhAIKbQndZk5eQ3y52dtzTNWECWhh2yKqxCQ0iqAa6JHhkfqRK9zSlIfKEBHyoJpJI6K4fWzMEYPlkA",
	"83TKLak+ISes4BNgPE01GEPrZRp4Ome0jUHYwq4CB8ubOfHxBavYjAvLRjBWGlysgXx0Jdne7jtWB7EG",
	"0VrDIHGGQbWVEMN+vLGaL1PoMURq79lVshV5W57en+CVUQ6E+tgJokKLZK1X/EVJmK+UpW6a6ow3IK4+",
	"7wTIL9VeFtWdU2OsqMwm+otEETKn18JCJlmZQuqGmAE7IHHDhsSu4/FyYIS+7RiMr9r26TAkrhvZfnc0",
	"ufXqOXrx0KNW7qMp/vl55+Fsc7yBpqIISVH9PKJ3ITn9K/DMTgPeE7d8xE3HNSlxvlTNZHAmsxTOUFc4",
	"Hiaap0HdtYCYOuBTrx3CwGHCs/dTLiVk7bW40COJFr0Xssh1E5VyEtkFpAL/UijNg8DjrD8DpMuISJq1",
	"VtG6DRYaOZX+um+kMePGnsxlsnkUpsF/V5ocA7kYrJRWZE5w5IXSls2UvgLNptww1D/0KhPyqu15Fe7j",
	"KHbEdNsKIbAsEpV7/6u7/iGtBilDPjXO+bAq5XOm5CBoIZbOx9rAnK2I475pxQxrcPpYCInd53Xdi+I9",
	"8sjvJec3n0FO8KTtDIfDta5TZ1+hPXzmclJWZkbtJiMKRJA+bvUPwtRB+O6mSXrQX7U62A3RprJI20rk",
	"3fBOUQe/VDNXaH9foDf+9gih2jgqzXqBf2YC0NOHcQNLEHgS/MFEh1PRQnb8VzWmw1dFuH8w3hNP5kFH",
	"drXC/qKknX7ggfXpDeMyZSmfx0xDARyDZz7VMAeuuybuzu7WzusFP2J4voNOxM75cGv38uVW9ft8Z9e7",
	"F6/Q03gZdCmOYNbKAi0woFfczeqfhJyMhcHY0V9FlvEo7hwjH1qrf2/kmoWodQSzY4/5ZbBQD33jNhDX",
	"Ip2azZnmFhYJOvYBFSWBnjDOfi9FcoUyUFs2AZcydMBRWguDLAZsWQxohg4ddt6SyOjng50QH4y6QblV",
	"jN6O32E0ueX5rfS4q3EUcnJZxy4JzySfcVtKHrNfMIG8QMI3wxXW/6aM8LbLB7uBKQmx63ZT8cAxt8mU",
	"vkIHb81HJ1nZw2ldArSQGmLBr7ZoWaddDiymSq6l4DENWgTEfdqz4AmEjmEK1+9VGmB3KgJQKTBhDWTj",
	"AfsA15CpIgeJnKuvQRumZDaPmVHMgrEshWuRgGEJl5TSZSLs3cLdU053QQrixIBM1/jP3m/mkqxEt1eE",
	"fFTHCiDtHMtXw7WqzoHZ3mEXmBBpjvkccdqf2OC2La6WXRlMu6w98a08F+WPdF/imhcFoQErC+bshTcI",
	"XzKlSW6lms/YCzUev/wLu4iUvIhYonLwdt4xn/8KGn4w+LlW1zxrG5dqPCYroDYx5XongTYXt3FQQR/E",
	"ZcUmCyYxPq5KNHAXyNSMFJOeE+WpoKPUElIU7R8HO2/2YpLqnvrs/73b+/HHnd1Xe6/f/NhVmu03IdY9",
	"niqrAlYnLyr5eV+f4aonb1HeI2dBK+CElWldwdeDZqv6rOlmX4vau28Dy0zYm7VQY8ZZgct3LKg6pDbl",
	"Zn2iApcNbktlohv/HGdwI0ZOj6kUtIte4rRJ2L0+1ipXDwyYV0HP5eimVvm6g/6Bz+/CQXeOs1P1SqhS",
	"iZTyUe1VLL/uDcRbtQ6ED7UNHwjuemPGMIsxVxzjclt0qj9BYdloTk+c0togGupcTRcSXYzsl6YnUkOU",
	"f4x8yXLM+8vXo5OvX492hlH8CEzxmEyw2iLtMMTqoQ9ljnA8u0u8HqrVmnUxKFsLl1pjjMssc1Z7zLhh",
	"aiZBG3Kwci75BH8YgGCNGs9BiqUCpLWFBiOecZnAhxI+8HnPwep3WU4pdzsDY51XgvIrXvBdNkydVmG2",
	"zTyL2phpvjzmE/DJ9Iazp9YWZn97+6q2+AcYNbqC+SAVGmkUr1FjD/F7Rq0agpWfVeNu48gnnDcOSbiD",
	"EyJtMoXk6lCunYDSfdX4r6Xd/IO7l0XexxNMoVBG2OMmULTMPR22/B7yCNrZkbVBeTey+m5zYtDH4Xqe",
	"0sC3Mrvr8RQJzz7eFErbuhhuydnQYFnBta2iPgnPQKYcTUv8kEKwZGp+PT0Il4IJH7/cfKN1eDsE84YB",
	"6U4AcfOlFwKPAQDaoYM7VNw6N2nt+ovulHMerQq4O4eS+XonpnQK+i9En7HQxmJKzVkR3mTYaO/O1A9s",
	"uagty5Wfu1G3pDtytTnOndUZWFdXLL0ypmH53PE+hU64UXLzpU9ofGjtzcMpcYTy6L+869ZohwMj+PZ7",
	"lal8pEIsSvprY0jPpNigiDeNPOTxmrBOS+8u6bi27O0Kv7hlCDQqoCXcW7ioGbfaaUdONqRaPqsV4WvG",
	"W5LSS5ZFRwY2aq4WsTVPtk5iO/lW69K2uFoWkKtssMco1q7mekC1djcuGJLo+BfVX2DaZgIDdjAyLirm",
	"X6EN43sb5oxr+AvLhLGGaXDlj005JD5/QmMxnLIZPomB9wwGmHOv7m2F1Z8/uym2bCM1JcPDtaRZsJ5a",
	"YZXdUG7xec2pXqQ+xKa6n7XTC8q/pS2zuUXSi5fnMEt6F38u26QXgLubDz1T3Ya0SDnKRLJZnnFz9/sf",
	"kNzbnKvvnT+7q70V0trfXMtPb1ZtTc/SAkSd0cHlfINdndrAUBDlKSkO5JIUrr0nGCf2ZnOgBC7doMrM",
	"5fs39+XWRWb7uxxF4i2SNBXIETw77sC7AeuGs+g0NZU5UmRKpIMogGZKn2+OkNXdhdoV26VRvbEQZdtC",
	"43HIs5oc4dLMcJDU06llAAQz6s9JNsrK4G8JM3r2g2Ei9VVfGHTneZ1PfQIS35m6YiIP5dOWGkmYnZlQ",
	"5vlUl1BVmQtDKXLsefa+IqGrNJ0MRSvLa+tWz5VgNU2hDyl68ovFS9VPze6C2PUaoLvtz2oGOuEGmClH",
	"qcq5kCzjI8hcsqaqnWlXy3dzrxdREx++iDB+3Rsv7qZmm2HdoqZzvvUH1i69+P/7/s+ty+878au3t9Wb",
	"cD1TY40spz2pUfdAa3HNs0BTHMBViuWQvisu4fIHyzgOB6ZkzIa045NSprzb+13Lhzfr3IRFPsz5TUjM",
	"vHm9PlezuUzC8/0BGwYtZveX9o1dhr4SdTYVyZTkwRYWg3KHKuNqLpS6GrAjTK/YUkvynPOqpr2GZvdV",
	"FwWyzDIsnY72rS4hBN1MyFTNSHp0N7a7d7fGyRo7bbQu7n5hvXiBKUInhoJSy8ah937uXUws5BWkZLGG",
	"yjy+KZUbxl0IYov8NCfOkQyGWTWhDs6HXUHQa1Rob/VuUEmPNiVA0WO2zACuQKbfNp9vlX3gFood7j2U",
	"i5jso2CPtVCRcaF4rYeqS7WjcCOMdZXcXq2SsuVyzizcUErv95JKEW27vwmH1Np4sBF7bO6cb2qC3JPI",
	"dxA8T0N93edfnFERSq974a9kqfyzurk75xPY/nsBFBelH4Vs/p7BqKh/TEEkQV/harFJkLIMrus3+IER",
	"fwSSwR9veGIZvkOWGc0tmAGj+IBhZcGsYjuv2ZefYur2rR7hk9U1yeuFp8/Ct1HkYexH9KlIriBkgN+9",
	"dLB17U6fObz0zYISczMgPgzItL6WhrnKJLwMhydoHXPDJuK609PXbKyvWisHO1UdAh+fnfb0XOByG3Wk",
	"10VgS735GnyWK6M2RyqKSZmSSbUdV/V4p+IxXzdWg1dvqsF+tyayr8uhspsffL8P5FxkD+vHafotVoYI",
	"q3Er/ej7l/QSdFVZqZdWNWzrbsFBdNZpjIWDVCFoWe3QnUQOeJZkwLVLhdIXg24t9u7rvUfG3WpdGYq0",
	"/RW0GM9XSObFcqq9t7vvdl4teARo9Pddr+DqmqvLWBbSQVM1k5UOxmwOXQFW32flPu2W90dHIucZKvRj",
	"T9d1BsKDS8J9Vdkyj1BUNSm1sPMTnKfjDTu511MmXN3gJV0ZFNOqtPjYGuzzYs0dciwvDXYp41B30ZG/",
	"DIvsS5zPyYiKv/ej/9zy3vXWYets8kJ8cvbCCLgGja6us7Lw18/Vgf6Pv51GiwL8oH2dWV1XipeqbV8T",
	"96BdVT/ywb8B+8yNNagVc3c/CgJM2CbXnJZtwJtaW7jr1IQcq2WkvVfSap44Aw2ZBZ3JTzBnI56gITNg",
	"XwmPINNCCWnxorBrtMtTINhiVlBI+UI2I8h/Hs07rrOrR6MMo0gnYBem2XazDC4kWUWuHX2GnimXzGvw",
	"nq6lFwny20un/rhkhydfm76lC3khvzaMYKi5nXHm0NS9UA4B5JK1ycwcDzDJsYsPwb+QFYtZhXxDXHVQ",
	"0VBpZlQOSlIilQl/O6HnLFdqw23NpROw5kLuDffiJijFjeNIvwgOr685JNN7cCEpHW/p0FbkOjg+jOII",
	"ux8cXYeDncEQuVIVIHkhov3o1WA48PLFuZ3bU+q6/QP/njizBkUUxdgP02g/+gWsb8yNu5dP7g6Hj3bj",
	"n18hcOWfe8N8NyW+N2Wecz3HfYNGEebbyFyjLptWwFo+MRTCnxsLeXSJ39JBasXTgjvGZP9BE1V6sk23",
	"L4IL7LwCIWYqS8FYz0BmKgpXCISU3Rvu9C1Tw73duaSxLVej/fPvHZF1fnl72cZwBUPoKsQRZIpqm1UL",
	"2U0vIuXwTAC978ku8DM3d0v9pNL5o6G21d1321U7Vpdwu0TUnccmaoigbuOpI9twPdlat7s+PaUdcG2x",
	"U7sSC3TnhgqOq7RSgPLVQUONhR6bD0AEueGze/80bLCQeduIFfYChhQhgKnSDtiZvJJoVrkwNOPa3Uha",
	"uGsz1WBBRH30Cs+AQaHMRjAVqGKY1+RunjYakTpdFCpb9OPP7+2rLZ4Ih61+wI3wN3zMlakxsO8aYJUC",
	"3URsQNr7Hqrdd+s/WbzTt0vhU4x3cfZmKxUTYZvMCUJnlWsJqju8VhPa80Sb2Mvb7jAO08pyC4Yp6Tun",
	"0bAdsGPq7KMIHS5OFgSiyvciXUj3XeovyDVtHsWYATK0D9eZqdKW0e2frAAtVOqmy8Aaxi9kkgmQ1t3x",
	"0+Lr2VQZqC/6YcIyiQAyDQmIa0idBbPIy/TtiYPjn0gmPKLObyXBAldJw8wLlgdI/Eb23LgiwEVpQ4SV",
	"zVIredI5If3yx7m4Tyd+ui70M1PLp2QDlPIqQciW4HmGm8+p6dmwmVZywl7QP7/hw5edW6+rjkPywV7g",
	"+9/825cxU/pCzrjL9uF7N5dViqmxBcleWKV+y7mc/8athbyw5iWe1S5rvccqQ8YdQGh++57q2GWMvZ/k",
	"7AUlfd26F429/JZDr0n+C9gv8JS2+Bfow3lpQD/gNG5qf50GDC1vO/CWET73ZveC1e3wSG5dMl1G31mB",
	"EUmPwcc/o00s75nPpy8QCNON9py26PfPZnI7qgRM7B8MK7TCMHjvWekGEv2ZWXA36kucW/e6U2iifQM8",
	"XpNAnYEWFfZgSSejd9rKSDwhMTu19gGiNlDEqL3chYm1G/wcxMWP9tZ/VP/XE0vcsBC8PL+MVzIIYqLd",
	"Sy68oeaDl3SXBbR5pBnX8b+7ePzqWkP9/RhCYgClaSitRI2acZ265YqMywE7wfRSVefobMML2b5JhvzF",
	"6pYZSgdTO2rjRzYtqtShKkeKa7oOjOJ+Zgrmgr7kWYbxPZzKai4Np9aFkMHonNbW9QtPFEuoV3jmYEJ3",
	"3X9wNAE/erX+o+Y/g7n7ecEP3j2PKbXRBagPPsFVVKU5X6jUhTXB9ftO8pLM3/4u0ttVxlLnSDyxvO7D",
	"cFG//5cQtqub6lcIWa55DpbS+OffXdYIo+tNzojypF2hEbdwvCbfe3vZMusW+71k6hS4c9+r7i90z53r",
	"lw7YZ2rvekF5kpj5PoW4up3cGe+KKfnyQoZ7wPYZ1eD4abnWbjmR0o0nrVogHEYBMW96xRfSfemzMnPm",
	"rjMSKY3iaQpp7A8EDstgbOmGd67BX/GeYsANKcE1Zl10MsXYAdOcJrJTjmnMDPA6JHbk64pMc1XSGLR2",
	"Zs+oBpqM6BngfNQZR8BR4q1Te+QQQ9hylcWmyqR2yobZR4y62KmQkwtJZwlMSHmxr4ELGZB0IbXmDMMn",
	"VmsLd4w9r+G+TnZUxntXhvybaLmH6hQX1CFD3t051NzVuFJWVWqEsqwdbYJdLqv1SbdlaBOp5ztn+uXe",
	"Br04l0/Jgt0thRwOGtGohbS5pOweFK/p56f1s/koa4uGbcugTUr6rCGjv3qqP1jsbg0zVQh3KyPRefbt",
	"c51/hoIqInzFlRrXxWLUA4B6yMd2/oDBhTw+O23Ks9xd9LVpr6sbynxNFeWypStJs/7SLCE7+7yQrl8Q",
	"HYWq2Xbg/7eQu4lLZ2S54ryninB0Siyf2QvolB0G+NRXzilfJPd/srI5a78A5mboGpMaP/UtbUpTPWnr",
	"jFVn6vLWLUw3SdK6S6GItCTF7gsGm+uCeCEW7wm6jZfbThKesbS5tbIzzf72NnY5ZlNl7P7b4dthdHtZ",
	"w/i9lq+urOE2rp8gaTq/q4xs61lLIbSeVvtuD3Ti5vby9n8HAA==",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
