//go:build go1.22

// Package oapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package oapi

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"net/http"
	"time"

	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for BookingType.
const (
	Entire BookingType = "entire"
	Rooms  BookingType = "rooms"
)

// Valid indicates whether the value is a known member of the BookingType enum.
func (e BookingType) Valid() bool {
	switch e {
	case Entire:
		return true
	case Rooms:
		return true
	default:
		return false
	}
}

// Defines values for Currency.
const (
	EUR Currency = "EUR"
	GBP Currency = "GBP"
	LKR Currency = "LKR"
	USD Currency = "USD"
)

// Valid indicates whether the value is a known member of the Currency enum.
func (e Currency) Valid() bool {
	switch e {
	case EUR:
		return true
	case GBP:
		return true
	case LKR:
		return true
	case USD:
		return true
	default:
		return false
	}
}

// Defines values for HealthDatabase.
const (
	Down HealthDatabase = "down"
	Up   HealthDatabase = "up"
)

// Valid indicates whether the value is a known member of the HealthDatabase enum.
func (e HealthDatabase) Valid() bool {
	switch e {
	case Down:
		return true
	case Up:
		return true
	default:
		return false
	}
}

// Defines values for HealthStatus.
const (
	Degraded HealthStatus = "degraded"
	Ok       HealthStatus = "ok"
)

// Valid indicates whether the value is a known member of the HealthStatus enum.
func (e HealthStatus) Valid() bool {
	switch e {
	case Degraded:
		return true
	case Ok:
		return true
	default:
		return false
	}
}

// BookingType Whether guests book the whole place or individual rooms.
type BookingType string

// Currency defines model for Currency.
type Currency string

// Error defines model for Error.
type Error struct {
	// Code Example: slug_taken
	Code string `json:"code"`

	// Message Example: That booking page address is already taken.
	Message string `json:"message"`
}

// Health defines model for Health.
type Health struct {
	Database HealthDatabase `json:"database"`
	Status   HealthStatus   `json:"status"`
}

// HealthDatabase defines model for Health.Database.
type HealthDatabase string

// HealthStatus defines model for Health.Status.
type HealthStatus string

// NewProperty defines model for NewProperty.
type NewProperty struct {
	// BaseRate Nightly base rate in minor units.
	//
	// Example: 18000
	BaseRate int64 `json:"baseRate"`

	// BookingType Whether guests book the whole place or individual rooms.
	BookingType BookingType `json:"bookingType"`
	Currency    Currency    `json:"currency"`

	// Location Example: Unawatuna, Galle
	Location *string `json:"location,omitempty"`

	// Name Example: Kingfisher Villa
	Name string `json:"name"`

	// Slug Lowercase subdomain label used for the booking page, for example "kingfisher" in kingfisher.staykey.direct.
	//
	// Example: kingfisher
	Slug *Slug `json:"slug,omitempty"`
}

// Property defines model for Property.
type Property struct {
	BaseRate int64 `json:"baseRate"`

	// BookingPageUrl Example: https://kingfisher.staykey.direct
	BookingPageUrl string `json:"bookingPageUrl"`

	// BookingType Whether guests book the whole place or individual rooms.
	BookingType BookingType        `json:"bookingType"`
	CreatedAt   time.Time          `json:"createdAt"`
	Currency    Currency           `json:"currency"`
	Id          openapi_types.UUID `json:"id"`
	Location    *string            `json:"location,omitempty"`
	Name        string             `json:"name"`

	// Slug Lowercase subdomain label used for the booking page, for example "kingfisher" in kingfisher.staykey.direct.
	//
	// Example: kingfisher
	Slug Slug `json:"slug"`
}

// PropertyList defines model for PropertyList.
type PropertyList struct {
	Items []Property `json:"items"`
}

// PublicProperty defines model for PublicProperty.
type PublicProperty struct {
	BaseRate int64 `json:"baseRate"`

	// BookingType Whether guests book the whole place or individual rooms.
	BookingType BookingType `json:"bookingType"`
	Currency    Currency    `json:"currency"`
	Location    *string     `json:"location,omitempty"`
	Name        string      `json:"name"`

	// Slug Lowercase subdomain label used for the booking page, for example "kingfisher" in kingfisher.staykey.direct.
	//
	// Example: kingfisher
	Slug Slug `json:"slug"`
}

// Slug Lowercase subdomain label used for the booking page, for example "kingfisher" in kingfisher.staykey.direct.
//
// Example: kingfisher
type Slug = string

// BadRequest defines model for BadRequest.
type BadRequest = Error

// NotFound defines model for NotFound.
type NotFound = Error

// CreatePropertyJSONRequestBody defines body for CreateProperty for application/json ContentType.
type CreatePropertyJSONRequestBody = NewProperty

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// GetHealth Service and database health
	// (GET /healthz)
	GetHealth(w http.ResponseWriter, r *http.Request)
	// ListProperties List the owner's properties
	// (GET /v1/properties)
	ListProperties(w http.ResponseWriter, r *http.Request)
	// CreateProperty Create a property and its booking page address
	// (POST /v1/properties)
	CreateProperty(w http.ResponseWriter, r *http.Request)
	// GetPublicProperty Public details for a property's booking page
	// (GET /v1/public/properties/{slug})
	GetPublicProperty(w http.ResponseWriter, r *http.Request, slug Slug)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetHealth operation middleware
func (siw *ServerInterfaceWrapper) GetHealth(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHealth(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListProperties operation middleware
func (siw *ServerInterfaceWrapper) ListProperties(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListProperties(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateProperty operation middleware
func (siw *ServerInterfaceWrapper) CreateProperty(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateProperty(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetPublicProperty operation middleware
func (siw *ServerInterfaceWrapper) GetPublicProperty(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "slug" -------------
	var slug Slug

	err = runtime.BindStyledParameterWithOptions("simple", "slug", r.PathValue("slug"), &slug, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "slug", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetPublicProperty(w, r, slug)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of [http.ServeMux].
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	http.Handler
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/healthz", wrapper.GetHealth)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/v1/properties", wrapper.ListProperties)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/v1/properties", wrapper.CreateProperty)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/v1/public/properties/{slug}", wrapper.GetPublicProperty)

	return m
}

type BadRequestJSONResponse Error

type NotFoundJSONResponse Error

type GetHealthRequestObject struct {
}

type GetHealthResponseObject interface {
	VisitGetHealthResponse(w http.ResponseWriter) error
}

type GetHealth200JSONResponse Health

func (response GetHealth200JSONResponse) VisitGetHealthResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListPropertiesRequestObject struct {
}

type ListPropertiesResponseObject interface {
	VisitListPropertiesResponse(w http.ResponseWriter) error
}

type ListProperties200JSONResponse PropertyList

func (response ListProperties200JSONResponse) VisitListPropertiesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type CreatePropertyRequestObject struct {
	Body *CreatePropertyJSONRequestBody
}

type CreatePropertyResponseObject interface {
	VisitCreatePropertyResponse(w http.ResponseWriter) error
}

type CreateProperty201JSONResponse Property

func (response CreateProperty201JSONResponse) VisitCreatePropertyResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type CreateProperty400JSONResponse struct{ BadRequestJSONResponse }

func (response CreateProperty400JSONResponse) VisitCreatePropertyResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type CreateProperty409JSONResponse Error

func (response CreateProperty409JSONResponse) VisitCreatePropertyResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type GetPublicPropertyRequestObject struct {
	Slug Slug `json:"slug"`
}

type GetPublicPropertyResponseObject interface {
	VisitGetPublicPropertyResponse(w http.ResponseWriter) error
}

type GetPublicProperty200JSONResponse PublicProperty

func (response GetPublicProperty200JSONResponse) VisitGetPublicPropertyResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetPublicProperty404JSONResponse struct{ NotFoundJSONResponse }

func (response GetPublicProperty404JSONResponse) VisitGetPublicPropertyResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// GetHealth Service and database health
	// (GET /healthz)
	GetHealth(ctx context.Context, request GetHealthRequestObject) (GetHealthResponseObject, error)
	// ListProperties List the owner's properties
	// (GET /v1/properties)
	ListProperties(ctx context.Context, request ListPropertiesRequestObject) (ListPropertiesResponseObject, error)
	// CreateProperty Create a property and its booking page address
	// (POST /v1/properties)
	CreateProperty(ctx context.Context, request CreatePropertyRequestObject) (CreatePropertyResponseObject, error)
	// GetPublicProperty Public details for a property's booking page
	// (GET /v1/public/properties/{slug})
	GetPublicProperty(ctx context.Context, request GetPublicPropertyRequestObject) (GetPublicPropertyResponseObject, error)
}

type StrictHandlerFunc func(ctx context.Context, w http.ResponseWriter, r *http.Request, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	if options.RequestErrorHandlerFunc == nil {
		options.RequestErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	if options.ResponseErrorHandlerFunc == nil {
		options.ResponseErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		}
	}
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// GetHealth operation middleware
func (sh *strictHandler) GetHealth(w http.ResponseWriter, r *http.Request) {
	var request GetHealthRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetHealth(ctx, request.(GetHealthRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetHealth")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetHealthResponseObject); ok {
		if err := validResponse.VisitGetHealthResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListProperties operation middleware
func (sh *strictHandler) ListProperties(w http.ResponseWriter, r *http.Request) {
	var request ListPropertiesRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListProperties(ctx, request.(ListPropertiesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListProperties")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListPropertiesResponseObject); ok {
		if err := validResponse.VisitListPropertiesResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateProperty operation middleware
func (sh *strictHandler) CreateProperty(w http.ResponseWriter, r *http.Request) {
	var request CreatePropertyRequestObject

	var body CreatePropertyJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateProperty(ctx, request.(CreatePropertyRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateProperty")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreatePropertyResponseObject); ok {
		if err := validResponse.VisitCreatePropertyResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetPublicProperty operation middleware
func (sh *strictHandler) GetPublicProperty(w http.ResponseWriter, r *http.Request, slug Slug) {
	var request GetPublicPropertyRequestObject

	request.Slug = slug

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetPublicProperty(ctx, request.(GetPublicPropertyRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetPublicProperty")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetPublicPropertyResponseObject); ok {
		if err := validResponse.VisitGetPublicPropertyResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}
