/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Service and database health */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/otp": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Text a 6-digit sign-in code to a phone number */
        post: operations["requestOtp"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Check a code and sign in, creating the user on first sign-in */
        post: operations["verifyOtp"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Exchange a refresh token for new tokens
         * @description The refresh token rotates on every call. Presenting one that was already
         *     rotated revokes the session, except for a short grace period that lets a
         *     client retry a refresh whose response it never received.
         */
        post: operations["refreshSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** End the session behind a refresh token */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The signed-in user and the accounts they belong to */
        get: operations["getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update the signed-in user's profile */
        patch: operations["updateMe"];
        trace?: never;
    };
    "/v1/accounts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Accounts the signed-in user belongs to */
        get: operations["listAccounts"];
        put?: never;
        /** Create an account with the signed-in user as its owner */
        post: operations["createAccount"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/properties": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List the properties the caller can see
         * @description Caretakers limited to some properties only see those.
         */
        get: operations["listProperties"];
        put?: never;
        /**
         * Create a property and its booking page address
         * @description Owners only, since a property counts towards the plan. Send baseRate for a
         *     quick start with one unit, or setup with the full setup as onboarding publishes
         *     it, all in one transaction.
         */
        post: operations["createProperty"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/properties/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        /** A property with its full setup */
        get: operations["getProperty"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Change some of a property's setup
         * @description Send only the sections that changed. Lists (units, seasons, charges and so on)
         *     replace the whole list: items that carry the id of an existing item are updated,
         *     items with any other id are added, and items left out are removed. Units are
         *     archived rather than deleted. New units can be referred to by the id they were
         *     sent with from linkedUnitIds and season prices in the same request. Everything
         *     applies in one transaction. Owners and managers only.
         */
        patch: operations["updateProperty"];
        trace?: never;
    };
    "/v1/uploads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Get a link to upload a photo or logo
         * @description Returns a short-lived URL that accepts one file of exactly this type and size.
         *     PUT the file there with the returned headers, then send the key in a property's
         *     photos or branding.logoKey. Owners and managers only.
         */
        post: operations["createUpload"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/quote": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Price a stay
         * @description The breakdown the booking would store, priced with the property's rates, seasons,
         *     rate overrides, discounts, extras and charges. Owners and managers only.
         */
        post: operations["createQuote"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/bookings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Stays the caller can see, by arrival
         * @description Stays that overlap [from, to), ordered by check-in. Pass nextCursor back as cursor
         *     for the next page. Caretakers see the properties they look after, without money.
         */
        get: operations["listBookings"];
        put?: never;
        /**
         * Add a stay the owner took directly
         * @description Prices the stay (or takes customTotal), holds its nights and confirms it, with an
         *     optional first payment. Nights another stay or a block holds give 409 with the
         *     clash. Owners and managers only.
         */
        post: operations["createBooking"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/bookings/{bookingId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                bookingId: components["parameters"]["BookingId"];
            };
            cookie?: never;
        };
        /** One stay with its price lines, payments and slips */
        get: operations["getBooking"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Change a stay
         * @description Send the version you read and the fields that changed. A change of unit, dates,
         *     guests or extras prices the stay again unless customTotal is sent. A stale version
         *     gives 409 with code stale. Owners and managers only.
         */
        patch: operations["updateBooking"];
        trace?: never;
    };
    "/v1/bookings/{bookingId}/transitions": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                bookingId: components["parameters"]["BookingId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Move a stay to its next status
         * @description Approve or decline a request, confirm, check in or check out. Every role can check
         *     guests in and out; the rest is for owners and managers. Declining frees the nights.
         */
        post: operations["transitionBooking"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/bookings/{bookingId}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                bookingId: components["parameters"]["BookingId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Cancel a stay and record any refund
         * @description Frees the nights. The refund is up to the owner, up to what was paid; the
         *     cancellation policy only suggests it. Owners and managers only.
         */
        post: operations["cancelBooking"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/bookings/{bookingId}/payments": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                bookingId: components["parameters"]["BookingId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Record money the guest paid
         * @description Send slipId to accept the guest's bank slip with the payment. A payment on a stay
         *     awaiting payment confirms it. Owners and managers only.
         */
        post: operations["recordPayment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/slips/{slipId}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slipId: components["parameters"]["SlipId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Turn down a bank slip the guest uploaded
         * @description Owners and managers only.
         */
        post: operations["rejectSlip"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/properties/{id}/calendar": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        /**
         * Blocks and rate overrides for a stretch of nights
         * @description Nights in [from, to), the next twelve months by default. Stays come from
         *     /v1/bookings with the same propertyId, from and to.
         */
        get: operations["getCalendar"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/blocks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Close nights on some units
         * @description Nights a stay or another block holds give 409. Owners and managers only.
         */
        post: operations["createBlock"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/blocks/{blockId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                blockId: components["parameters"]["BlockId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Open a block's nights again
         * @description Owners and managers only.
         */
        delete: operations["deleteBlock"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/rate-overrides": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Set or clear the price and stay rules for some nights
         * @description Replaces the overrides on every unit and night in [from, to). Leave out price and
         *     minNights and send closedToArrival false to go back to the usual rates. Owners and
         *     managers only.
         */
        put: operations["setRateOverrides"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/public/properties/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Public details for a property's booking page */
        get: operations["getPublicProperty"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Health: {
            /** @enum {string} */
            status: "ok" | "degraded";
            /** @enum {string} */
            database: "up" | "down";
        };
        /**
         * @description Phone number with its country code. Returned in E.164, for example +94771234567.
         * @example +94771234567
         */
        Phone: string;
        OtpRequest: {
            phone: components["schemas"]["Phone"];
        };
        OtpSent: {
            phone: components["schemas"]["Phone"];
            /** Format: date-time */
            expiresAt: string;
            /**
             * @description Seconds before another code can be requested.
             * @example 30
             */
            resendAfter: number;
            /** @description The code itself. Development servers only, so test devices can sign in. */
            devCode?: string;
        };
        VerifyRequest: {
            phone: components["schemas"]["Phone"];
            /** @example 482913 */
            code: string;
            /**
             * @description Shown in the list of signed-in devices.
             * @example Nimal's iPhone
             */
            deviceName?: string;
        };
        RefreshRequest: {
            refreshToken: string;
        };
        AuthTokens: {
            accessToken: string;
            /** Format: date-time */
            accessTokenExpiresAt: string;
            refreshToken: string;
            /** Format: date-time */
            refreshTokenExpiresAt: string;
        };
        SignIn: {
            tokens: components["schemas"]["AuthTokens"];
            user: components["schemas"]["User"];
            accounts: components["schemas"]["Account"][];
            /** @description True when this sign-in created the user. */
            newUser: boolean;
        };
        /** @enum {string} */
        Language: "en" | "si";
        User: {
            /** Format: uuid */
            id: string;
            phone: components["schemas"]["Phone"];
            name: string;
            email?: string;
            language: components["schemas"]["Language"];
            /** Format: date-time */
            createdAt: string;
        };
        UserPatch: {
            name?: string;
            /** @description An empty string clears the email. */
            email?: string;
            language?: components["schemas"]["Language"];
        };
        Me: {
            user: components["schemas"]["User"];
            accounts: components["schemas"]["Account"][];
        };
        /** @enum {string} */
        Role: "owner" | "manager" | "caretaker";
        /** @enum {string} */
        AccountStatus: "trial" | "active" | "grace" | "lapsed" | "closed";
        /** @description An account as the signed-in user sees it, with their role in it. */
        Account: {
            /** Format: uuid */
            id: string;
            name: string;
            status: components["schemas"]["AccountStatus"];
            role: components["schemas"]["Role"];
            /** @description The properties this member is limited to. Empty means every property. */
            propertyIds: string[];
            /** Format: date-time */
            trialStartedAt: string;
            /** Format: date-time */
            createdAt: string;
        };
        AccountList: {
            items: components["schemas"]["Account"][];
        };
        NewAccount: {
            /** @example Kingfisher Villa */
            name: string;
        };
        /**
         * @description Lowercase subdomain label used for the booking page, for example "kingfisher" in kingfisher.staykey.direct.
         * @example kingfisher
         */
        Slug: string;
        /**
         * @description Whether guests book the whole place or individual rooms.
         * @enum {string}
         */
        BookingType: "entire" | "rooms";
        /** @enum {string} */
        Currency: "USD" | "LKR" | "EUR" | "GBP";
        NewProperty: {
            /** @example Kingfisher Villa */
            name: string;
            slug?: components["schemas"]["Slug"];
            bookingType: components["schemas"]["BookingType"];
            /** @example Unawatuna, Galle */
            location?: string;
            currency: components["schemas"]["Currency"];
            /**
             * Format: int64
             * @description Nightly rate in minor units for the one unit a quick start gets. Required without setup.units.
             * @example 18000
             */
            baseRate?: number;
            setup?: components["schemas"]["PropertyPatch"];
        };
        /**
         * Format: int64
         * @description An amount in minor units of the property's currency.
         */
        Money: number;
        /** @description A property with its full setup, as owners and managers see it. */
        Property: {
            /** Format: uuid */
            id: string;
            slug: components["schemas"]["Slug"];
            name: string;
            bookingType: components["schemas"]["BookingType"];
            location?: string;
            currency: components["schemas"]["Currency"];
            /**
             * Format: int64
             * @description The lowest unit rate, in minor units.
             */
            baseRate: number;
            /**
             * Format: uri
             * @example https://kingfisher.staykey.direct
             */
            bookingPageUrl: string;
            /** Format: date-time */
            createdAt: string;
            description: string;
            amenities: string[];
            checkIn: components["schemas"]["Clock"];
            checkOut: components["schemas"]["Clock"];
            /** @example Asia/Colombo */
            timeZone: string;
            /** @description In display order; the first is the cover. */
            photos: components["schemas"]["Photo"][];
            units: components["schemas"]["Unit"][];
            extraGuest: components["schemas"]["ExtraGuest"];
            seasons: components["schemas"]["Season"][];
            lengthDiscounts: components["schemas"]["LengthDiscount"][];
            rules: components["schemas"]["StayRules"];
            policy: components["schemas"]["Policy"];
            depositPercent: number;
            balanceDueDays: number;
            houseRules: string[];
            charges: components["schemas"]["Charge"][];
            extras: components["schemas"]["Extra"][];
            promos: components["schemas"]["Promo"][];
            payments: components["schemas"]["PaymentSettings"];
            booking: components["schemas"]["BookingSettings"];
            branding: components["schemas"]["Branding"];
            icalFeeds: components["schemas"]["IcalFeed"][];
            /** @description Secret part of the calendar export link for OTAs. */
            icalExportToken: string;
        };
        /** @description Sections to change. Absent sections stay as they are; lists replace the whole list. */
        PropertyPatch: {
            name?: string;
            bookingType?: components["schemas"]["BookingType"];
            description?: string;
            location?: string;
            checkIn?: components["schemas"]["Clock"];
            checkOut?: components["schemas"]["Clock"];
            amenities?: string[];
            policy?: components["schemas"]["Policy"];
            depositPercent?: number;
            balanceDueDays?: number;
            houseRules?: string[];
            rules?: components["schemas"]["StayRules"];
            booking?: components["schemas"]["BookingSettings"];
            branding?: components["schemas"]["BrandingInput"];
            payments?: components["schemas"]["PaymentSettings"];
            extraGuest?: components["schemas"]["ExtraGuest"];
            units?: components["schemas"]["UnitInput"][];
            seasons?: components["schemas"]["SeasonInput"][];
            lengthDiscounts?: components["schemas"]["LengthDiscount"][];
            charges?: components["schemas"]["ChargeInput"][];
            extras?: components["schemas"]["ExtraInput"][];
            promos?: components["schemas"]["PromoInput"][];
            photos?: components["schemas"]["PhotoInput"][];
            icalFeeds?: components["schemas"]["IcalFeedInput"][];
        };
        /** @example 14:00 */
        Clock: string;
        /**
         * Format: date
         * @example 2026-12-01
         */
        Day: string;
        /**
         * @description Month and day, repeating every year.
         * @example 12-15
         */
        MonthDay: string;
        /** @enum {string} */
        Policy: "flexible" | "moderate" | "strict";
        Photo: {
            /** Format: uuid */
            id: string;
            key: string;
            /** Format: uri */
            url: string;
            caption: string;
        };
        PhotoInput: {
            /** @description The key from /v1/uploads, or of a photo the property already has. */
            key: string;
            caption?: string;
        };
        Unit: {
            /** Format: uuid */
            id: string;
            name: string;
            sleeps: number;
            beds: string;
            rate: components["schemas"]["Money"];
            weekendRate?: components["schemas"]["Money"];
            /** @description Rooms a whole-house unit books together. */
            linkedUnitIds: string[];
        };
        UnitInput: {
            /** @description An existing unit's id, or any text unique in the request for a new unit. */
            id: string;
            name: string;
            sleeps: number;
            beds?: string;
            rate: components["schemas"]["Money"];
            weekendRate?: components["schemas"]["Money"];
            linkedUnitIds?: string[];
        };
        /** @description A charge per guest per night above the included guests. Amount 0 is off. */
        ExtraGuest: {
            above: number;
            amount: components["schemas"]["Money"];
        };
        Season: {
            /** Format: uuid */
            id: string;
            name: string;
            start: components["schemas"]["MonthDay"];
            end: components["schemas"]["MonthDay"];
            minNights?: number;
            /** @description Nightly price per unit id. */
            prices: {
                [key: string]: number;
            };
        };
        SeasonInput: {
            id?: string;
            name: string;
            start: components["schemas"]["MonthDay"];
            end: components["schemas"]["MonthDay"];
            minNights?: number;
            /** @description Nightly price per unit id, or per new unit's id from the same request. */
            prices: {
                [key: string]: number;
            };
        };
        LengthDiscount: {
            nights: number;
            percent: number;
        };
        StayRules: {
            minNights: number;
            maxNights: number;
            /** @description Hour until which same-day arrivals can book. Null turns them off. */
            sameDayCutoff: number | null;
            windowMonths: number;
            /** @description Weekdays guests can't arrive on, 0 for Sunday. */
            closedArrival: number[];
        };
        /** @enum {string} */
        ChargeKind: "percent" | "fixed";
        Charge: {
            /** Format: uuid */
            id: string;
            name: string;
            kind: components["schemas"]["ChargeKind"];
            /**
             * Format: int64
             * @description A whole percent, or minor units for fixed charges.
             */
            amount: number;
            /** @enum {string} */
            per: "stay" | "night" | "guest";
            enabled: boolean;
            note?: string;
        };
        ChargeInput: {
            id?: string;
            name: string;
            kind: components["schemas"]["ChargeKind"];
            /** Format: int64 */
            amount: number;
            /** @enum {string} */
            per: "stay" | "night" | "guest";
            enabled: boolean;
            note?: string;
        };
        /** @enum {string} */
        ExtraPer: "stay" | "night" | "guest" | "trip" | "guestNight";
        Extra: {
            /** Format: uuid */
            id: string;
            name: string;
            price: components["schemas"]["Money"];
            per: components["schemas"]["ExtraPer"];
            onRequest: boolean;
            enabled: boolean;
        };
        ExtraInput: {
            id?: string;
            name: string;
            price: components["schemas"]["Money"];
            per: components["schemas"]["ExtraPer"];
            onRequest: boolean;
            enabled: boolean;
        };
        Promo: {
            /** Format: uuid */
            id: string;
            code: string;
            kind: components["schemas"]["ChargeKind"];
            /** Format: int64 */
            amount: number;
            from?: components["schemas"]["Day"];
            to?: components["schemas"]["Day"];
            limit?: number;
            /** @description Bookings that used the code. Kept by the server. */
            used: number;
            minNights?: number;
            note?: string;
        };
        PromoInput: {
            id?: string;
            /** @example MONSOON10 */
            code: string;
            kind: components["schemas"]["ChargeKind"];
            /** Format: int64 */
            amount: number;
            from?: components["schemas"]["Day"];
            to?: components["schemas"]["Day"];
            limit?: number;
            minNights?: number;
            note?: string;
        };
        BankDetails: {
            enabled: boolean;
            bankName: string;
            accountName: string;
            /** @description Encrypted at rest. Hidden from caretakers. */
            accountNumber: string;
            payWithinHours: number;
            cancelIfUnpaid: boolean;
        };
        PaymentSettings: {
            bank: components["schemas"]["BankDetails"];
            atProperty: boolean;
            /**
             * @description The app can apply (pending) or withdraw (off); "on" comes from PayHere's approval.
             * @enum {string}
             */
            cards: "off" | "pending" | "on";
        };
        BookingSettings: {
            /** @enum {string} */
            mode: "instant" | "request";
            replyHours: number;
            holdMinutes: number;
            displayCurrencies: ("USD" | "EUR" | "GBP" | "AUD" | "INR" | "LKR")[];
        };
        Branding: {
            /** @example #09090b */
            color: string;
            logoKey?: string;
            /** Format: uri */
            logoUrl?: string;
        };
        BrandingInput: {
            color: string;
            /** @description A key from /v1/uploads, or the current logo's. Leave out to remove the logo. */
            logoKey?: string;
        };
        /** @enum {string} */
        IcalChannel: "airbnb" | "booking" | "agoda" | "expedia" | "other";
        IcalFeed: {
            /** Format: uuid */
            id: string;
            channel: components["schemas"]["IcalChannel"];
            url: string;
            /**
             * @description Pending until the import worker has read the link.
             * @enum {string}
             */
            status: "pending" | "ok" | "error";
            /** Format: date-time */
            lastSync?: string;
            error?: string;
            /** @description Imported stays from today on. */
            upcoming: number;
        };
        IcalFeedInput: {
            id?: string;
            channel: components["schemas"]["IcalChannel"];
            url: string;
        };
        UploadRequest: {
            /** @enum {string} */
            kind: "photo" | "logo";
            /** @enum {string} */
            contentType: "image/jpeg" | "image/png" | "image/webp" | "image/heic";
            /**
             * Format: int64
             * @description Exact size in bytes. Photos up to 15 MB, logos up to 5 MB.
             */
            size: number;
        };
        UploadTicket: {
            key: string;
            /** Format: uri */
            uploadUrl: string;
            /** @enum {string} */
            method: "PUT";
            /** @description Headers to send with the upload, exactly as given. */
            headers: {
                [key: string]: string;
            };
            /** Format: date-time */
            expiresAt: string;
            /**
             * Format: uri
             * @description Where the file is served once uploaded.
             */
            url: string;
        };
        PropertyList: {
            items: components["schemas"]["Property"][];
        };
        PublicProperty: {
            slug: components["schemas"]["Slug"];
            name: string;
            bookingType: components["schemas"]["BookingType"];
            location?: string;
            currency: components["schemas"]["Currency"];
            /** Format: int64 */
            baseRate: number;
        };
        /** @enum {string} */
        BookingStatus: "requested" | "awaiting_payment" | "confirmed" | "checked_in" | "checked_out" | "cancelled" | "declined";
        /**
         * @description Where the stay came from. airbnb, booking, agoda and expedia arrive by iCal.
         * @enum {string}
         */
        BookingSource: "page" | "widget" | "whatsapp" | "phone" | "walkin" | "other" | "airbnb" | "booking" | "agoda" | "expedia";
        /** @enum {string} */
        PaymentMethod: "bank" | "cash" | "card";
        /**
         * Format: int64
         * @description An amount in minor units that may be negative, such as a discount.
         */
        Signed: number;
        Guest: {
            name: string;
            phone?: string;
            email?: string;
            /** @description ISO 3166 two-letter code. */
            country?: string;
        };
        PriceLine: {
            label: string;
            amount: components["schemas"]["Signed"];
            /** @enum {string} */
            kind?: "discount" | "charge" | "extra";
        };
        Payment: {
            /** Format: uuid */
            id: string;
            /** @enum {string} */
            kind: "payment" | "refund";
            method: components["schemas"]["PaymentMethod"];
            amount: components["schemas"]["Money"];
            note: string;
            /** Format: date-time */
            receivedAt: string;
        };
        Slip: {
            /** Format: uuid */
            id: string;
            amount: components["schemas"]["Money"];
            /** @enum {string} */
            status: "pending" | "accepted" | "rejected";
            /** Format: date-time */
            uploadedAt: string;
            /** Format: uri */
            url: string;
        };
        /**
         * @description A stay. Money fields (total, lines, payments, slips, paid, balance) are left out for
         *     caretakers.
         */
        Booking: {
            /** Format: uuid */
            id: string;
            /** @example KV-2041 */
            ref: string;
            /** Format: uuid */
            propertyId: string;
            /** Format: uuid */
            unitId: string;
            source: components["schemas"]["BookingSource"];
            status: components["schemas"]["BookingStatus"];
            guest: components["schemas"]["Guest"];
            adults: number;
            children: number;
            checkIn: components["schemas"]["Day"];
            checkOut: components["schemas"]["Day"];
            currency: components["schemas"]["Currency"];
            total?: components["schemas"]["Money"];
            lines?: components["schemas"]["PriceLine"][];
            /** @description Ids of the extras booked. */
            extras: string[];
            payments?: components["schemas"]["Payment"][];
            slips?: components["schemas"]["Slip"][];
            paid?: components["schemas"]["Signed"];
            balance?: components["schemas"]["Money"];
            guestNote: string;
            ownerNote: string;
            /** Format: date-time */
            requestExpiresAt?: string;
            /** Format: date-time */
            paymentDueAt?: string;
            cancel?: {
                reason: string;
                /** Format: date-time */
                at: string;
            };
            /** @description Send back on changes; it moves on with every change. */
            version: number;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        BookingList: {
            items: components["schemas"]["Booking"][];
            /** @description Present when there are more stays. */
            nextCursor?: string;
        };
        NewBooking: {
            /** Format: uuid */
            propertyId: string;
            /** Format: uuid */
            unitId: string;
            checkIn: components["schemas"]["Day"];
            checkOut: components["schemas"]["Day"];
            adults: number;
            children?: number;
            guest: components["schemas"]["Guest"];
            source: components["schemas"]["BookingSource"];
            extras?: string[];
            customTotal?: components["schemas"]["Money"];
            ownerNote?: string;
            /** @description A first payment taken with the booking, such as a deposit. */
            payment?: {
                /** Format: int64 */
                amount: number;
                method: components["schemas"]["PaymentMethod"];
            };
        };
        BookingPatch: {
            version: number;
            /** Format: uuid */
            unitId?: string;
            checkIn?: components["schemas"]["Day"];
            checkOut?: components["schemas"]["Day"];
            adults?: number;
            children?: number;
            guest?: components["schemas"]["Guest"];
            source?: components["schemas"]["BookingSource"];
            extras?: string[];
            customTotal?: components["schemas"]["Money"];
            ownerNote?: string;
        };
        Transition: {
            /** @enum {string} */
            to: "awaiting_payment" | "confirmed" | "declined" | "checked_in" | "checked_out";
            version: number;
            reason?: string;
        };
        Cancellation: {
            version: number;
            reason: string;
            refund?: {
                /** Format: int64 */
                amount: number;
                method: components["schemas"]["PaymentMethod"];
            };
        };
        NewPayment: {
            /** Format: int64 */
            amount: number;
            method: components["schemas"]["PaymentMethod"];
            note?: string;
            /**
             * Format: date-time
             * @description Defaults to now.
             */
            receivedAt?: string;
            /**
             * Format: uuid
             * @description The pending slip this payment accepts.
             */
            slipId?: string;
        };
        QuoteRequest: {
            /** Format: uuid */
            propertyId: string;
            /** Format: uuid */
            unitId: string;
            checkIn: components["schemas"]["Day"];
            checkOut: components["schemas"]["Day"];
            adults: number;
            children?: number;
            extras?: string[];
            promo?: string;
        };
        Quote: {
            nights: number;
            nightly: {
                night: components["schemas"]["Day"];
                price: components["schemas"]["Money"];
            }[];
            lines: components["schemas"]["PriceLine"][];
            total: components["schemas"]["Signed"];
            currency: components["schemas"]["Currency"];
            /** @description The shortest stay allowed for this check-in. */
            minNights: number;
            deposit: components["schemas"]["Signed"];
        };
        /** @description The first night already taken, and what holds it. */
        Clash: {
            night: components["schemas"]["Day"];
            from: components["schemas"]["Day"];
            to: components["schemas"]["Day"];
            /** Format: uuid */
            bookingId?: string;
            ref?: string;
            guestName?: string;
            /** Format: uuid */
            blockId?: string;
        };
        ConflictError: {
            /** @enum {string} */
            code: "dates_taken" | "stale" | "bad_status";
            message: string;
            clash?: components["schemas"]["Clash"];
        };
        /** @enum {string} */
        BlockReason: "maintenance" | "owner" | "other";
        Block: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            propertyId: string;
            unitIds: string[];
            from: components["schemas"]["Day"];
            to: components["schemas"]["Day"];
            reason: components["schemas"]["BlockReason"];
            note: string;
        };
        NewBlock: {
            /** Format: uuid */
            propertyId: string;
            unitIds: string[];
            from: components["schemas"]["Day"];
            to: components["schemas"]["Day"];
            reason: components["schemas"]["BlockReason"];
            note?: string;
        };
        RateOverride: {
            /** Format: uuid */
            unitId: string;
            night: components["schemas"]["Day"];
            price?: components["schemas"]["Money"];
            minNights?: number;
            closedToArrival: boolean;
        };
        RateOverrideInput: {
            /** Format: uuid */
            propertyId: string;
            unitIds: string[];
            from: components["schemas"]["Day"];
            to: components["schemas"]["Day"];
            /** Format: int64 */
            price?: number;
            minNights?: number;
            closedToArrival?: boolean;
        };
        Calendar: {
            blocks: components["schemas"]["Block"][];
            rateOverrides: components["schemas"]["RateOverride"][];
        };
        Error: {
            /** @example slug_taken */
            code: string;
            /** @example That booking page address is already taken. */
            message: string;
            /**
             * @description The request field the error is about, when there is one.
             * @example slug
             */
            field?: string;
            /** @description Seconds to wait before retrying, on 429 responses. */
            retryAfter?: number;
        };
    };
    responses: {
        /** @description The access token is missing, invalid, expired or revoked */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description The caller's role does not allow this */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Too many requests. Retry after the number of seconds in retryAfter. */
        TooManyRequests: {
            headers: {
                "Retry-After"?: number;
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description The request was invalid */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Not found */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /**
         * @description The nights are taken (code dates_taken, with the clash), the stay changed since it
         *     was read (code stale), or its status doesn't allow this (code bad_status).
         */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ConflictError"];
            };
        };
        /** @description The Idempotency-Key was already used for a different request */
        KeyReused: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        Id: string;
        BookingId: string;
        SlipId: string;
        BlockId: string;
        /**
         * @description Any unique string, such as a UUID made when the form opened. A retry with the same
         *     key and body gets the first reply; the same key with another body gets 422. Keys
         *     last 24 hours.
         */
        IdempotencyKey: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Health status */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    requestOtp: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OtpRequest"];
            };
        };
        responses: {
            /** @description The code was sent */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OtpSent"];
                };
            };
            400: components["responses"]["BadRequest"];
            429: components["responses"]["TooManyRequests"];
        };
    };
    verifyOtp: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VerifyRequest"];
            };
        };
        responses: {
            /** @description Signed in */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SignIn"];
                };
            };
            /**
             * @description The code is wrong (wrong_code), expired or already used (code_expired), or
             *     was guessed wrong too often (too_many_attempts).
             */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    refreshSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"];
            };
        };
        responses: {
            /** @description New tokens */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthTokens"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"];
            };
        };
        responses: {
            /** @description Signed out. Unknown tokens are accepted too. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The user */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Me"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    updateMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserPatch"];
            };
        };
        responses: {
            /** @description The updated user */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    listAccounts: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Accounts, oldest membership first */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountList"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    createAccount: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NewAccount"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Account"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    listProperties: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Properties, newest first */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PropertyList"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    createProperty: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NewProperty"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Property"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            /** @description The booking page address is already taken */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getProperty: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The property */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Property"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    updateProperty: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PropertyPatch"];
            };
        };
        responses: {
            /** @description The updated property */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Property"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    createUpload: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UploadRequest"];
            };
        };
        responses: {
            /** @description Where to upload */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadTicket"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    createQuote: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QuoteRequest"];
            };
        };
        responses: {
            /** @description The price */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Quote"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    listBookings: {
        parameters: {
            query?: {
                propertyId?: string;
                from?: components["schemas"]["Day"];
                to?: components["schemas"]["Day"];
                cursor?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of stays */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookingList"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    createBooking: {
        parameters: {
            query?: never;
            header?: {
                /**
                 * @description Any unique string, such as a UUID made when the form opened. A retry with the same
                 *     key and body gets the first reply; the same key with another body gets 422. Keys
                 *     last 24 hours.
                 */
                "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NewBooking"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Booking"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["KeyReused"];
        };
    };
    getBooking: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                bookingId: components["parameters"]["BookingId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The stay */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Booking"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    updateBooking: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                bookingId: components["parameters"]["BookingId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BookingPatch"];
            };
        };
        responses: {
            /** @description The changed stay */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Booking"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    transitionBooking: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                bookingId: components["parameters"]["BookingId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Transition"];
            };
        };
        responses: {
            /** @description The stay in its new status */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Booking"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    cancelBooking: {
        parameters: {
            query?: never;
            header?: {
                /**
                 * @description Any unique string, such as a UUID made when the form opened. A retry with the same
                 *     key and body gets the first reply; the same key with another body gets 422. Keys
                 *     last 24 hours.
                 */
                "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
            };
            path: {
                bookingId: components["parameters"]["BookingId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Cancellation"];
            };
        };
        responses: {
            /** @description The cancelled stay */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Booking"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["KeyReused"];
        };
    };
    recordPayment: {
        parameters: {
            query?: never;
            header?: {
                /**
                 * @description Any unique string, such as a UUID made when the form opened. A retry with the same
                 *     key and body gets the first reply; the same key with another body gets 422. Keys
                 *     last 24 hours.
                 */
                "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
            };
            path: {
                bookingId: components["parameters"]["BookingId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NewPayment"];
            };
        };
        responses: {
            /** @description The stay with the payment */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Booking"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["KeyReused"];
        };
    };
    rejectSlip: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slipId: components["parameters"]["SlipId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The stay the slip belongs to */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Booking"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    getCalendar: {
        parameters: {
            query?: {
                from?: components["schemas"]["Day"];
                to?: components["schemas"]["Day"];
            };
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The calendar */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Calendar"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    createBlock: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NewBlock"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Block"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    deleteBlock: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                blockId: components["parameters"]["BlockId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    setRateOverrides: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RateOverrideInput"];
            };
        };
        responses: {
            /** @description Saved */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    getPublicProperty: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: components["schemas"]["Slug"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Public property details */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicProperty"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
}
