/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Service and database health */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/properties": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List the owner's properties */
        get: operations["listProperties"];
        put?: never;
        /** Create a property and its booking page address */
        post: operations["createProperty"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/public/properties/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Public details for a property's booking page */
        get: operations["getPublicProperty"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Health: {
            /** @enum {string} */
            status: "ok" | "degraded";
            /** @enum {string} */
            database: "up" | "down";
        };
        /**
         * @description Lowercase subdomain label used for the booking page, for example "kingfisher" in kingfisher.staykey.direct.
         * @example kingfisher
         */
        Slug: string;
        /**
         * @description Whether guests book the whole place or individual rooms.
         * @enum {string}
         */
        BookingType: "entire" | "rooms";
        /** @enum {string} */
        Currency: "USD" | "LKR" | "EUR" | "GBP";
        NewProperty: {
            /** @example Kingfisher Villa */
            name: string;
            slug?: components["schemas"]["Slug"];
            bookingType: components["schemas"]["BookingType"];
            /** @example Unawatuna, Galle */
            location?: string;
            currency: components["schemas"]["Currency"];
            /**
             * Format: int64
             * @description Nightly base rate in minor units.
             * @example 18000
             */
            baseRate: number;
        };
        Property: {
            /** Format: uuid */
            id: string;
            slug: components["schemas"]["Slug"];
            name: string;
            bookingType: components["schemas"]["BookingType"];
            location?: string;
            currency: components["schemas"]["Currency"];
            /** Format: int64 */
            baseRate: number;
            /**
             * Format: uri
             * @example https://kingfisher.staykey.direct
             */
            bookingPageUrl: string;
            /** Format: date-time */
            createdAt: string;
        };
        PropertyList: {
            items: components["schemas"]["Property"][];
        };
        PublicProperty: {
            slug: components["schemas"]["Slug"];
            name: string;
            bookingType: components["schemas"]["BookingType"];
            location?: string;
            currency: components["schemas"]["Currency"];
            /** Format: int64 */
            baseRate: number;
        };
        Error: {
            /** @example slug_taken */
            code: string;
            /** @example That booking page address is already taken. */
            message: string;
        };
    };
    responses: {
        /** @description The request was invalid */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Not found */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Health status */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    listProperties: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Properties, newest first */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PropertyList"];
                };
            };
        };
    };
    createProperty: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NewProperty"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Property"];
                };
            };
            400: components["responses"]["BadRequest"];
            /** @description The booking page address is already taken */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getPublicProperty: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: components["schemas"]["Slug"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Public property details */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicProperty"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
}
